concourse/dev-pipelines.yml
Add my own Concourse development pipeline.
=> Add Concourse dev pipeline for Richard

ci/config/space-users/dev-nim.csv, ci/config/space-users/dev-oswald.csv, ci/config/space-users/dev-stephen.csv, ci/config/space-users/staging.csv, ci/pipelines/provision-envs.yml
Create space for Oz, Nim and Stephen and grant them permission to
staging space.
=> Create dev spaces for other developers

ci/config/dev-pipelines.yml, ci/config/space-users/dev-rory.csv, ci/config/space-users/staging-cde.csv, ci/config/space-users/staging.csv
- Adds ```rory.malcolm@digital.cabinet-office.gov.uk``` to a new paas
environment and existing staging envs
=> BAU Add Rory

ci/config/dev-pipelines.yml, ci/config/space-users/dev-steven.csv, ci/config/space-users/staging-cde.csv, ci/config/space-users/staging.csv
* dev space configuration
* pipeline configuration
=> Add steven.fountain dev pipeline

ci/config/space-users/dev-stephen.csv
- Adds Rory Malcolm to the dev-stephen space
=> BAU Add Rory to dev-stephen

docs/source/infrastructure.html.md.erb
Adds a basic guide to setting up the project Terraform from scratch.
=> Document Terraform setup and usage

ci/pipelines/deploy.yml
Add in override to put card-frontend to staging-cde rather than default
staging space.
=> PP-6030 Push card-frontend to staging-cde

ci/pipelines/deploy.yml, ci/tasks/extract-artefact.yml, paas/env_variables/staging.yml
- selfservice, directdebit-frontend and products-ui
=> PP-6030 Switch node apps to buildpack deployment

ci/pipelines/deploy.yml, paas/env_variables/staging.yml, terraform/modules/paas/cardid-data.tf, terraform/modules/paas/cardid.tf
This will serve the data that cardid needs over HTTP. It will be read at
application startup.
See the ADR in https://github.com/alphagov/pay-omnibus/pull/67
=> Pp 6128 cardid data

ci/pipelines/build.yml
Now that this is building from travis it can be the same as all the
other java apps.
* Code review
* I've already `set-pipeline` from this branch, so check out the build pipeline
=> PP-6128: Add cardid build

ci/pipelines/deploy.yml, paas/fake-sqs.yml
Splits manifest for fake SQS container service into separate file.
=> Add separate manifest for fake SQS application

terraform/modules/paas/publicauth.tf, terraform/staging-paas/terraform.tfvars
Adds secret service and staging placeholder creds to publicauth
=> PP-6127: Add secret service to publicauth

terraform/modules/paas/toolbox.tf, terraform/staging-paas/terraform.tfvars
Adds toolbox-secret-service and corresponding creds/placeholders. Terraform has been tested and applied to staging environment.
=> PP-6127: Add toolbox-secret-service and corresponding creds

terraform/modules/paas/directdebit-frontend.tf, terraform/staging-paas/terraform.tfvars
Adds user-provided service to provide creds and config when bound to the directdebit-frontend app.
=> PP-6127: Add dd-frontend secret service and creds

terraform/modules/paas/selfservice.tf
Passing in secrets from pay-low-pass and pay-dev-pass
=> PP-6127 Provision selfservice secrets service

ci/config/dev-pipelines.yml, ci/config/space-users/dev-user-research
Add a new environment to use for user research purposes where we can push different versions of frontend etc. to try out prototypes.
=> Add environment for user research

client/client
Reverts alphagov/pay-omnibus#125
=> Revert "Don't abort create user if app isn't up"

ci/pipelines/deploy.yml, paas/metric-exporter/env-map.yml, paas/metric-exporter/manifest.yml, terraform/modules/paas/metric-exporter.tf, terraform/staging-paas/terraform.tfvars
Adds relevant CloudFoundry infra (via Terraform) and CI Concourse deployment tasks to deploy the PaaS metric-exporter application.
=> PP-6233: PaaS metric exporter infra

ci/scripts/migrate_database.sh
Adminusers uses an older style xml based migration for its initial state
before the liqibase migrations can kick off.
=> Add support for running Adminusers initial migration

ci/config/dev-pipelines.yml, ci/config/space-users/dev-anshul.csv
=> BAU Remove Anshul's Pipelines From Concourse

ci/pipelines/deploy.yml, ci/tasks/cf-v3-deploy.yml
Various fixes and refactoring of deploy pipeline for v3 deploys
=> Refactor deploy pipeline with reusable config

ci/pipelines/deploy.yml
- Enables zero downtime deploys for the staging environment.
=> BAU ZDT Enabled For Staging

terraform/modules/aws/card-frontend.tf, terraform/modules/aws/directdebit-frontend.tf, terraform/modules/aws/notifications.tf, terraform/modules/aws/products-ui.tf, terraform/modules/aws/selfservice.tf
- Adds the WAF rules to all other public facing apps
Co-authored-by: Richard Baker
<richard.baker@digital.cabinet-office.gov.uk>
=> PP-6447 Add WAF To Other Applcations

terraform/modules/aws/waf_v2_acl/main.tf
- Descriptions need single quotes wrapped in double quotes
=> PP-6447 Fix Quotes

terraform/modules/aws/kinesis-firehose.tf
- Creates a Kinesis firehose stream that places the output in S3
Co-authored by: Richard Baker
<richard.baker@digital.cabinet-office.gov.uk>
=> PP-6447 Create Kinesis Stream Output to S3

terraform/modules/aws/card-frontend.tf, terraform/modules/aws/directdebit-frontend.tf, terraform/modules/aws/notifications.tf, terraform/modules/aws/products-ui.tf, terraform/modules/aws/selfservice.tf, terraform/modules/aws/waf_v2_acl/configure_aws_wafv2.rb, terraform/modules/aws/waf_v2_acl/variables.tf
Adds logging configurations for all WAF ACLs. Supports optional Kinesis firehose ARN and optional field redaction configuration.
=> PP-6447: Create WAF log configurations for all ACLs

terraform/modules/aws/card-frontend.tf
- Redact Card Frontend Cookie Header
=> PP-6447 Redact Card Frontend Cookie Header

.gitingore
- add a gitignore, starting with folders named `/node_modules`
=> BAU Add gitignore

terraform/modules/aws/hosted-graphite.tf
- We get a warning when we run the TF
=> BAU Remove Interpolated Expression

docs/config/tech-docs.yml, docs/source/adrs.html.md.erb, docs/source/infrastructure.html.md.erb, docs/source/infrastructure/metrics.html.md, docs/source/infrastructure/using-terraform.html.md
Adds documentation for AWS/Hosted Graphite ingestion of CloudWatch metrics.
=> PP-6488: Document AWS/HG metrics

ci/pact_broker/pay-pact-broker_manifest.yml
To avoid any impact to existing CI pact process.
=> PP-6504 Add new pact broker for concourse pr pipeline

terraform/modules/aws/sqs.tf
Adds Terraform configuration for the three SQS queues used by
Pay applications. Queue configuration params are copied from
existing production values.
=> PP-6234: Add Terraform for three SQS queues (with dead-letters)

terraform/modules/aws/hosted-graphite.tf, terraform/modules/aws/iam.tf
Creates an `Applications` IAM user group, allowing "external" apps running on PaaS to have their own IAM user accounts belonging to this group.
=> PP-6234: Create IAM group for applications in iam.tf file

terraform/modules/aws/card-connector.tf, terraform/modules/aws/iam.tf, terraform/modules/aws/ledger.tf
- Creates new users for the applications which will have access to SQS
and KMS for encypting queue entries
=> PP-6234 Create Users For Apps With SQS Access

terraform/staging-paas/terraform.tfvars
- Create .tfvars mapping for AWS secret keys in Ledger and Connector
=> PP-6234 Create TFVars Mapping For AWS Secrets

terraform/staging-paas/terraform.tfvars
- Reflect the future state of the migration, at some point it wont be a
migration and in fact just reality, the path should reflect this.
=> PP-6234 Reflect Future Migration State

terraform/modules/aws/ledger.tf
- Give ledger the permission to GetAttributes on our SQS queues.
=> PP-6234 Ledger GetAttributes Permissions

docs/source/adrs/0011-sqs-queues.html.md
- Adds an ADR describing our thoughts on the configuration of SQS queues
on PaaS
=> PP-6234 Add SQS Queue ADR

terraform/modules/aws/card-connector.tf
- Connector should be able to read and write from the capture queue.
=> PP-6234 Add Capture Queue Read/Write

ci/pipelines/deploy.yml, ci/tasks/calculate-release-number.yml
Just trialling triggering deploy from master merge, adminusers first. Am I missing anything? Seems straight forward. Thought I'd seek some input before rolling it out for all apps. I've set the deploy pipeline from this change so you can see it working for Adminusers.
=> Pp 6676 trigger deploy from master merge

ci/docker/concourse-runner/Dockerfile
- Add netcat-openbsd to the omnibus base image
=> PP-6615 Add Netcat

ci/docker/concourse-runner/Dockerfile
- Add netcat to main install instead of community
=> PP-6615 Add Netcat and Git to main

ci/pipelines/deploy.yml, ci/tasks/send-hg-metric.yml
- Send two new metrics to hosted graphite regarding smoke tests run
statuses
=> PP-6615 Send HG Metrics Regarding Smoke Tests

ci/tasks/send-hg-metric.yml
- Mapping values are invalidating the pipeline when it runs the task
=> PP-6615 Fix Mapping Values

ci/tasks/send-hg-metric.yml
- Fix the inputs to the pipeline
=> PP-6615 Fix Inputs

ci/pipelines/deploy.yml, ci/tasks/send-hg-metric.yml
- Fix the access pattern for Hosted Graphite keys
=> PP-6686 Fix HG Key Pattern

ci/tasks/send-hg-metric.yml
- Use the "Echo" command instead of `<<<`
=> PP-6686 Echo Instead of Here-String

ci/tasks/send-hg-metric.yml
- Add a line break and revert to <<<
=> PP-6686 Add Line Break

ci/tasks/send-hg-metric.yml
=> PP-6686 Remove Echo

ci/tasks/send-hg-metric.yml
- Add a `-w` to the NC command
=> PP-6686 Add Wait

ci/docker/concourse-runner/Dockerfile
- We need to add the pact CLI and its dependencies to the dockerfile,
this is the beginnings of that
=> PP-6704 Update Dockerfile with Beginnings of Pact

ci/tasks/node-build-pr.yml
- Add toolbox specific logic to run the generate dev environment via
node, if it exists with the local flag
=> PP-6659 Add Toolbox Specific Logic

ci/pipelines/deploy.yml
- "Toolbox" APP_NAME should be "toolbox" and not "selfservice" for
deploys
=> PP-6659 Fix Toolbox App Name

ci/pipelines/pr.yml
Runs Pipecleaner (https://github.com/alphagov/paas-cf/tree/master/tools/pipecleaner) on all Concourse pipeline and task PRs.
=> BAU: Run pipecleaner on all omnibus pipelines and tasks

ci/pipelines/pr.yml
- Test PRs on ```alphagov/pay-js-commons```
=> PP-6845 Add Pay JS Commons PR Test

ci/tasks/node-build-pr.yml
- There's a second apt-get update here that is superfluous
=> PP-6845 Remove apt-get update

ci/tasks/node-build-pr.yml
- Karma tests need chromium in the container
=> PP-6845 Add Chromium

ci/tasks/node-build-pr.yml
Reverts alphagov/pay-omnibus#267
=> Revert "PP-6845 Add Chromium"

ci/pipelines/pr.yml, ci/tasks/node-build-pr.yml
- Move pay-js-commons CI to its own repo to reflect the structure of
other ad-hoc apps
=> PP-6845 Move pay-js-commons

ci/pipelines/pr.yml
- There was an issue with the indentation
=> PP-6845 Fix Pipeline

docs/source/adrs/0012-concourse-teams.html.md
- Split the teams into deploy and ci on concourse
=> PP-6871 ADR Split Concourse Teams

docs/source/adrs/0013-test-environment.html.md
Adds an ADR for creating the test environment.
=> PP-6870: ADR for test environment

paas/env_variables/staging.yml
- Change the base URL for Notify on staging before we change the API key
to the new staging one
=> PP-6883 Notify On Staging

terraform/staging-paas/terraform.tfvars
- Notify template and API key for the staging environment
=> PP-6883 Notify Template and API Key

terraform/modules/state-bucket/state-bucket.tf, terraform/modules/state-bucket/variables.tf, terraform/test-account/iam.tf, terraform/test-account/site.tf
Me and Toby have made your new AWS account.
Feel free to remove us.
=> Add new Pay Test account

ci/pipelines/pr.yml
- We want to test against the checkout instead of the merge commit
=> PP-6854 Integration Tool Merge -> Checkout

terraform/staging-paas/terraform.tfvars
- We have more templates! Provision them!
=> PP-6883 Add tfvars for adminusers and connector

terraform/staging-paas/terraform.tfvars
- Add connector refund email template ID
=> PP-6883 Add Connector Refund Email

ci/pipelines/pr.yml
=> PP-7062 Correct case for new serial groups

terraform/test-paas/site.tf, terraform/test-paas/terraform.tfvars, terraform/test-paas/variables.tf
- Add PaaS test environment application skeleton with ancilliary
services and network policies.
=> PP-7154 Create Test Environment

terraform/modules/aws/vpc.tf
- Create VPC peering connection accepter and prevent destruction of the
VPC peering connection
=> PP-7150 Create VPC Peering Connection Accepter

paas/env_variables/staging-smoke-tests.yml, paas/env_variables/test-smoke-tests.yml, paas/smoke-test-apps.yml
- Declare the smoke-tests-test application
=> PP-7027 Deploy Test Smoke Test

terraform/modules/aws/card-frontend.tf, terraform/modules/aws/notifications.tf, terraform/modules/aws/products-ui.tf, terraform/modules/aws/publicapi.tf, terraform/modules/aws/selfservice.tf, terraform/test-aws/site.tf
- Create vpc_peering_connection_accepter
- Accept connection
- Modify WAF creation rules
=> PP-7024 VPC Peering Acceptance

ci/pipelines/pr.yml
Add jobs for publishing connector consumer pacts and verifying against the provider for PRs
=> PP-7253 Add jobs for connector consumer tests to PR pipeline

.gitignore, README.md, ci/pipelines/concourse-runner.yml, ci/pipelines/docs.yml, ci/pipelines/pact-broker.yml, ci/pipelines/pr.yml, ci/tasks/endtoend/task.yml
So that people know what this repo is for
=> PP-7652 Rename omnibus to ci

ci/pipelines/apps-test-ecr.yml, ci/pipelines/toolbox-deploy-ecr.yml, ci/pipelines/toolbox-staging-ecr.yml
- This needs to be set-pipelined within pay-deploy, NOT pay-dev
=> PP-7703 Add staging ecr deployment

ci/pipelines/pr.yml, ci/tasks/java-package.yml, ci/tasks/java-tests.yml, ci/tasks/node-build-pr.yml, ci/tasks/node-build.yml, ci/tasks/pact-provider-test-preflight-check.yml, ci/tasks/pact-provider-verification.yml, ci/tasks/publish-pacts.yml, ci/tasks/zip-build.yml
Reverts alphagov/pay-ci#368 - this was causing failures on the pact tests.
=> Revert "BAU: fix ci-pr-test failures"

ci/pipelines/toolbox-staging-deploy.yml
Rename things to align with the fact that the job is a deploy job
=> PP-7796: Rename things

ci/pipelines/toolbox-staging-deploy.yml
Job toolbox-staging-deploy triggers and fetches from staging ECR when a new toolbox image with regex "[0-9]-release" tag is found.
=> PP-7796: Pull image from staging ecr

ci/pipelines/apps-test-ecr.yml
Missed these off first time round. Needed to trigger deploy pipeline.
=> PP-7794 Add variant to test ecr resources

ci/pipelines/apps-test-ecr.yml
As per pattern established by toolbox
=> PP-7794 Split cardid pipeline

ci/pipelines/toolbox-staging-deploy.yml, ci/scripts/wait-for-deploy.js
Green build: https://cd.gds-reliability.engineering/teams/pay-deploy/pipelines/toolbox-staging-deploy/jobs/toolbox-staging-deploy/builds/44
=> bau: Use the common assume-role.yml

ci/pipelines/apps-test-ecr.yml, ci/scripts/wait-for-deploy.js, ci/tasks/deploy-app.yml, ci/tasks/wait-for-deploy.yml
This PR extracts the `deploy-app` and `wait-for-deploy` tasks (ececf7a), and then uses them both in toolbox and in frontend pipelines (46de2ad).
I have also made some minor changes to `wait-for-deploy.js` in order to report more usefully whats happening at the wait for deploy stage (7bee460)
=> PP-7801 deploy frontend

ci/pipelines/apps-test-ecr.yml
Copy pasta of toolbox deployment - there shouldn't be any differences
=> PP-780X Add deployment pipelines for other apps

ci/pipelines/apps-test-ecr.yml, ci/tasks/pact-tag.yml
Task to tag a given version of given 'pacticipant' with a given tag.
See https://cd.gds-reliability.engineering/teams/pay-dev/pipelines/apps-test-ecr/jobs/frontend-pact-tag/builds/13
=> PP-7834 Pact tag task

ci/pipelines/apps-test-ecr.yml, ci/scripts/wait-for-deploy.js, ci/tasks/deploy-app.yml, ci/tasks/wait-for-deploy.yml
Pass in environment and account as params to `deploy-app` and `wait-for-deploy` tasks
=> PP-7686 Make deploy and wait tasks generic

ci/pipelines/deploy-to-production.yml
Same as staging except without push to a further ECR at the end (this is the end of the line)
=> PP-7687 Frontend production pipeline

ci/pipelines/deploy-to-production.yml
Add adminusers, products, products-ui, cardid and publicauth to prod pipeline following a well worn pattern
=> PP-7688 Add deploy to prod for 5 apps

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml
Connector and selfservice pipeline for staging and prod.
=> Pp 7688 connector selfservice pipeline

ci/pipelines/deploy-to-test.yml
This happens upon a successful smoke test in toolbox.
with: @nimalank7 @mrlumbu
=> PP-7877: Push telegraf image to staging ecr

ci/pipelines/deploy-to-staging.yml
Following the well established pattern
=> PP-7688 Add staging publicapi + ledger pipelines

ci/pipelines/deploy-to-production.yml
Following well established pattern
=> PP-7688 Pipelines for publicapi and ledger on prod

ci/pipelines/deploy-to-production.yml
=> PP-7688 Fix prod pipeline update

ci/pipelines/deploy-to-production.yml
Description:
- Correct pipeline is deploy-to-production and this PR updates the deploy-to-production.yml file correctly
=> BAU - Set deploy-to-production pipeline .yml file to correct name

ci/scripts/run_ecs_db_migration.js
A small whitespace change for the DB migration NodeJS script.
=> BAU: fix linting error

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml
As with telegraf, deploy new version of nginx in staging as part of toolbox deployment to check its ok before pushing up to prod, then deploy to toolbox in prod to check its ok in prod.
https://cd.gds-reliability.engineering/teams/pay-deploy/pipelines/deploy-to-staging?group=nginx-proxy
https://cd.gds-reliability.engineering/teams/pay-deploy/pipelines/deploy-to-production?group=nginx-proxy
=> PP-7755 nginx check staging prod

ci/pipelines/deploy-to-test.yml
Description:
- Adds a trigger to frontend to deploy to test when a new nginx-forward-proxy image appears in test ECR
=> PP-7755 - Trigger Frontend deployment to test on new nginx-forward-proxy image in test ECR

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml
Triggers for app deployments fixed in line with ADR https://docs.google.com/document/d/1oJ347kiaB_tBp-Q_7iZ1NC-xv-uQLz4etoyqI90IKVs/edit#
=> BAU Correct triggers on staging and prod pipelines

ci/pipelines/deploy-to-test.yml, ci/tasks/deploy-frontend.yml
Description:
- Frontend now deploys with the latest nginx proxy in test
- Refactors the inline task into a separate file called deploy-frontend.yml
=> PP-7915 - Frontend deploys with newest nginx version in test

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml
Description:
- Following the previous PR this replaces the inline task with a the deploy-frontend.yml file
- Frontend in both staging and prod will now deploy with the latest nginx proxy
=> PP-7915 - Frontend latest nginx staging and prod

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml, ci/tasks/deploy-app.yml, ci/tasks/wait-for-deploy.yml
Description:
- Remaining apps will be deployed to test with the latest version of nginx proxy
=> PP-7915 - Latest version of nginx for all test apps

ci/pipelines/deploy-to-production.yml
Description:
- Fix branch to master
=> BAU - Fix deploy to production branch

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml, ci/scripts/wait-for-deploy.js
Description:
- Display the nginx proxy version as output when the wait-for-deploy.js script runs
- If the app is frontend then also display the nginx frontend version as well otherwise don't
=> PP-7915 - Display nginx versions in deploy script

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml, ci/scripts/wait-for-deploy.js, ci/tasks/deploy-app.yml, ci/tasks/wait-for-deploy.yml
Description:
- All apps now deploy using the latest version of telegraf which is passed into the Terraform
=> PP-7915 - Latest telegraf for all apps

ci/tasks/deploy-frontend.yml
Description:
- Pass telegraf image to frontend
=> PP-7915 - Pass telegraf image to frontend

ci/pipelines/deploy-to-staging.yml
Description:
- Previous PR missed out a few renames of tag to application_image_tag
=> PP-7915 - Rename tag parameter staging

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-test.yml
Following pattern on staging pipeline.
See e.g. https://gds.slack.com/archives/CAEN2AVLP/p1616602359007400
from https://cd.gds-reliability.engineering/teams/pay-deploy/pipelines/deploy-to-production/jobs/deploy-toolbox-to-prod/builds/27
=> PP-7889 prod slack notifications

ci/pipelines/deploy-to-test.yml
Forgot to rename in test pipeline
=> PP-7889 Fix script rename

ci/pact_broker/pay-pact-broker_manifest.yml
Seeing some weird bugs that should be fixed in new version. Nothing too scary looking in release notes.
=> BAU Bump pact broker version

ci/pact_broker/pay-pact-broker_manifest.yml
This was not the right thing to do.
It was the wrong pact broker.
It seems to have broken everything.
Revert.
=> BAU revert pact broker bump

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml, ci/tasks/check-release-versions.yml
Extract existing check-release-versions task to, you guessed it, check release versions for all deployments in test, staging and prod pipeline.
=> PP-7908 check release versions on all deployments

ci/pipelines/deploy-to-test.yml
Missed these in original copy pasta fest
=> BAU Load success and failure snippets

ci/pipelines/deploy-to-test.yml
=> BAU Fix products ui test smoke test job

ci/pipelines/deploy-to-production.yml
=> BAU Add prod ledger smoke test slack notification

ci/pipelines/deploy-to-staging.yml
Put the `get: pay-ci` in wrong place didn't I?
=> BAU Fix staging connector smoke test job

ci/pipelines/deploy-to-test.yml
=> BAU Fix ledger smoke test

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml
Concourse is not doing the heavy lifting, so let's run 8 in parallel and see what happens
=> BAU increase parallelism of smoke tests

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml
This will make it easier to look for the job!
This has been applied to test; someone with the right perms will need to apply to staging/production.
=> bau: Order jobs in alphabetical order in concourse

ci/pipelines/deploy-to-staging.yml
- Add a DB migration for staging products deployments
=> PP-7921 Add Staging DB Migration

ci/pipelines/deploy-to-production.yml
- Add a DB migration for products products deployments
=> PP-7921 Add Prod Products DB Migration

ci/pipelines/pr.yml, ci/tasks/java-package.yml, ci/tasks/java-tests.yml
- Upgrades to latest maven version
=> PP-7967 Upgrade maven version from 3.6.1 to 3.8.1

ci/pipelines/deploy-to-staging.yml
- Adminusers DB migration staging
=> PP-7920 Adminusers DB Migration Staging

ci/pipelines/deploy-to-production.yml
[Succesful deploy to prod](https://cd.gds-reliability.engineering/teams/pay-deploy/pipelines/deploy-to-production/jobs/deploy-carbon-relay-to-prod/builds/2).
=> PP-8162: Deploy carbon-relay to production

ci/pipelines/deploy-smoke-tests.yml
Following on from the move of our smoke tests Terraform, this updates the Concourse Pipelines to point towards the new location of the smoke tests Terraform.
=> [PP-8142] Update path of smoke test Terraform.

ci/pipelines/deploy-smoke-tests.yml
Updating the terraform commands as we have changed the module names in
https://github.com/alphagov/pay-infra/pull/3143.
=> PP-8157: Update deploy smoke test pipeline

ci/pipelines/deploy-smoke-tests.yml
These changed paths were updated in https://github.com/alphagov/pay-infra/pull/3162.
=> PP-8413: Update smoke_tests path

ci/docker/node-runner/Dockerfile
- update to latest security release of NodeJS
=> PP-8418 update NodeJS to 12.2.4

ci/pipelines/deploy-to-staging.yml
This creates the Deploy-to-Staging Pipeline for the Egress Proxy. Not a lot else to say really.
When ready to deploy, run:
```
fly -t pay-deploy set-pipeline -p deploy-to-staging -c ci/pipelines/deploy-to-staging.yml
```
=> [PP-8167] Create Deploy-to-Staging Egress Pipe

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml, ci/tasks/create-egress-notification-snippets.yml
This has been run successfully: https://cd.gds-reliability.engineering/teams/pay-deploy/pipelines/deploy-to-production?group=egress
=> PP-8167: Deploy egress to production

ci/scripts/run_smoke_test.js
- These functions and dependencies are no longer used
=> BAU Remove Unused Functions

ci/pipelines/deploy-to-production.yml
This makes it consistent with "update-deploy-to-staging-pipeline" and
"update-deploy-to-test-pipeline".
=> PP-8773: Update deploy pipeline name

ci/pipelines/pr.yml, ci/tasks/create-notification-snippets.yml, ci/tasks/java-package.yml, ci/tasks/java-tests.yml, ci/tasks/node-build-pr.yml, ci/tasks/node-build.yml, ci/tasks/pact-provider-test-preflight-check.yml, ci/tasks/pact-provider-verification.yml, ci/tasks/parse-release-tag.yml, ci/tasks/publish-pacts.yml, ci/tasks/zip-build.yml
There are a lot of shellcheck erros in the ci for this repo, most of them are trivial to fix. Hopefully this PR should produce a green build and also still work everywhere.
=> BAU: Fix shellcheck errors

ci/docker/node-runner/Dockerfile
Driveby update of alpine while we pinned the aws-sdk and octoreset
=> Update alpine version and pin node and octorest to major versions

ci/pipelines/pr.yml
Amending as per the rules at https://concourse-ci.org/config-basics.html#schema.identifier.
There are way more identifiers to rectify but thought I'd raise this as a preliminary pass for people to have a look at.
=> bau: Address deprecation warnings

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml
There are no smoke tests covering toolbox, this PR removes the smoke test toolbox steps of the deploy pipelines, currently the tests don't add any value since no test touches toolbox, they just delay the deployment.
<details><summary>deploy-to-test</summary>
```
$ fly -t pay-cd-dev set-pipeline -c deploy-to-test.yml  -p deploy-to-test
groups:
group toolbox has changed:
jobs:
- push-toolbox-to-test-ecr
- deploy-toolbox
- - smoke-test-toolbox
- push-toolbox-to-staging-ecr
name: toolbox
jobs:
job smoke-test-toolbox has been removed:
- name: smoke-test-toolbox
- on_failure:
-   params:
-     channel: '#govuk-pay-announce'
-     icon_emoji: ':fargate:'
-     text: "((.:failure_snippet)) \n - <https://pay-cd.deploy.payments.service.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/job …
```
=> BAU: Remove smoke-test-toolbox steps

ci/pipelines/deploy-to-test.yml
Parallelise the get steps
Also parallelise the load_var and assume_role steps
Running with the change set https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/run-frontend-e2e/builds/5
The change would look like this:
```
jobs:
job run-frontend-e2e has changed:
name: run-frontend-e2e
plan:
- - get: frontend-candidate-ecr-registry-test
-   trigger: true
- - file: frontend-candidate-ecr-registry-test/tag
-   load_var: candidate_image_tag
- - get: pay-ci
- - file: pay-ci/ci/tasks/assume-role.yml
-   params:
-     AWS_ROLE_ARN: arn:aws:iam::((pay_aws_test_account_id)):role/pay-cd-pay-dev-codebuild-executor-test-12
-     AWS_ROLE_SESSION_NAME: e2e-test-assume-role
-   task: assume-role
+ - in_parallel:
+     steps:
+     - get: …
```
=> PP-9229: Parallelise some steps in frontend e2e tests

ci/pipelines/deploy-to-test.yml
Running card e2e is not required here.
=> PP-9233: e2e tests for products and products-ui

ci/pipelines/codebuild-e2e.yml
https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/codebuild-e2e/jobs/frontend/builds/181 🥳
=> PP-9230: Run zap test as part of frontend e2e job

ci/pipelines/pr.yml
Run all PR e2e tests automatically and without waiting for unit tests to pass first
=> PP-9361: Run pr e2e tests automatically 

ci/pipelines/pr.yml
Resolve all the remaining deprecation warnings in pr-ci
It was essentially all that you cannot have spaces in task names:
before:
```
DEPRECATION WARNING:
- jobs.record-connector-build-time.plan.do[1].task(send pr build time to Hosted Graphite): 'send pr build time to Hosted Graphite' is not a valid identifier: illegal character ' '
- jobs.record-endtoend-build-time.plan.do[1].task(send pr build time to Hosted Graphite): 'send pr build time to Hosted Graphite' is not a valid identifier: illegal character ' '
- jobs.record-publicapi-build-time.plan.do[1].task(send pr build time to Hosted Graphite): 'send pr build time to Hosted Graphite' is not a valid identifier: illegal character ' '
- jobs.record-java-commons-build-time.plan.do[1].task(send pr build time to Hosted Graphite): 'send pr …
```
=> BAU: Resolve derepcation warnings in pr-ci pipeline

ci/tasks/endtoend/card/docker-compose.yml, ci/tasks/endtoend/products/docker-compose.yml, ci/tasks/endtoend/zap/docker-compose.yml
The changes at https://github.com/alphagov/pay-endtoend/pull/1183 makes this work.
=> PP-9306: Use selenium/standalone-chrome:3.141.59

ci/pipelines/deploy-to-test.yml
Build docker image and push to ECR.
=> PP-9253: Build job for alphagov/pay-stream-s3-sqs

ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml
Build that pushes image to staging ecr: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/push-stream-s3-sqs-to-staging-ecr/builds/1.
Build that pushes image to prod ecr: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/deploy-to-staging/jobs/push-stream-s3-sqs-to-production-ecr/builds/1
=> PP-9253: Push stream-s3-sqs image staging and prod

ci/tasks/parse-release-tag.yml
Add release-number as an output of parse-release-tag
=> PP-9210: Add release-number output from parse-release-tag

ci/pipelines/deploy-to-test.yml
=> PP-9213: Build adminusers in concourse

.github/workflows/_run-provider-contract-tests.yml
Set the pact provider version explicitly to the sha of the master release
=> PP-9213: Set provider version for pact provider tests

ci/pipelines/deploy-to-test.yml
Build ledger and connector on concourse. Based on https://github.com/alphagov/pay-ci/pull/656/files since they are both java apps
=> Pp 9213 build connector and ledger in concourse

ci/pipelines/deploy-to-test.yml
Build and push both products and publicapi in concourse
=> PP-9213: products and publicapi builds

ci/pipelines/deploy-to-test.yml
Build and push publicauth in concourse
=> PP-9213: Build publicauth

ci/pipelines/deploy-to-test.yml
Build frontend, products-ui, and toolbox. (also make the toolbox deploy need the build and push)
=> PP-9213: Build frontend, products-ui, toolbox

ci/pipelines/concourse-runner.yml, ci/pipelines/control-plane.yml, ci/pipelines/e2e-helpers.yml, ci/pipelines/infra-drift-detector-higher-envs.yml, ci/pipelines/infra-drift-detector-lower-envs.yml, ci/pipelines/node-runner.yml
Add jobs to automatically update all pipelines (which are defined in this repo) when master is merged and the pipeline definition is changed.
=> Bau add pipeline self update tasks

ci/pipelines/deploy-to-production.yml
This follows the pattern laid out in
https://github.com/alphagov/pay-ci/pull/676. Sidecar images will be dealt with
in another PR.
🟢 jobs can be seen at https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/deploy-to-production.
=> PP-8295: Retag app images with xxx-perf

ci/pipelines/deploy-to-perf.yml
🟢  🎉  https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-perf/jobs/deploy-adminusers-to-perf/builds/7
=> PP-8295: Deploy adminusers to perf

ci/scripts/run-ecs-db-migration.js
Example successful build: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/adminusers-db-migration/builds/8
=> PP-9266: Wait for migration to complete

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml
Example run on test: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/adminusers-db-migration/builds/13
Example run on staging: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/deploy-to-staging/jobs/adminusers-db-migration-staging/builds/5
Example run on prod: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/deploy-to-production/jobs/adminusers-db-migration-prod/builds/5
=> PP-9266: Success/failure notification for db jobs

ci/pipelines/deploy-to-perf.yml
[Example successful build](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-perf/jobs/adminusers-db-migration-perf/builds/2).
[Database migration status dashboard for the above run](https://gds.splunkcloud.com/en-GB/app/gds-004-pay/migration_status?form.field1.earliest=-24h%40h&form.field1.latest=now&form.environment=test-perf-1).
=> PP-9266: Trigger DB migration on perf

ci/pay_stubs/pay-stubs_manifest.yml, ci/pipelines/pay-stubs.yml
- Added a new manifest to deploy `pay-stubs` to paas
- Added a new pipeline definition to continuously deploy `pay-stubs`
=> PP-9582 manifest and pipeline for `pay-stubs`

ci/pipelines/concourse-runner.yml, ci/pipelines/pr.yml
Also sneakily fixing the webhooks-integration-test.
See https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/concourse-runner for a 🍏 build.
=> PP-9829: Concourse-runner-with-java-17 build pipeline

ci/pipelines/pr.yml
🍏 build: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/pr-ci/jobs/webhooks-as-consumer-pact-test/builds/2
=> PP-9829: Run provider (ledger) contract test

ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml
Add smoke testing and pact tagging stages to the `webhooks` test and staging deployment pipelines
=> PP-9829 smoke test and pact tag stages

ci/pipelines/deploy-to-staging.yml
Update the deploy-to-staging pipeline to start moving images into the production ecr repos
=> PP-9792 push webhooks images to prod

ci/tasks/create-egress-notification-snippets.yml
This has been annoying me for weeks
=> BAU: Fix curly braces appearing in webhooks-egress slack notification

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-test.yml
`webhooks` deploy-to-production jobs:
- `webhooks`: deploy, smoke test, migrate and pact tag
- `webhooks-egress`: deploy and smoke test
=> PP-9792 concourse jobs for webhooks services in production

ci/pipelines/deploy-to-test.yml
Change pay-ci branch back to master
=> BAU: Fix deploy-to-test pipeline

ci/tasks/check-release-versions.yml, ci/tasks/get-git-sha-for-release-tag.yml, ci/tasks/node-build-pr.yml, ci/tasks/parse-perf-db-release-tag.yml, ci/tasks/parse-perf-release-tag.yml, ci/tasks/run-smoke-test.yml, ci/tasks/wait-for-deploy.yml
updated more task with node 16
=> PP-9392 updated node runner to tag 16

ci/tasks/node-build-pr.yml
Previously we were using node:12-stretch for this task
Also fixes some typos in the comments
Successful unit test build: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/pr-ci/jobs/products-ui-test/builds/855
=> PP-9392: Use govukpay/node-runner repository

ci/pipelines/e2e-helpers.yml
Added trigger:true to pay-infra-src resource in pay-ci repo
=> PP-10050 Added trigger:true to pay-infra-src resource in pay-ci repo

.github/workflows/_run-provider-contract-tests.yml
- updated GHA to pull new image dependency
=> PP-10004 M1 support for integration tests

.github/dependabot.yml, actions/detect-secrets/Dockerfile, actions/detect-secrets/README.md, actions/detect-secrets/action.yml, actions/detect-secrets/entrypoint.sh, ci/docker/detect-secrets/Dockerfile, ci/pipelines/detect-secrets.yml
- added custom GH action to run `detect-secrets` against an established baseline
- fixed some yml formatting
- added `detect-secrets base` image definition
- concourse pipeline to manage build and push of `detect-secrets` image
=> PP-10116 add GH action for secrets detection

.github/workflows/detect-secrets.yml, .pre-commit-config.yaml, .secrets.baseline
See https://github.com/alphagov/pay-webhooks/pull/510 for details
=> PP-10116: Update detect-secrets to 1.4.0, add GHA workflow

ci/docker/node-runner/Dockerfile.node16
=> PP-10283: node updated

ci/tasks/endtoend/docker-config/productsui.env
- add a new env var for demo payments return url that was changed due to removing gateway cookies from selfservice
=> PP-10413 add products ui demo payment return url

ci/pipelines/e2e-helpers.yml, ci/tasks/send-job-release-info-to-hosted-graphite.yml
added task to send job release metric from e2e-helpers
=> PP-10335: Send job release metric to Hosted graphite

ci/tasks/check-pact-compatibility.yml, ci/tasks/pact-tag.yml
- removing reference to jenkins from concourse pact tasks
related to and requires https://github.com/alphagov/pay-infra/pull/4275
@Rkotyank
=> PP-8597 update pactbroker secret refs

ci/tasks/check-canaries-in-error-state.yml
- Added stripe recurring card canary to the list of canaries checked for error state
=> PP-10496 Update list of canaries to check in error state

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml, ci/tasks/check-canaries-in-error-state.yml
- Added Sandbox recurring card payment smoke test task to post-deploy job for all environments
=> PP-10496 Add Sandbox recurring payment smoke test task

ci/tasks/parse-release-tag.yml
Small PR to rename tag name introduced by https://github.com/alphagov/pay-ci/pull/881 to fix typo.
=> PP-11028: Rename tag name

ci/pipelines/prometheus-pushgateway.yml
[Successful concourse job](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/prometheus-pushgateway/jobs/push-adot-to-deploy-ecr/builds/1). This resulted in the [ADOT image now in deploy ECR](https://eu-west-1.console.aws.amazon.com/ecr/repositories/private/424875624006/govukpay/adot?region=eu-west-1).
=> PP-11272: Push ADOT image to deploy ecr

ci/pipelines/pay-js.yml
Set `js-commons-git-release` trigger to `true`.
=> PP-9356 automate `js-commons` release

ci/pipelines/deploy-to-test.yml
Correct a broken link in DB migration Slack message.
=> PP-11309-fix-db-migration-slack-link

ci/pipelines/stubs.yml
Re-enable Slack integration now pipeline works.
=> PP-11785-enable-stubs-slack-integration

ci/scripts/run_smoke_test.js, ci/tasks/check-canaries-in-error-state.yml
Point manual links to new domain.
=> PP-11868-update-manual-references

ci/pipelines/e2e-helpers.yml, ci/tasks/endtoend/card/docker-compose.yml, ci/tasks/endtoend/products/docker-compose.yml, ci/tasks/endtoend/zap/docker-compose.yml
Bump Postgres used in e2e tests from 11 to 15.2.
=> PP-11895-bump-e2e-postgres-version

ci/pipelines/deploy-to-test.yml
- Removed build-jar task as it is no longer required
=> PP-10385 Remove build-jar task from adminusers job

ci/tasks/build-docker-image.yml
- remove `build` input as it is no longer required
=> PP-11936 Fix E2E build

ci/pipelines/deploy-to-perf.yml, ci/pipelines/perf-tests.yml
We did a DR recovery of the publicauth database in perf, change the scale tasks to scale the new DB
=> PP-11646: Change scale tasks to scale publicauth restored DB

ci/pipelines/deploy-to-test.yml
- Builds ledger images in CodeBuild.
- [build and push candidate job](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/build-and-push-ledger-candidate/builds/507)
- [retag manifest](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/run-ledger-e2e/builds/540)
- [DockerHub](https://hub.docker.com/layers/governmentdigitalservice/pay-ledger/1705-candidate/images/sha256-1b12db725620abf7087ad5a226efff3257b25ee98c1d21cc3b80617104fc79ce?context=repo)
- [ECR](https://eu-west-1.console.aws.amazon.com/ecr/repositories/private/223851549868/govukpay/ledger/_/image/sha256:7c75fe0b7ed59fac9b6fc2b58313f4cf8022a4a525309e6f4ddabaa2dc637823/details?region=eu-west-1)
=> PP-12011 Build ledger in CodeBuild

ci/pipelines/deploy-to-test.yml
Build AMD and ARM Products images in CodeBuild. Push to ECR and DockerHub and tag for release if tests pass.
* [Concourse build](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/build-and-push-products-candidate/builds/309)
* [Docker Hub images](https://hub.docker.com/repository/docker/governmentdigitalservice/pay-products/general)
* [ECR images](https://eu-west-1.console.aws.amazon.com/ecr/repositories/private/223851549868/govukpay/products?region=eu-west-1)
=> PP-12013-build-products-in-codebuild

ci/pipelines/deploy-to-test.yml
Add Slack notifications for mutliarch CodeBuild jobs.
=> BAU-fix-slack-notifications

ci/pipelines/deploy-to-test.yml
- Builds webhooks images in CodeBuild.
- [Dockerhub](https://hub.docker.com/repository/docker/governmentdigitalservice/pay-webhooks/tags?page=1&ordering=last_updated)
**- ECR**
- [Concourse](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/build-webhooks/builds/551)
=> PP-12014 Build webhooks in CodeBuild

ci/pipelines/deploy-to-test.yml
- Builds selfservice images in CodeBuild.
**Concourse:** 
- Build - https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/build-and-push-selfservice-candidate/builds/641
- e2e tests - https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/run-selfservice-e2e/builds/642
**Dockerhub**
**ECR**
=> PP-12028 Build selfservice in CodeBuild

ci/pipelines/deploy-to-test.yml
- Builds frontend images using CodeBuild.
**Concourse**
- Build candidate - https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/build-and-push-frontend-candidate/builds/611
- Retag - https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/run-frontend-e2e/builds/669
**ECR**
**Dockerhub**
=> PP-12027 Build frontend in CodeBuild

ci/pipelines/deploy-to-test.yml
Build multi-arch toolbox in CodeBuild.
* [Concourse run](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/build-and-push-toolbox-to-test-ecr/builds/276)
* [Images in test ECR](https://eu-west-1.console.aws.amazon.com/ecr/repositories/private/223851549868/govukpay/toolbox?region=eu-west-1)
* [Images in Docker Hub](https://hub.docker.com/repository/docker/governmentdigitalservice/pay-toolbox/general)
=> PP-12029-build-toolbox-in-codebuild

ci/pipelines/deploy-to-test.yml
Build multi-arch nginx-proxy in CodeBuild
* [Concourse Run](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/build-and-push-nginx-proxy-to-test-ecr/builds/33)
* [images in ECR](https://eu-west-1.console.aws.amazon.com/ecr/repositories/private/223851549868/govukpay/docker-nginx-proxy?region=eu-west-1)
* [Images in Docker Hub](https://hub.docker.com/repository/docker/governmentdigitalservice/pay-docker-nginx-proxy/general)
=> PP-12031-build-nginx-proxy-in-codebuild

ci/pipelines/deploy-to-test.yml
Fix e2e for publicauth. 
[Concourse run](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/run-publicauth-e2e/builds/329)
=> PP-12080-fix-publicauth-e2e

ci/pipelines/deploy-to-test.yml
- Builds alpine images in CodeBuild
- [Concourse](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/build-and-push-alpine-to-ecr/builds/22)
- ECR
=> PP-12036 Build alpine images in CodeBuild

ci/pipelines/deploy-to-test.yml
- Builds adot images in CodeBuild
- [Concourse](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/build-and-push-adot-candidate/builds/12)
- ECR
=> PP-12036 Build adot images in CodeBuild

ci/pipelines/deploy-to-test.yml
- Builds pay-nginx-forward-proxy images in CodeBuild
- [Concourse](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/build-and-push-nginx-forward-proxy-to-test-ecr/builds/54)
- ECR
=> PP-12032 Build pay-nginx-forward-proxy images in CodeBuild

ci/pipelines/deploy-to-test.yml
- Builds webhooks-egress images in CodeBuild
- [Concourse](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/build-and-push-webhooks-egress-to-test-ecr/builds/31)
- ECR
=> PP-12026 Build webhooks-egress images in CodeBuild

ci/pipelines/concourse-runner.yml
- Passes repo inputs to test-concourse-runner task (build-and-push-concourse-runner jobs) so it can run app integration tests
=> PP-12125 Fix concourse-runner builds

ci/pipelines/grafana-annotation-resource.yml
Fix the filepath for the pipeline self update job
successful run: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/grafana-annotation-resource/jobs/update-grafana-annotation-resource-pipeline/builds/4
=> PP-12218: Fix filepath for pipeline self-update

ci/pipelines/deploy-to-staging.yml
Missed sending the metric from push-adminusers-to-production-ecr
```
jobs:
job push-adminusers-to-production-ecr has changed:
name: push-adminusers-to-production-ecr
+ on_failure:
+   params:
+     job: deployment_pipeline_app_release_number/pipeline/$BUILD_PIPELINE_NAME/concourse_job/$BUILD_JOB_NAME/app/((.:app_name))/outcome/failure
+     labels:
+       app: ((.:app_name))
+       conocurse_job: $BUILD_JOB_NAME
+       environment: staging-2
+       instance: concourse
+       outcome: failure
+       pipeline: $BUILD_PIPELINE_NAME
+     metric: deployment_pipeline_app_release_number
+     value: ((.:app_release_number))
+   put: send-app-release-number-metric
+   resource: prometheus-pushgateway
+ on_success:
+   params:
+     job: …
```
=> PP-12216/add-missed-metric-from-staging

ci/pipelines/deploy-to-perf.yml, ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml
- Sends connector release metrics for all environments
- [Metrics](https://grafana.monitoring.pay-cd.deploy.payments.service.gov.uk/d/e5000e04-deef-4ac7-8ffc-b7364c241dd1/release-pipeline-releases?orgId=1&var-app=connector&var-pipeline_step=build-and-push-connector-candidate&var-pipeline_step=run-connector-e2e&var-pipeline_step=deploy-connector&var-pipeline_step=smoke-test-connector&var-pipeline_step=connector-pact-tag&var-pipeline_step=push-connector-to-staging-ecr&var-pipeline_step_staging=deploy-connector-to-staging&var-pipeline_step_staging=smoke-test-connector-on-staging&var-pipeline_step_staging=connector-pact-tag&var-pipeline_step_staging=push-connector-to-production-ecr&var-pipeline_step_production=deploy-connector-to-prod&var-pipeline_step_production=smoke-test-connector-on-prod&v …
=> PP-12263 Send connector release metrics for staging, prod and test-perf-1

ci/pipelines/deploy-to-test.yml
- Sends release metrics for frontend jobs (deploy to test)
=> PP-12265 Send frontend release metrics in test

ci/pipelines/deploy-to-perf.yml
- Sends frontend test-perf-1 release metrics
=> PP-12265 Send frontend test-perf-1 metrics

ci/pipelines/deploy-to-perf.yml, ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml
- Sends ledger release metrics (all envs)
=> PP-12266 Send ledger release metrics

ci/pipelines/deploy-to-perf.yml, ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml
- Sends release metrics for all products jobs
=> PP-1267 Send products release metrics

ci/docker/concourse-runner-with-java-17/Dockerfile, ci/docker/concourse-runner/Dockerfile
Add pkl to the concourse runner images.
=> PP-12343: Add pkl to concourse-runner images

ci/pipelines/deploy-to-perf.yml, ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml
- Sends metrics for publicapi jobs (all envs)
=> PP-12269 Send publicapi release metrics

ci/pipelines/deploy-to-test.yml, ci/tasks/create-egress-notification-snippets.yml, ci/tasks/parse-release-tag.yml
Update deploy-to-test to send release metrics for the egress app jobs.
=> PP-12264: Send release metrics for egress in test

ci/pipelines/deploy-to-perf.yml, ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml
- Sends metrics for products-ui jobs (all envs)
=> PP-12268 Send products-ui release metrics

ci/pkl-pipelines/common/pipeline_self_update.pkl, ci/pkl-pipelines/common/shared_resources.pkl, ci/pkl-pipelines/detect-secrets.pkl, ci/pkl-pipelines/pay-deploy/prometheus-pushgateway.pkl, ci/pkl-pipelines/prometheus-pushgateway.pkl
`fly -t pay-deploy set-pipeline -c ./prometheus-pushgateway.yml -p prometheus-pushgateway`
```diff
resources:
resource prometheus-pushgateway-pipeline has changed:
icon: github
name: prometheus-pushgateway-pipeline
source:
branch: master
+   password: ((github-access-token))
paths:
- ci/pipelines/prometheus-pushgateway.yml
uri: https://github.com/alphagov/pay-ci
+   username: alphagov-pay-ci-concourse
type: git
pipeline name: prometheus-pushgateway
```
=> PP-12402 Pkl module for prometheus-pushgateway pipeline

ci/pipelines/deploy-to-staging.yml
Update `deploy-to-staging` to send release metrics for the egress app jobs.
Pipeline applied:
```
jobs:
job deploy-egress-to-staging has changed:
name: deploy-egress-to-staging
on_failure:
-   params:
-     channel: '#govuk-pay-announce'
-     icon_emoji: ':fargate:'
-     text: "((.:failure_snippet)) \n - <https://pay-cd.deploy.payments.service.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Concourse
-       build #$BUILD_NAME>"
-     username: pay-concourse
-   put: slack-notification
+   in_parallel:
+     steps:
+     - params:
+         channel: '#govuk-pay-announce'
+         icon_emoji: ':fargate:'
+         text: "((.:failure_snippet)) \n - <https://pay-cd.deploy.payments.service.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PI …
```
=> PP-12264: Send release metrics for egress in staging

ci/pkl-pipelines/pay-deploy/pact-broker.pkl
- Added pkl module for pact broker
fly -t pay-deploy set-pipeline -c ./pact-broker.yml -p pact-broker --dry-run
```diff
resources:
resource pact-broker-pipeline has been removed:
- icon: github
- name: pact-broker-pipeline
- source:
-   branch: master
-   paths:
-   - ci/pipelines/pact-broker.yml
-   uri: https://github.com/alphagov/pay-ci
- type: git
resource pact-broker-src has changed:
icon: github
name: pact-broker-src
source:
branch: master
+   password: ((github-access-token))
paths:
- ci/docker/pact-broker/*
uri: https://github.com/alphagov/pay-ci
+   username: alphagov-pay-ci-concourse
type: git
resource pay-ci has changed:
icon: github
name: pay-ci
source:
branch: master
+   password: ((github-access-token))
uri: https://github.com/alphagov/pay-ci
+   username: …
```
=> PP-12403 Add pkl module for pack broker

ci/pipelines/deploy-to-production.yml
Publicauth wasn't getting retagged correctly on push to test-perf, it's now 10 releases behind.
This fixes that retagging, and makes all the retagging jobs more consistent.
It also renames any parsing and loading var for the perf-db tag to include -db in it so it's easier to pick out.
```diff
$ fly-pay-deploy set-pipeline -c deploy-to-production.yml -p deploy-to-production
jobs:
job retag-publicauth-image-for-test-perf has changed:
name: retag-publicauth-image-for-test-perf
on_failure:
params:
job: deployment_pipeline_app_release_number/pipeline/$BUILD_PIPELINE_NAME/concourse_job/$BUILD_JOB_NAME/app/((.:app_name))/outcome/failure
labels:
app: ((.:app_name))
conocurse_job: $BUILD_JOB_NAME
environment: production-2
instance: concourse
outcome: failure
pipeline: $BUILD_PIPELINE_NAME
metric: …
```
=> BAU: Fix incorrect retag into perf, and make retagging more consistent

ci/pkl-pipelines/common/shared_resources_for_metrics.pkl
- Added shared pkl module for metrics
- a separate one so `shared_resources` doesn't get bloated with everything
=> PP-12420 Add shared module for metrics

ci/pkl-pipelines/common/shared_resources_for_slack_notifications.pkl
- Added a separate shared resource for slack notifications
=> PP-12420 Add shared resource for slack notifications

ci/pkl-pipelines/pay-dev/deploy-to-perf.pkl
- Added missing variable for frontend job
- assume-role for DB migration is done separately after the `get (pay-ci)` task as concourse is erroring on `unknown artifact source: 'pay-ci' in file path 'pay-ci/ci/tasks/assume-role.yml'`
- created a separate variable to deploy `scheduled-tasks` as it is easy to miss if it is somewhere in the methods
=> PP-12420 Further fixes for deploy-to-perf jobs

ci/pkl-pipelines/common/shared_resources_for_slack_notifications.pkl, ci/pkl-pipelines/pay-deploy/deploy-to-production.pkl
- Added deploy-to-prod pkl module
To see changes locally
> cd ci/pkl-pipelines/pay-deploy
>
> pkl eval -f yaml deploy-to-production.pkl && fly -t pay-deploy set-pipeline -c ./deploy-to-production.yml -p deploy-to-production --dry-run | zmore
=> PP-12422 Convert deploy-to-prod pipeline to pkl

ci/pkl-pipelines/pay-deploy/deploy-to-production.pkl
- Changed the order of loading variables 
- Added metrics for retag-images for DB migration job
=> PP-12422 Fixes to deploy-to-production pkl module

ci/pkl-pipelines/pay-deploy/deploy-to-production.pkl
- Loading missing variables to send job metrics
- Removed slack notifications as we were not doing this before
=> PP-12422 Fix retag image for test-perf DB job

ci/pkl-pipelines/common/shared_resources_for_deploy_pipelines.pkl, ci/pkl-pipelines/pay-dev/deploy-to-test.pkl
- Added deploy-to-test pkl module
To see changes locally
> cd ci/pkl-pipelines/pay-dev
>
> pkl eval -f yaml deploy-to-test.pkl > deploy-to-test.yml && fly -t pay-dev set-pipeline -c ./deploy-to-test.yml -p deploy-to-test --dry-run | zmore
=> PP-12423 Convert deploy-to-test pipeline to pkl

ci/pkl-pipelines/common/shared_resources_for_deploy_pipelines.pkl, ci/pkl-pipelines/common/shared_resources_for_slack_notifications.pkl, ci/pkl-pipelines/pay-deploy/deploy-to-production.pkl, ci/pkl-pipelines/pay-dev/deploy-to-perf.pkl, ci/pkl-pipelines/pay-dev/deploy-to-test.pkl
- Refactored Slack notifications and metrics functions to use classes
=> PP-12423 Refactor deploy pipelines

ci/pkl-pipelines/common/shared_resources.pkl, ci/pkl-pipelines/pay-deploy/pact-broker.pkl, ci/pkl-pipelines/pay-deploy/prometheus-pushgateway.pkl, ci/pkl-pipelines/pay-dev/e2e-helpers.pkl
- Refactored e2e-helpers, pack-broker and prometheus-pushgateway modules to use shared Slack notifications resources
- and removed unused Slack notification functions
=> PP-12423 Refactor modules to use shared slack notifications resource

.github/workflows/_run-app-as-provider-contract-tests.yml, .github/workflows/_run-provider-pact-tests-for-consumer.yml
- Added/updated contract test job names. 
**For adminusers PRs, below is the change**
=> PP-12570 Add or update contract test names

ci/pipelines/pr.yml
- Removed all (except E2E) selfservice tests
- depends on https://github.com/alphagov/pay-selfservice/pull/4219
=> PP-12579 Remove selfservice tests

.github/workflows/_create-alpha-release-tag.yml, ci/pipelines/pr.yml
- Removed all (except E2E) products-ui tests from Concourse
- Depends on https://github.com/alphagov/pay-products-ui/pull/2680
=> PP-12576 Remove products-ui tests

ci/pipelines/pr.yml
- Removed all (except E2E) frontend tests from Concourse
- Depends on https://github.com/alphagov/pay-frontend/pull/3831
=> PP-12573 Remove frontend tests

ci/pipelines/pr.yml
- Removes webhooks tests from Concourse
- Depends on https://github.com/alphagov/pay-webhooks/pull/1283
=> PP-12581 Remove webhooks tests

ci/pkl-pipelines/common/shared_resources_for_lock_pools.pkl
1. Make lock claims timeout after 10 minutes
2. Try 10 times to get the lock
3. Only try 3 times to release the lock (this usually fails quite fast, and 10 attempts at it is pointless)
=> BAU: Wait 10 mins to claim lock, retry 10 times

.github/workflows/_run-node-install-and-compile.yml
- Added input to NodeJs workflow to disable compiling if not required (applicable for pay-stubs)
=> PP-12615 Run `compile` step conditionally

ci/pipelines/pr.yml
- Removed all (except E2E) publicapi tests from Concourse
=> PP-12577 Remove publicapi tests

.editorconfig, ci/scripts/assume-role.js
- Added default editorconfig file and formatted `assume-role` script
=> PP-12783 Add editorconfig and format assume-role script

ci/docker/node-runner/Dockerfile, ci/pkl-pipelines/pay-dev/deploy-to-test.pkl, ci/scripts/package-lock.json, ci/scripts/package.json, ci/tasks/get-git-sha-for-release-tag.yml, ci/tasks/parse-perf-db-release-tag.yml, ci/tasks/parse-perf-release-tag.yml, ci/tasks/run-codebuild.yml
- Removed deprecated (and now unused) AWS SDK v2
- Updated tasks to use node18 everywhere
=> PP-12783 Remove AWS SDK v2

ci/pipelines/support-rota-notifications.yml, ci/scripts/support-rota-notification/access-control-util.js, ci/scripts/support-rota-notification/index.js, ci/scripts/support-rota-notification/package-lock.json, ci/scripts/support-rota-notification/package.json, ci/scripts/support-rota-notification/pagerduty-client.js, ci/scripts/support-rota-notification/slack-client.js, ci/tasks/support-rota-notifications.yml
- Job and related scripts to update support/incident channel topics for rota changes
=> PP-12796 Job to set support (rota) topics

ci/docker/concourse-runner/README.md, ci/scripts/test-concourse-runner.sh
- Added test to check docker scout installation
=> PP-12758 Test docker scout

ci/pkl-pipelines/pay-deploy/internal-vulnerability-scan.pkl, ci/scripts/run-vulnerability-scan/generate_vulnerability_report.js, ci/scripts/run-vulnerability-scan/package-lock.json, ci/scripts/run-vulnerability-scan/package.json, ci/scripts/run-vulnerability-scan/scan.sh, ci/tasks/run-vulnerability-scan.yml
- pipeline to run internal vulnerability scan
Concourse job https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/internal-vulnerability-scan/jobs/run-vulnerability-scan/builds/1
=> PP-12758 Pipeline to run vulnerability scan

ci/pipelines/support-rota-notifications.yml
- Use `main` branch for `pay-access-control`
=> PP-12796 Fix branch name

ci/pkl-pipelines/pay-deploy/internal-vulnerability-scan.pkl, ci/scripts/run-vulnerability-scan/create-jira-issue.sh, ci/scripts/run-vulnerability-scan/scan.sh, ci/tasks/create-vulnerability-scan-jira-issue.yml, ci/tasks/run-vulnerability-scan.yml
- Added task to concourse job to create JIRA story to triage internal vulnerability scan report
Concourse job
- https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/internal-vulnerability-scan/jobs/run-vulnerability-scan/builds/3
=> PP-12759 Add task to create story to triage vulnerability scan

ci/pkl-pipelines/pay-dev/infra-drift-detector.pkl
The CI account is now closed. Remove the unsubscribed SNS topic check
=> PP-13083: Remove CI sns unsubscriber check

ci/docker/detect-secrets/Dockerfile, ci/docker/node-runner/Dockerfile, ci/tasks/create-egress-notification-snippets.yml, ci/tasks/create-notification-snippets.yml, ci/tasks/generate-docker-config-file.yml, ci/tasks/get-image-tag-from-dockerfile.yml, ci/tasks/parse-candidate-tag.yml, ci/tasks/parse-ecr-release-tag.yml, ci/tasks/parse-release-tag.yml, ci/tasks/prepare-perftests-codebuild.yml
Update, and standardise, on direct alpine usage to float on the latest released 3.x version
=> PP-13021: Update alpine

ci/pkl-pipelines/common/shared_resources.pkl, ci/pkl-pipelines/common/shared_resources_for_multi_arch_builds.pkl, ci/pkl-pipelines/pay-dev/bastion.pkl
Add a bastion build pipeline.
See https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/bastion/jobs/build-and-push-bastion/builds/8 for a successful run
=> Pp 12812/build bastion pipeline

ci/pkl-pipelines/common/shared_resources_for_deploy_pipelines.pkl, ci/tasks/check-for-tf-drift.yml
I missed a couple from the PR, I just forgot to add the files when committing :(
=> PP-12812: Make notifications deploy with loaded tf version and run infra drift detector

ci/tasks/endtoend/card/docker-compose.yml, ci/tasks/endtoend/products/docker-compose.yml, ci/tasks/endtoend/zap/docker-compose.yml
Set BIND_HOST env var for all containers in the e2e tests.
You can see it works since this config is itself run through the end to end tests (see the e2e tests check).
=> PP-13145: Set BIND_HOST env vars for all end to end task containers

ci/pkl-pipelines/pay-deploy/pay-js.pkl
Two things:
1. I don't know how to run this to check it, I've made the changes I'd expect to work but haven't run them yet (reaching out to the relevant people to go through that process with).
2. I've added `short_name` and `really_short_name` that should probably be renamed if they're needed.  As I'm not sure they're needed I haven't put much effort into naming them yet.
=> PP-13234: Adding a pipeline for run-amock

ci/pkl-pipelines/pay-dev/pr-ci.pkl, ci/scripts/test-bastion/index.js, ci/scripts/test-bastion/package-lock.json, ci/scripts/test-bastion/package.json, ci/tasks/get-pr-info.yml, ci/tasks/run-bastion-e2e.yml
- Added a new job to test bastion for PRs
Working E2E test
https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/pr-ci/jobs/aws-bastion-e2e/builds/2
Depends on https://github.com/alphagov/pay-infra/pull/5012
=> PP-13142 Bastion e2e test for PRs

ci/scripts/test-bastion/index.js, ci/scripts/test-bastion/package-lock.json, ci/scripts/test-bastion/package.json
##WHAT
- For the bastion E2E tests
- checks DB connection after opening the tunnel
- and checks bastion task is stopped after disconnecting the session
**Concourse job:**
https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/pr-ci/jobs/aws-bastion-e2e/builds/3
Depends on https://github.com/alphagov/pay-infra/pull/5015
=> PP-13142 Bastion E2E test - check DB connection and task status

ci/scripts/check-release-versions.js
I have confirmed this is correct after intercepting the failed task and running the below command from the command line and it logged in successfully. Also matches other examples in the code base.
=> Correct Fly Login Command When Checking Downgrade

ci/scripts/test-bastion/index.js
Update bastion e2e test to account for https://github.com/alphagov/pay-cli/pull/136
=> PP-12479: Update bastion e2e test for new prompt

ci/pipelines/support-rota-notifications.yml, ci/scripts/support-rota-notification/index.js, ci/scripts/support-rota-notification/slack-client.js
- Added jobs to notify support people about triaging alerts during the weekend & to update support notes
=> PP-13222 Jobs for support notifications

.github/workflows/_run-node-cypress-tests.yml, .github/workflows/_run-node-install-and-compile.yml
- add `dist` to cached directories
- add optional environment flag to suppress vulkan errors when running cypress, see https://github.com/cypress-io/cypress/issues/29521#issuecomment-2581881432 for more context
=> PP-13452 support esbuild projects

.github/workflows/_run-node-unit-tests-and-publish-pacts.yml
- cache 'dist' in all node workflows
=> PP-13452 cache dist for all node worklfows

.github/workflows/_run-app-as-provider-contract-tests.yml, .github/workflows/_run-java-tests-and-publish-pacts.yml, .github/workflows/_run-node-cypress-tests.yml, .github/workflows/_run-node-install-and-compile.yml, .github/workflows/_run-node-unit-tests-and-publish-pacts.yml, .github/workflows/_run-provider-pact-tests-for-consumer.yml
=> BAU update cache action version for shared workflows

ci/pkl-pipelines/pay-dev/deploy-logging-pipeline.pkl, ci/scripts/test-logging-pipeline/index.js, ci/tasks/run-logging-pipeline-e2e-test.yml
- Added e2e test job to logging pipeline
A working build https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-logging-pipeline/jobs/e2e-test-logging-pipeline-in-dev/builds/1
=> PP-13784 Add e2e test job to logging pipeline

ci/pkl-pipelines/pay-dev/deploy-to-test.pkl
=> PP-13989: Add ZAP tests to selfservice end to end tests

ci/scripts/test-logging-pipeline/index.js
- Queries CloudWatch alarms by environment or account
=> PP-14016 Logging pipeline e2e test - Query alarms by account or environment

ci/pkl-pipelines/pay-dev/deploy-logging-pipeline.pkl
- Passes the missing ENVIRONMENT env variable to the e2e test
=> PP-14017 Fix logging pipeline

ci/pkl-pipelines/pay-dev/deploy-logging-pipeline.pkl, ci/tasks/promote-logging-lambdas.yml
- Added job to promote (copy lambdas to prod path) logging lambdas to deploy to prod
=> PP-14018 Promote logging lambdas to prod

ci/pkl-pipelines/common/shared_pipelines/deploy-logging-pipeline.pkl, ci/pkl-pipelines/pay-deploy/deploy-logging-pipeline.pkl
- Added logging pipeline to deploy to the `deploy` environment
- Uses `prod/` S33 subfolder to trigger deployments
=> PP-13789 Logging pipeline to deploy into deploy env

ci/pkl-pipelines/common/shared_pipelines/deploy-logging-pipeline.pkl
- Fixes for deploy-logging-pipeline
=> PP-13789 Fix deploy-logging-pipeline

ci/pkl-pipelines/pay-deploy/deploy-logging-pipeline.pkl
- Added jobs to deploy-logging-pipeline to deploy into staging
=> PP-13786 Logging pipeline - Add deploy to staging jobs

ci/pkl-pipelines/pay-deploy/deploy-logging-pipeline.pkl
Deploy the new logging pipeline to production.
Very similar to the PR to add it to staging: https://github.com/alphagov/pay-ci/pull/1397/files
=> PP-13787 Add Prod Logging Pipeline Deployment

ci/pkl-pipelines/common/shared_pipelines/deploy-logging-pipeline.pkl, ci/pkl-pipelines/pay-deploy/upload-lambdas.pkl, ci/tasks/deploy-logging-pipeline.yml, ci/tasks/promote-logging-lambdas.yml
Add lambda upload to `upload-lambdas` pipeline, and deployment (which requires https://github.com/alphagov/pay-infra/pull/5214) via logging pipelines
=> PP-14177: Add deployment of cloudtrail canary

ci/pkl-pipelines/pay-dev/pr-ci.pkl
=> PP-14193 Add products e2e tests to Selfservice PR CI pipeline

ci/pkl-pipelines/common/shared_resources_for_deploy_pipelines.pkl, ci/pkl-pipelines/pay-dev/deploy-to-test.pkl
- Removed nginx-forward-proxy job as it is no longer deployed with frontend
=> PP-14029 Remove nginx-forward-proxy job

.github/workflows/pact-broker-post-merge.yml
- Added post-merge workflow for pact docker images
=> PP-12801 Post merge workflow for pact broker

.github/workflows/_validate_docker_image_is_manifest.yml, .github/workflows/check-pact-broker-base-image-is-manifest.yml
=> Revert "PP-12801 Update Validate docker image is manifest action for pactbroker"
