docker-compose.yml
Links are now deprecated. Updated to use a network alias.
=> Use Docker compose network and ssm host alias

Makefile, docker-compose.yml
Now that we've got SSM running locally, we can push secrets into it from
the secrets store for use in the pipelines.
=> Provision cloud foundry secrets in `make setup`

Makefile, ci/pipelines/selenium-hub.yml, ci/pipelines/smoke-tests.yml, ci/tasks/run-smoke-test.yml, paas/selenium-apps.yml
Adds:
* `selenium-hub` pipeline - Deploys a persistent Selenium hub / chrome application to PaaS `tools` space 
* `smoke-tests` pipeline - Runs card smoke tests on Concourse using existing pay-endtoend docker container using selenium hub running on PaaS
=> Add selenium and card smoke-test pipelines

ci/pipelines/deploy-env.yml, ci/tasks/create-app.yml
The `provision-space` job is now responsible for creating placeholder
apps and network policies. The app jobs just pick up changes to the
Docker images and push them to PaaS without triggering any infra
changes.
We have to push an alpine image because you can't switch between
buildpack apps (the default) and Docker image apps without deleting the
app first.
=> Deploy apps independently of infrastructure

ci/pipelines/deploy-env.yml, ci/pipelines/provision-envs.yml, paas/env_variables/dev.yml, paas/env_variables/staging.yml, paas/pay-apps.yml
Create a template application structure to merge and override as
necessary.
Does this make things clearer with less duplication or just more complicated? The rationale is that there is a lot of commonality between the apps that we needn't repeat.
I cleared my space
`cf apps | awk 'NR > 4 {print $1}' | xargs -I {} cf delete -f {}`
Then deployed all the apps from the manifest, all started and seems ok
```
name                    requested state   instances   memory   disk   urls
adminusers              started           1/1         1.5G     1G     pay-adminusers-dev-dan.london.cloudapps.digital, adminusers-dev-dan.apps.internal
cardid                  started           1/1         1.5G     1G     pay-cardid-dev-dan.london.cloudapps.digital, cardid-dev-dan.apps.internal
card-connector …
```
=> Reduce duplication in pay-apps.yaml

ci/pipelines/deploy-env.yml
We need the tools to be deployed before the apps so that they can
connect to them and carry out functions such as DB migrations.
=> Deploy tools before other apps

ci/pipelines/deploy-env.yml, ci/tasks/apply-network-policies.yml, paas/apply_network_policies.rb, paas/network-policies.yml
We were running into issues with too many containers on our Concourse
workers. We probably don't need to have a separate `put` for each and
every network policy. Instead, we can use `paas/network-policies.yml` as
the canonical source for network policies and apply them all in one go.
Something to think about is that this won't remove already existing
policies but that could be added later. Also I'm not using Andy's cf-cli
plugin because it needs Go to install.
=> Single task to apply network policies

ci/pipelines/smoke-tests.yml, ci/tasks/run-notifications-smoke-test.yml
Adds smoke tests used to check availability of card and dd notifications endpoints.
Works by running remote curl command from app hosted on PaaS.
Based on existing script: https://github.com/alphagov/pay-chef/blob/master/cookbooks/pay-ci/templates/default/jenkins_jobs/scheduled-notifications-smoke-run.groovy.erb
=> Notification endpoint smoke tests

ci/pipelines/smoke-tests.yml, ci/tasks/run-notifications-smoke-test.yml
DD notifications smoke tests still run via the e2e java app (see: https://github.com/alphagov/pay-endtoend/blob/master/bin/smoke-directdebit-notifications)
This PR executes these via the remote endtoend app.
Card notifications smoke tests just use a Curl request to test the endpoint, see: https://github.com/alphagov/pay-chef/blob/master/cookbooks/pay-ci/templates/default/jenkins_jobs/scheduled-notifications-smoke-run.groovy.erb
=> Fix dd notifications smoke test

ci/pipelines/deploy-env.yml, paas/network-policies.yml, paas/pay-apps.yml
Adds the notifications/naxsi service in front of connector & dd-connector.
The notifications container required some modifications to run on PaaS. 
Specifically:
* Disable default nginx ipv6 listener as this isn't supported and causes the container to crash
* Bind nginx DNS resolver to PaaS DNS host. This is now configurable.
* Removed self-signed SSL cert config. This isn't needed as envoy should handle this implicitly.
* Configure Tini (init script) to run as a subreaper since CF already has an init system.
Notifications container changes are on the following branch: https://github.com/alphagov/pay-notifications/tree/paas_configuration
Paired with @nimalank7
=> PP-5876: add notifications service to paas skeleton

ci/tasks/run-notifications-smoke-test.yml
When executed remotely, unescaped double quotes cause payload to become malformed.
=> PP-5836: Escape double quotes in card notification smoke test

paas/smoke-test-apps.yml
The notification service is now running. Point dd notification smoke tests at it.
=> PP-5836: Update dd notification smoke url to use notification service

ci/pipelines/smoke-tests.yml, paas/env_variables/staging-smoke-tests.yml, paas/smoke-test-apps.yml
Moves smoke test environment variable value definitions to a separate file. This will make it easier to reuse the endtoend app definition for other environments.
=> Move smoke test env var definitions to separate file

ci/pipelines/deploy-env.yml
This causes the "staging" environment to be reset with each change.
Longer term staging provisioning could be decoupled from dev envs.
=> Temporarily disable auto reprovisioning on every change

ci/pipelines/smoke-tests.yml, paas/env_variables/staging-smoke-tests.yml, paas/smoke-test-apps.yml
Updates creds for card and dd sandbox users.
Runs p1 sandbox tests only.
=> PP-5836: Fix smoke tests

ci/pipelines/pay-tech-docs.yml
It looks like this worked at https://cd.gds-reliability.engineering/teams/pay-deploy/pipelines/pay-tech-docs/jobs/deploy/builds/1
=> PP-5847: Concourse pipeline for pay-tech-docs

terraform/.gitignore, terraform/environment/cloudfront.tf, terraform/environment/main.tf, terraform/environment/route53.tf, terraform/environment/variables.tf, terraform/site.tf
I've created two TF modules:
- `dns` manages Route53 for the root domain name.
- `environment` holds configuration for a Pay environment (for example,
staging).
Inside `environment` we setup a Cloudfront distribution to forward
traffic to the PaaS and some Route53 records to setup the environment's
subdomain and an ALIAS record to the Cloudfront distribution.
Cloudfront can only use ACM certificates that were provisioned in
us-east-1, so we need to provide an additional aliased `aws` provider to
the `environment` module that can be used for provisioning that cert.
=> PP-5894: Terraform for Cloudfront

terraform/environment/cloudfront.tf
Ensures authenticated GET requests reach PaaS, particularly publicapi.
We could potentially create another behaviour rule for this to apply to only `/v1/*` routes, but this will work.
=> PP-5894: Forward Authorization headers to PaaS from CloudFront

ci/config/space-users/staging.csv, ci/pipelines/deploy.yml
This change adds a new `deploy.yml` pipeline. This is used to deploy built artefacts for each application to the Staging PaaS environment. This also decouples the staging environment CF space definition from the dev environment spaces.
At a later point this pipeline may be updated to further promote built artefacts to a production environment following successful deployment validation (smoke tests etc).
Currently, application deploys are triggered by changes to an application Docker image tagged with `latest-master`. This may later be changed to respond to git tags promoting a build from a successful CI test stage.
=> PP-5907: Create separate staging deploy pipeline

ci/config/space-users/staging.csv
Required to reprovision the staging space until it's split into another pipeline.
=> Replace staging space config

ci/pipelines/deploy.yml, ci/pipelines/smoke-tests.yml
Currently its `smoke-test-user` which no longer exists and all the
deploy jobs are failing.
=> Update git source branch to develop

terraform/modules/environment/cloudfront.tf
Specifies a dependency on the SSL certificate validation before the CloudFront distribution is created. Without this Terraform fails to create the distribution because the certificate is not
yet validated.
=> Ensure CloudFront distribution is created after ACM cert validation

Makefile
provision-envs.yml disappeared in b92e7dca
dev-pipelines knows how to get the other pipelines.
=> Fix local concourse pipelines

ci/pipelines/deploy.yml, ci/tasks/download-deployment-artifact.yml, paas/env_variables/staging.yml
Add a github-release resource to watch for releases with appropriate
tag. Once triggered the `download_deployment_artifact.yml` task will get the
zipped archive and extract it so that the `cf` resource can push it
using the included manifest.
This commit will require a new credential on concourse for the github
api token, referred to within the deploy job as `git-access-token`.
**What**
I've tested something very similar on a local pipeline pushing to my dev space so should work. Just doing it for Frontend to begin with.
~This is dependent upon Richard's work and adding the new github access token cred to concourse, hence the `do-not-merge`.
https://github.com/alphagov/pay-omnibus/pull/45#pullrequestreview-347990689~ Richard's pr is merged.
=> PP-6030 Switch card-frontend to deploy from buildpack

ci/pipelines/deploy.yml
cf-cli resources is the type not the name, which is `paas-staging`.
Remove old card-frontend docker image resource as a trigger for smoke
tests.
=> PP-6030 Correct config errors

paas/env_variables/staging.yml
In the new individual manifests we are no longer using the format
`http://((app_route)):8080` so the urls in the config need to be
updated. I've tried manually changing the env vars for card-frontend to
those included in here and the smoke tests pass.
We may have some inconsistency as we move to individual manifests and
buildpacks whether the manfiest expects the protocol prefix or not, if
things break we can fix it up.
=> PP-6030 Correct env vars for staging

ci/pipelines/deploy.yml
It was thought this wasn't needed with the cf-cli, we were wrong.
=> PP-6030 Add manifest param back

ci/tasks/extract-artefact.yml, paas/env_variables/staging.yml
Update staging.yml with missing vars for node apps. This is a temp fix
to get to a point where the apps will run.
Update the extract-artefact task since direct-debit-frontend.tar.gz
isn't caught by the current pattern.
=> PP-6030_update_staging_vars

ci/pipelines/build.yml, ci/tasks/maven-build.yaml
Adds Maven build jobs for Java apps triggered by Travis. `.jar` artefacts produced in the `/target/`directory are added to Github release.
=> PP-6038: Add Java build jobs to build pipeline

ci/pipelines/deploy.yml
This function no longer exists in provision_pipeline.sh and db/service
binding will be accomplished via each app's manifest.
=> PP-6030 Remove bind_db from deploy pipeline

docs/source/adrs/0004-separate-cde-space.html.md, docs/source/adrs/index.html.md.erb, docs/source/infrastructure.html.md.erb, docs/source/onboarding.html.md.erb
I've created a new section of the omnibus docs to contain architectural
decision records. The ADR for using a separate CDE space has been added
to this.
=> PP-6063: Add ADR for separate CDE space

paas/env_variables/staging.yml
Required to be able to push the apps since their manifests expect them.
=> PP-6030 Add staging env vars

ci/pipelines/deploy.yml
Shows deployments with related smoke tests in a single view.
=> Show staging deploys with related smoke tests

ci/pipelines/dev-env.yml
Get create test user working temporarily by passing in a user and
service name, as these are now expected as arguments.
=> Get create test user working

ci/tasks/maven-build.yml
When creating the tar for the release, copy files ending in both yml and
yaml since the manifest follows our convention of yml but the config
files use yaml; we don't want to change the config file extensions in
case it has unexpected consequences.
=> PP-6031 Copy yaml and yml to the archive

terraform/modules/paas/app-catalog-service.tf
It isn't possible to bind services to apps in another space so this
creates a version of the app-catalog for the staging-cde space. This
also adds `selfservice_transactions_url` which is needed by products-ui.
We deployed this on Friday running tf on my machine but didn't actually get round to committing it.
=> PP-6085 Add staging-cde creds

terraform/dev-paas/site.tf, terraform/staging-paas/site.tf
Bumps the required Cloudfoundry provider version to v0.11.0 to support sso authentication.
See release notes: https://github.com/cloudfoundry-community/terraform-provider-cf/releases/tag/v0.11.0
**Note:** This will require the locally installed plugin to be updated
`curl -o ~/.terraform/plugins/terraform-provider-cloudfoundry_v0.11.0 https://github.com/cloudfoundry-community/terraform-provider-cf/releases/download/v0.11.0/terraform-provider-cloudfoundry_darwin_amd64`
=> Update Terraform Cloudfoundry provider to v0.11.0

ci/tasks/checkout-commit.yml
Git describe only returns a single tag which isn't always the one we need. Instead, list all tags and filter by paas_release prefix then sort to return the latest paas release tag.
=> Fix release tag calculation

terraform/modules/paas-stub-sqs/sqs.tf, terraform/modules/paas/adminusers.tf, terraform/modules/paas/card-connector.tf, terraform/modules/paas/card-frontend.tf, terraform/modules/paas/cardid.tf, terraform/modules/paas/directdebit-connector.tf, terraform/modules/paas/directdebit-frontend.tf, terraform/modules/paas/ledger.tf, terraform/modules/paas/notifications.tf, terraform/modules/paas/products-ui.tf, terraform/modules/paas/products.tf, terraform/modules/paas/publicapi.tf, terraform/modules/paas/publicauth.tf, terraform/modules/paas/selfservice.tf, terraform/modules/paas/toolbox.tf
This is needed if we want connector to be able to talk to SQS in a nice way.
When applying the terraform we also noticed a weird edge case where terraform
wanted to turn all the health_check_type's back to "port" from "http" - we
think that might be a bug in the provider, but we're working around it for now
by telling terraform to ignore_changes.
=> PP-6085: Add SQS user proviced service inside the CDE space

terraform/modules/paas/app-catalog-service.tf
These should ideally be configured within the applications, leaving the app-catalog service to simply provide app urls for service discovery.
=> PP-6085: Add arbitrary product_ui routes to app-catalog service

terraform/staging-paas/site.tf
Adds remote state configuration for Paas Cloudfoundry resources. This uses the same S3 bucket as the AWS infra.
To run the terraform, you'll need to set CF_USER & CF_PASSWORD as per the plugin guide: https://github.com/cloudfoundry-community/terraform-provider-cf/wiki/provider_config
In addition, you'll also need to run terraform with AWS creds, i.e. via aws-vault
e.g. `CF_USER=username; CF_PASSWORD=password; aws-vault exec <account> -- terraform apply`
=> Add terraform remote state config for staging-paas

paas/env_variables/staging.yml
Each app should be binding to `app-catalog` service to get the urls for
other apps. There are no longer needed in the staging.yml
=> PP-6085 Remove app url from staging.yml

terraform/modules/aws/products-ui.tf
This updates the DNS record and reconfigures the cloudfront
distribution to match the "products.staging.gdspay.uk" route
bound to the products-ui app in PaaS instead of using `products-ui`.
=> PP-6085: Update external products-ui subdomain to "products."

ci/pipelines/deploy.yml
Trigger staging smoke tests every 10 mins
Temporarily ignore cardid deploys until we can successfully build via Travis.
=> PP-6085: Fix smoke tests

terraform/modules/aws/card-frontend.tf
Disassociate FLE profile from frontend CDN until app development (FLE field decryption) is complete.
=> Temporarily disable frontend field level encryption

terraform/modules/paas/products-ui.tf
Products UI needs to connect to adminusers. This adds the missing network policy to the PaaS related Terraform.
=> Add missing network policy products-ui -> adminusers

ci/tasks/smoke-test-user.yml, client/client
Adding a price to an adhoc product makes it a non-adhoc product.
Product smoke tests require an adhoc product in order to target the "price" field and enter an arbitrary product price.
=> PP-6085: Remove price from smoketest adhoc product

ci/pipelines/deploy.yml
Adds necessary tasks to deploy toolbox from a Github release to PaaS staging environment.
=> Add toolbox to staging deploy pipeline

terraform/modules/paas/main.tf, terraform/modules/paas/toolbox.tf
Adds a PaaS-provided route to get access the toolbox app in the Staging environment. This will be accessible via the cloudapps.digital domain for now and provides https by default.
Todo:
=> Add external route to toolbox app

terraform/modules/credentials/main.tf, terraform/modules/credentials/outputs.tf, terraform/modules/credentials/variables.tf, terraform/modules/paas/publicapi.tf, terraform/modules/paas/variables.tf, terraform/staging-paas/site.tf, terraform/staging-paas/terraform.tfvars, terraform/staging-paas/variables.tf
Implement version 1 of provisioning secrets in paas. It is likely that
this will be replaced when PaaS provide a more robust means for secrets
management.
This adds a credentials module which will gather secrets from
pay-low-pass. The credentials are set on a user provided service which
will be bound to the app.
To get it started this commit deals with publicapi but the same approach
and be used for the other apps.
with @rjbaker
We intend to iterate and improve upon this but this is a start. Comments and feedback welcomed to help us improve this as we roll it out for the other apps.
=> PP-6127 Add secret service for publicapi

terraform/modules/paas/card-connector.tf, terraform/modules/paas/publicapi.tf, terraform/modules/paas/variables.tf, terraform/staging-paas/site.tf, terraform/staging-paas/terraform.tfvars, terraform/staging-paas/variables.tf
Make the credentials variable a map of apps and their credentials
(previously it was only for publicapi). This allows us to add apps
without having to modify how we pass the values into the paas module.
Second commit adds the creds for connector.
I've tested this in staging by running the terraform and binding card-connector, it then has the necessary vars within VCAP-Services.
=> PP-6127 Restructure credentials variable and add connector

terraform/staging-paas/terraform.tfvars
The card-connector needs at least a default value to start.
=> PP-6127 Set default value for some aws creds

terraform/staging-paas/terraform.tfvars
A few were missing and one or two were not as per `secrets.yml` in
`pay-infra`.
=> PP-6127 Update card-connector secret service creds

terraform/staging-paas/terraform.tfvars
Add selfservice secrets for staging.
Gocardless url and client id are same for test and live, as in current
staging.
=> PP-6127 Selfservice secrets

ci/pipelines/deploy.yml, ci/scripts/migrate-database.sh, ci/scripts/migrate_database.sh
Adds database migration pipelines triggered by deployment jobs.
- Executes a bash script inside the cf-task container, targeting the relevant space and app.
- Runs the Java migration task via `cf run task ...`
- Retrieves logs for the task whilst running via `cf logs ...`
- Parses log lines related to the running task
- Parses JSON log lines into plain text
- Parses the task exit code to determine the job result
Todo:
=> PP-6132: Database migration pipeline

ci/pipelines/deploy.yml
Prevent smoke test logs filling Concourse's disk. These will be updated to emit success/failure metrics for long term number crunching.
=> Limit smoke test build logs to 1000

terraform/staging-paas/terraform.tfvars
We cannot reuse the existing staging creds as github redirects to the
associated redirect url for those credentials. This uses new creds added
to pay-low-pass for our paas staging space.
Linked to PR https://github.com/alphagov/pay-low-pass/pull/152
=> Add new OAuth creds for toolbox in paas staging

ci/pipelines/build.yml, terraform/modules/aws/card-frontend.tf, terraform/modules/aws/provision_fle_config.rb, terraform/modules/credentials/main.tf, terraform/staging-paas/terraform.tfvars
- Enables FLE on the card-frontend Cloudfront distribution.
- Adds necessary FLE keys to secrets and application configuration
- Enable request forwarding when a non form-encoded data (json) is used
See card-frontend changes in: alphagov/pay-frontend#1388
=> PP-6147: Decrypt field level encryption fields

terraform/modules/paas/notifications.tf
This was being created as a buildpack-based app, which causes initial deployment of the Docker container to fail because app types can not be changed once pushed.
Since the notifications app container is specified using an app manifest applied via Concourse, the initial Terraform run will create an empty docker app and ignore the image in subsequent runs.
=> PP-6146: Ensure Notifications app is pushed as a Docker app

client/client
In scenarios where a smoke test user already exists, attach the user to the new service and return existing credentials.
=> PP-6146: Check for existing smoke-test user before creating

ci/tasks/node-build.yml
Explicitly remove all dev dependencies in node_modules before reinstalling production dependencies only. Previously this incorrectly assumed `--only=prod` pruned dev dependencies.
=> Remove node_modules directory before installing prod dependencies

ci/tasks/node-build.yml
Caches ~/.npm global directory reducing the number of packages that are re-downloaded between dev and prod dependency installs. Props to @danworth 👍
=> Fix node_module cache behaviour when removing dev dependencies

client/client
Not all apps might be up, e.g. directdebit-connector so if they are
not available after retrying when attempting to forward ports, just
log and continue. The script handles apps not being up later on.
=> Don't abort create user if app isn't up

paas/carbon-relay/apt.yml, paas/carbon-relay/carbon-relay-ng.ini.erb, paas/carbon-relay/manifest.yml, paas/carbon-relay/start.sh, paas/carbon-relay/stunnel.conf.erb
Use the apt buildpack to create a Ubuntu Bionic container with
carbon-relay-ng and stunnel. use erb for variables substitution. This
give us greater ability to configure both processes over the previous
docker container approach.
Note that Dropwizard apps emit their metrics on UDP so when adding cf
network-policies be sure to specify `--protocol udp`.
=> PP-6245 Carbon-relay and stunnel in apt buildback

paas/carbon-relay/manifest.yml, paas/carbon-relay/start_carbon_relay.sh, paas/carbon-relay/start_stunnel.sh
This allows us to change instances, memory and cpu indendently to. CF  should
alert us and take steps to restart both carbon-relay and its sidecar stunnnel
should one or the other fail.
=> PP-6254 Run stunnel as a 'side-car'

paas/carbon-relay/carbon-relay-ng.ini.erb, paas/carbon-relay/env-map.yml, paas/carbon-relay/manifest.yml, paas/carbon-relay/stunnel.conf.erb, terraform/modules/paas/app-catalog-service.tf, terraform/modules/paas/carbon-relay.tf, terraform/staging-paas/terraform.tfvars
**Commit No. 1**
Add `carbon-relay` module to create empty app with route and
corresponding secret service. Use the env-map buildpack to extract
hosted graphite vars from VCAP_SERVICES.
Tested by running tf in staging. `carbon-relay` starts along with its side car stunnel process and envs are correctly set.
**Commit No. 2**
Added carbon-relay route and port to app-catalog, confirmed its present:
```
gds5062 > cf curl /v2/service_instances/8bd15004-0ad9-41d0-a19e-2a684973d7f8 | grep carbon_relay
"carbon_relay_port": "2003",
"carbon_relay_route": "carbon-relay-stg.apps.internal",
```
**Commit No. 3** 
Add network policies to carbon-relay. Might be a better way to iterate over each instance of `cloudfoundry_app` resource without having to create the set although I cannot find it in docs, …
=> PP-6254 Add carbon-relay app to tf

ci/pipelines/deploy.yml
We might want to move carbon-relay to its own repo to avoid it being
redeployed each time pay-omnibus is updated which may well not be
changing carbon-relay set-up.
=> PP-6254 Add deploy carbon-relay job

paas/carbon-relay/start_carbon_relay.sh, paas/carbon-relay/start_stunnel.sh
Replaces the bash startup script process id with the application. This ensures the application is able to correctly receive process signals from the OS.
=> PP-6254: Start carbon-relay apps using exec

ci/pipelines/deploy.yml
Defines a separate resource for the carbon-relay app source by
using the "path" attribute of the git resource. This ensures
the deploy job is triggered only when a change is made to files
within the specified directory, rather than every commit to the
repo.
=> BAU: Trigger carbon-relay deploy only when app config changes

terraform/modules/paas/splunk-log-drain.tf
Creates two service instances (CDE & non-CDE) for shipping application logs to Splunk via Techops /Cyber Splunk service broker. 
https://github.com/alphagov/tech-ops/tree/master/cyber-security/components/csls-splunk-broker
=> Create Splunk log service instance in cde & non cde spaces

ci/scripts/migrate_database.sh
Minor fixes relating to:
- Wrapping variable references in `""` to handle whitespace
- Removing `cat <filename> | ` in favour of passing the file name as an arg to
`sed` and `awk`.
@sfount reminded me about [shellchecker](https://github.com/koalaman/shellcheck#user-content-installing) so I ran it and this fixes its report.
Any bash enthusiast
=> Ran shellcheck on the migration script

ci/pipelines/deploy.yml, ci/tasks/cf-v3-deploy.yml
Apps are now created using the CF v3 API. 
This PR updates Concourse pipelines and tasks to use V7 CF CLI  as this supports the vars-file option and ZDT functionality which was missing from v6 v3-push command.
=> Use CF CLI v7 with optional arguments

terraform/modules/paas/splunk-log-drain.tf
The GUIDs generated on initial creation of the services are used to configure our static Splunk index names. Destruction and recreation of the service instance would generate a new GUID and cause logs to be sent to the incorrect index.
Discussed with @chrisfarms
=> Prevent destruction of Splunk logdrain service instances

README.md, terraform/Makefile, terraform/modules/credentials/main.tf
**What is it?**
Adds a makefile to automate installation steps for Terraform Cloudfoundry & Pass provider plugins.
**How to test**
- Checkout this PR branch.
- `cd terraform`
- run `make`
- `cd terraform/paas-staging`
- `aws-vault exec <env> -- terrafrom init` 
- test the provider configuration `aws-vault exec <env> -- terraform providers`
=> PP-6366: Add makefile to automate installation of TF plugins

ci/pipelines/pr.yml, ci/tasks/java-tests.yml
**What is it?**
Adds a new pipeline for testing pull requests on all application repositories.
Uses the [pull request Concourse resource](https://github.com/telia-oss/github-pr-resource) to run unit and integration tests on Github PRs.
Java builds use a docker-in-docker container environment to allow Java Test Containers to pull and start Postgres and other Docker test dependencies within the test environment.
Within the pr.yml, the first PR build job definition specifies global `max_in_flight` (3 per repo) and `build_log_retention` (500 builds) parameters. These are inherited by all jobs but can be changed or overridden by subsequent job definitions as required.
=> PP-6371: Create PR pipeline

ci/docker/concourse-runner/Dockerfile, ci/docker/concourse-runner/README.md, ci/docker/concourse-runner/docker-helpers.sh, ci/docker/concourse-runner/docker-wrapper, ci/pipelines/concourse-runner.yml, ci/pipelines/pr.yml
Adds a Docker image used as an environment to run jobs requiring Docker-in-Docker with extra dependencies preinstalled, such as maven and openjdk11.
Adds readme.md with usage instructions.
Adds concourse pipeline to build and push image to https://hub.docker.com/repository/docker/govukpay/concourse-runner
=> Add concourse-runner image to run Pay builds

terraform/modules/aws/publicapi.tf, terraform/modules/aws/waf_v2_acl/configure_aws_wafv2.rb, terraform/modules/aws/waf_v2_acl/main.tf, terraform/modules/aws/waf_v2_acl/outputs.tf, terraform/modules/aws/waf_v2_acl/rules.tpl, terraform/modules/aws/waf_v2_acl/variables.tf
Adds a ruby script to create a basic WAF ACL using the WAFv2 API.
The ACL uses a JSON template to configure AWS managed rulesets (a new feature in WAFv2).
Composed into a Terrafrom module so it can be applied to other CloudFront distributions.
- Run `terraform apply` in the aws staging environment
- Check ACL and resource association in AWS console. Be sure to select *global* region to see ACLs applied to CloudFront distributions.
- Matching rules are currently set to *count* not *block*, so we can measure stats.
- The resource does not currently support updating WAF rule template in place.
The Terraform resource to support WAFv2 is due to be merged into the AWS provider.
See: https://github.com/terraform-providers/terraform-provider-aws/pull/12688
Co-authored-by: @rorymalcolm
=> PP-6109: Add Publicapi WAF ACL config

terraform/modules/aws/waf_v2_acl/configure_aws_wafv2.rb, terraform/modules/aws/waf_v2_acl/fetch_aws_wafv2.rb, terraform/modules/aws/waf_v2_acl/main.tf, terraform/modules/aws/waf_v2_acl/rules.tpl
Adds a Terraform `null_resource` with script to provision a WAF v2 ACL. This allows updates to the resource to be triggered by changes to the ACL rule configuration.
When a change occurs this will trigger the null_resource to be recreated. However, the script that is executed ensures that any existing WAF is updated instead of being destroyed and recreated.
=> Refactor WAF provisioning script

terraform/modules/aws/card-frontend.tf, terraform/modules/aws/directdebit-frontend.tf, terraform/modules/aws/notifications.tf, terraform/modules/aws/products-ui.tf, terraform/modules/aws/selfservice.tf
ACLs are created for the respective distributions but must be applied to CloudFront using the id/arn value from the WAFv2 module.
TF has now been applied.
=> PP-6447: Attach WAF ACLs to public Cloudfront distributions

terraform/modules/aws/publicapi.tf, terraform/modules/aws/waf_v2_acl/main.tf, terraform/modules/aws/waf_v2_acl/variables.tf
Allows optional override of ACL rules for CloudFront distributions. This allows individual endpoints to adjust ACL rules as required.
Co-authored-by: @rorymalcolm
=> PP-6447: Support overriding of WAF ACL configuration

terraform/modules/aws/publicapi.tf, terraform/modules/aws/waf_v2_acl/configure_aws_wafv2.rb, terraform/modules/aws/waf_v2_acl/main.tf, terraform/modules/aws/waf_v2_acl/variables.tf
Allows an optional log_destination and field redaction config
to be passed to a WAF ACL "resource". This allows WAF logs to be
pushed to a kinesis stream.
Public API WAF is configured to redact the Authorization header
so tokens do not appear in any WAF logs.
Co-authored-by: Rory Malcolm <rory.malcolm@digital.cabinet-office.gov.uk>
=> PP-6447: Add logging config to WAFv2 terraform

terraform/modules/aws/hosted-graphite.tf
Adds an IAM user with limited CloudWatch read-only permissions.
Credentials are provided to Hosted Graphite and used to query
metric data from an AWS account.
Co-authored-by: @rorymalcolm
=> PP-6488: Add hosted graphite IAM user to AWS account

lambda/waf-to-splunk-kinesis-data-transformation/.gitingore, lambda/waf-to-splunk-kinesis-data-transformation/index.js, terraform/modules/aws/logs.tf, terraform/modules/aws/variables.tf, terraform/modules/aws/waf_logging/kinesis-firehose.tf, terraform/modules/aws/waf_logging/lambda.tf, terraform/modules/aws/waf_logging/s3.tf, terraform/modules/aws/waf_logging/variables.tf, terraform/staging-aws/site.tf
Deploys a Kinesis Firehose Delivery Stream used to process and deliver logs from WAF ACLs to Splunk.
- Uses a lambda function to process logs to required Splunk HEC format
- Drops "Allow" logs, so only Block and Count actions are delivered.
- Failed logs are delivered to an S3 bucket
- Adds log groups and streams for debugging Lambda function and Firehose Delivery
- Requires Splunk HEC Endpoint and Token as input variables
=> PP-6448: WAF Log Kinesis Firehose Delivery Stream

terraform/modules/aws/logs.tf, terraform/modules/aws/main.tf, terraform/modules/aws/variables.tf, terraform/staging-aws/site.tf
Refactors AWS Terraform to source Splunk HEC token used by WAF log Kinesis delivery pipeline from pay-low-pass rather than an input variable.
=> BAU: Source Splunk HEC token from pay-low-pass secret store

terraform/modules/aws/logs.tf, terraform/modules/aws/waf_logging/s3.tf, terraform/staging-account/site.tf
Buckets already had private ACLs applied. An explicit public access
block ensures any ACL or IAM policies created later on can not accidentally 
make objects public.
This is a relatively new feature to prevent misconfiguration of
bucket and object policies.
See: https://docs.aws.amazon.com/AmazonS3/latest/dev/access-control-block-public-access.html
Terraform has been applied.
=> BAU: Apply explicit public access block to s3 buckets

terraform/modules/paas/adminusers.tf, terraform/modules/paas/carbon-relay.tf, terraform/modules/paas/card-connector.tf, terraform/modules/paas/card-frontend.tf, terraform/modules/paas/cardid.tf, terraform/modules/paas/directdebit-connector.tf, terraform/modules/paas/directdebit-frontend.tf, terraform/modules/paas/ledger.tf, terraform/modules/paas/metric-exporter.tf, terraform/modules/paas/notifications.tf, terraform/modules/paas/products-ui.tf, terraform/modules/paas/products.tf, terraform/modules/paas/publicapi.tf, terraform/modules/paas/publicauth.tf, terraform/modules/paas/selfservice.tf, terraform/modules/paas/splunk-log-drain.tf, terraform/modules/paas/toolbox.tf
Binds all applications & ancillary apps (carbon relay / metric exporter) to Splunk log service.
This is a managed service run by Cyber. Logs are currently pushed to `pay_testing` index. This can be changed by Cyber.
=> PP-6446 Bind Apps to Splunk Log Service

terraform/modules/aws/sqs.tf
Uses the default master KMS key managed by AWS. Messages are
encrypted and decrypted by applications using temporary keys
requested from KMS.
This occurs transparently when using AWS SDK SQS client.
More information: https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-server-side-encryption.html
=> PP-6234: Enable SSE on all SQS queues

terraform/modules/aws/variables.tf
Public static egress IPs for PaaS Ireland.
These may be used to create AWS resource IP restrictions etc.
=> PP-6234: Add PaaS Ireland public IPs to TF variables

ci/pipelines/pr.yml, ci/tasks/java-integration-tests.yml, ci/tasks/node-build-pr.yml, ci/tasks/pact-provider-check.yml, ci/tasks/pact-provider-verification.yml, ci/tasks/publish-pacts.yml
Adds consumer PR pact tests for all consumers.
The general structure is:
- publish pacts in a separate task after the consumer pact tests are run,
and tag pact with PR number
- in a separate job, first check whether any provider tests need to be
run by calling pact-cli `can-i-deploy` - this avoids unnecessarily
running provider verifications
- pass list of providers needing verification to provider verification tasks
which runs all required provider verifications in parallel
- report back to PR on status of provider verification
This structure is more efficient and parallelised than current implementation,
and is fairly self explanatory when viewed in concourse.
=> PP-6504 Consumer PR pact tests

terraform/modules/paas/sqs-config-service.tf, terraform/modules/paas/variables.tf, terraform/staging-paas/site.tf
- Adds an SQS config user-provided service to provide queue URLs to apps.
- Queue URLs are built from AWS region, account id, and environment variables.
- Apps are still bound to SQS config service via app manifest in their respective repositories.
- Connector will need updating to add payout reconcile config via `env-map.yml`
=> PP-6234: Remove stub SQS service and add real queue config

ci/scripts/migrate_database.sh
The correct java command options for the current buildpack runtime can be found in `/home/vcap/staging_info.yml`. 
`server` is replaced with the migration command(s), for the given app.
jq is also available in the runtime to allow this to be parsed for use with CF tasks. This should keep tasks stable as buildpacks are updated.
Co-authored-by: Rory Malcolm <rory.malcolm@digital.cabinet-office.gov.uk>
=> PP-6234: Fix database migration tasks running in Java buildpack

ci/tasks/node-build-pr.yml
Alex raised a pr on Toolbox and the build failed when trying to copy the non-existent pact files. This allows that step to pass if they do not exist.
Tested on pr pipeline and it passes.
https://cd.gds-reliability.engineering/teams/pay-deploy/pipelines/pr-ci/jobs/toolbox-test/builds/53
=> Toolbox doesn't have pact files so don't error if they're not there

ci/pipelines/pr.yml
Somehow the pr pipeline on master couldn't actually be set because of the  incorrect indentation fixed herein.
=> Fix yml formatting

ci/pipelines/pr.yml
Seems some of the pact verifiction jobs  were not getting omnibus and so they
could not find the task file. Also need to rename the task input
from provider to test_target to match a previous change to the job.
=> BAU Fix pact provider tasks

ci/tasks/calculate-release-number.yml
`cut` the release number before sorting since sort even with the `-n` flag
doesn't appreciate that `paas_release-10` is greater than
`paas_release-9` and we were forever stuck creating release 10.
Also ran shellcheck and fixed one error to correctly reference
`is_numeric` (there was no `$`) and double quoted variables to keep it
happy and avoid globbing/word splitting.
Example of previous calculation:
```
GDS5062:pay-frontend danworth$ git tag --list 'paas_release-*' | sort -nr
paas_release-9
paas_release-8
paas_release-7
paas_release-6
paas_release-5
paas_release-4
paas_release-3
paas_release-2
paas_release-10
paas_release-1
```
=> PP-6676 fix calculation of next release number

ci/tasks/node-build-pr.yml
**What is it?**
This change enables Cypress tests for frontend projects by detecting the `cypress.json` file in the project root. Tests now run and pass:
https://cd.gds-reliability.engineering/teams/pay-deploy/pipelines/pr-ci/jobs/selfservice-test/builds/170
To do this I have needed to change the node pr-build container to node Debian Stretch from Alpine. This is because Cypress requires libc dependencies not available on Alpine.
Cypress is installed by npm as a development dependency and this is cached by the Concourse task worker.
One drawback to this is that unit/cypress/e2e tests are each run serially.
**Future Solution**
A possible solution to parallelize this work is to create a new “cypress” test task for frontend build jobs. This can be executed in parallel with other tasks. …
=> PP-6606: Run Cypress tests on Node apps if config is present

ci/tasks/send-hg-metric.yml
- Params are passed as environment variables, not concourse globals
=> PP-6615 Fix Param Vars

ci/pipelines/pr.yml
Prevents Concourse running PR builds on external, untrusted forks.
=> BAU: Prevent builds triggered by external forks

ci/pipelines/pr.yml
The `privileged` task option is only required if running Docker-in-Docker.
Looks like it's been accidentally copied in a few places where not required.
See: https://concourse-ci.org/jobs.html#schema.step.task-step.privileged
=> BAU: Remove privileged task option where not needed

ci/pipelines/deploy.yml, ci/tasks/tag-pacts-with-master.yml
```
PP-6686 Tag consumer master pacts with master
Upon merge commit of a consumer find the previous commit that was not a
merge. This should be the head commit of the PR that was tested and
which was just merged. The pact broker will have contracts for this version
of the consumer. Use curl to tag them with "master".
This avoids generating the pacts a second time for node apps which
would require an npm install which is costly.
This was the simplest solution at the time and we may want to revist it.
```
=> PP 6687 tag consumer master merges

ci/pipelines/concourse-runner.yml, ci/pipelines/deploy.yml, ci/pipelines/dev-env.yml, ci/pipelines/dev-pipelines.yml, ci/pipelines/docs.yml, ci/pipelines/pay-tech-docs.yml, ci/pipelines/pr.yml
`github-circle` appears to have been removed from https://materialdesignicons.com.
This updates all references accordingly.
=> BAU: Update github material design icon used in pipelines

ci/pipelines/deploy.yml, ci/tasks/pact-provider-master-verification.yml, ci/tasks/pact-provider-test-preflight-check.yml
When a provider is merged into master run pact validation using the
commit one before the merge commit which will be the commit from the
head of the PR. The pact broker will know about this commit since it
will have been tested during the PR build leading up to this merge. If the
pacts with its consumers are still valid then exit. If not then rerun
the validation for the consumer. If the rerun fails then manual
intervention will be necessary as it would be today with Jenkins CI.
**HOW**
This has been set to our deploy pipeline and it looks good so far, for example 
https://cd.gds-reliability.engineering/teams/pay-deploy/pipelines/deploy/jobs/build-card-connector/builds/25
Also we ran through the plan with Oz and he was onboard. I think we can bring together some of the pact verification …
=> PP-6704 Run provider pact validation on master merge

ci/scripts/migrate_database.sh
Need to add `--command` to run-task for this to work, perhaps something has recently
changed. I've tried this on a hijacked card-connector container and it worked.
```
USAGE:
cf run-task APP_NAME [--command COMMAND] [-k DISK] [-m MEMORY]
[--name TASK_NAME] [--process PROCESS_TYPE]
```
Original error:
```
Incorrect Usage: unexpected argument "source <(jq -r ."start_command" /home/vcap/staging_info.yml | sed 's/server/db migrate/g')"
```
Tested this on a hijacked card-connector container and it worked:
```
bash-5.0# APP_NAME='card-connector' APP_PACKAGE='uk.gov.pay.connector.app.ConnectorApp' ./migrate_database.sh
Creating task for app card-connector in org govuk-pay / 
Task has been submitted successfully for execution.
```
=> BAU Fix cf run-task command to add --command

ci/scripts/migrate_database.sh
When running db migrations we use `source` to modify & execute the start command directly
from the app's container to future proof against buildpack changes and the command
changing.
The app's start command is run with `exec` which replaces the process
that called it with a new process. This makes sense when you're starting the
app and want the app process to be pid 1 in the container.
When we're running migrations we want the command we've provided to `cf run-task`
to remain as pid 1 especially for adminusers where we effectively
run `initial migration && all other migrations`. Without this change the
initial migration runs and being pid 1 the container exits once its completed
and the next migration does not happen.
I've tested this on a hijacked adminusers db migration task and both …
=> BAU Fix adminusers db migration script

ci/pipelines/pr.yml
Check for new prs and commits every 1m (this is the default frequency
for resources). The original value of 1h comes from our original
development of the pipeline before we added the auth credentials and
were much more restricted by api rate limit.
Github API rate limits for authenticated requests is
5000 per hour, we have 13 projects set-up so this will take 780 requests
per hour which leaves plenty of head room for the other calls to update statues
etc.
=> PP-6724 Use default check frequency of 1m for pr resources

ci/pipelines/pr.yml
Also corrected the pr status context for products endtoend tests which was
previously being reported as 'card'
Have tested this on pr pipeline and it was successful:
https://cd.gds-reliability.engineering/teams/pay-deploy/pipelines/pr-ci?group=End%20To%20End
N.B. Open to suggestions but I've used `endtoend` when referring to it in this new context of the project being tested since it's more descriptive and differentiates it from the existing `e2e` text used in the context of it being run as a test task.
=> PP-6726 Add endtoend project to pr pipeline

ci/pact_broker/pay-pact-broker_manifest.yml, ci/pipelines/deploy.yml, ci/pipelines/pr.yml, ci/tasks/pact-provider-master-verification.yml, ci/tasks/pact-provider-test-preflight-check.yml, ci/tasks/pact-provider-verification.yml, ci/tasks/publish-pacts.yml, ci/tasks/tag-pacts-with-master.yml
Updates deploy and pr pipelines to pass Pact broker credentials from Concourse secrets to pact tasks. Creds are passed as task "vars" which are interpolated into the task definition and mapped to broker-username & broker-password environment variables used in the task script.
=> PP-6722: Update pipelines & tasks with pact-broker credentials

ci/pipelines/deploy.yml
We no longer need to use the update pipeline resource now
Concourse has a native method to update piplines on master merge.
I have added "git" resource to track changes on master to the
deploy.yaml pipeline. This ensures the update is only triggered
when the pipline is changed, rather than any file in the omnibus
repo.
=> Update deploy pipeline using new set-pipeline job step

ci/pipelines/pr.yml
cardid-data submodule's url is defined as ssh yet concourse
is using oauth. Furthermore we need to avoid the password
prompt from the git cli. Therefore rewrite the url for https
and add the token. The risk of setting the token in the url is mitigated
since these files are not committed, the container is ephemeral
and anyone with access to read the files could read the token from
environment variable. Furthermore we redact the token from the files
after the update.
Note that we can't make use of the `git_pr_resource` `submodule`
feature because it will attempt ssh as per the config in `.gitmodules`
and fail.
Experimented a little using `expect` to manage the password input prompt when username is `x-oauth-basic` but with limited success. After some discussion with the team we felt this …
=> PP-6561 Fix cardid cloning of data submodule

ci/tasks/pact-provider-master-verification.yml, ci/tasks/pact-provider-test-preflight-check.yml, ci/tasks/pact-provider-verification.yml, ci/tasks/tag-pacts-with-master.yml
Task params are used as bash environment variables so can't have underscores.
=> PP-6722: Fix Pact broker authentication

ci/tasks/pact-provider-master-verification.yml, ci/tasks/pact-provider-verification.yml, ci/tasks/publish-pacts.yml
Pact tests run via maven require dependencies to be installed each time. The PR adds dependencies to the Concourse task cache which should save a couple of minutes from the build time.
Also fixes hyphens in env vars.
=> PP-6722: Add maven cache to Pact tasks

ci/tasks/pact-provider-master-verification.yml
Saves repetition and allows URL to be overridden by passing in from the pipeline
=> BAU: Add pact broker url to env var

ci/tasks/pact-provider-test-preflight-check.yml
There was an erroneous `)"` at the end which meant the pact broker command was incorrect and failing. Take the opportunity to follow examples in other pact test scripts and use `broker_url` env var.
The script was failing because of the erroneous `)"` at the end of the broker url but this was interpreted by the script as the call to the pact broker was returning exit status 1 and that provider validation was required. It makes no distinction between an error making the call, and the call succeeding but returning the need to run validation.
Sample run: https://cd.gds-reliability.engineering/teams/pay-deploy/pipelines/pr-ci/jobs/publicapi-pact-provider-verification/builds/31.1
```
Pact tests being run in consumer context. Creating parameters...
sh: --broker-username=pay-team: not found …
```
=> PP-6722 Fix typo in broker url

ci/tasks/pact-provider-test-preflight-check.yml
Add the closing `)"` for the `can_deploy` call.
Checked it this time on hijacked container and ran `shellcheck` which was clean.
```
/tmp/build/a42abd17 # git_sha="$(cat src/.git/resource/head_sha)"
/tmp/build/a42abd17 # can_deploy="$(pact-broker can-i-deploy \
>   --pacticipant="$consumer" --version="$git_sha" \
>   --broker_base_url="$broker_url" \
>   --broker-username="$broker_username" \
>   --broker-password="$broker_password")"
/tmp/build/a42abd17 # echo $can_deploy
Computer says yes \o/ CONSUMER | C.VERSION | PROVIDER | P.VERSION | SUCCESS? ----------|--------------------------------|------------------------|--------------------------------|--------- publicapi | 318213a9803f7f3d341d18f2a08... | connector | eff61776768db58918a78c38776... | true publicapi | …
```
=> PP-6722 Fix typo

terraform/modules/paas/ledger.tf, terraform/modules/paas/selfservice.tf
When setting the `service_instance`  for `cloudfoundry_app` it needs the GUID from
`cloudfoundry_service_instance` which is an object. This change has
already been made elsewhere, seems these were missed.
=> PP-6659 cloudfoundry_service_instance is an object

ci/tasks/pact-provider-master-verification.yml
single quotes prevent parameter expansion so change them to `"` so it will work as intended. Tested on hijacked container
```
bash-5.0# pact-broker can-i-deploy --pacticipant="$provider"           --version="$pr_sha"           --pacticipant="$consumer"           --latest="master"           --broker_username="$broker_username"           --broker_password="$broker_password"           --broker_base_url="${broker_url}"
Computer says yes \o/
There are no missing dependencies
```
=> BAU Put broker_url in double quotes to permit parameter expansion

ci/pipelines/pr.yml
Runs mvn clean install as per current Jenkinsfile.
Set this config on our pr pipeline and the new job passes: https://cd.gds-reliability.engineering/teams/pay-deploy/pipelines/pr-ci/jobs/java-commons-test/builds/1
Probably scope to align some of the mvn task definitions but this one has been inlined since it is the only one to use `install` phase.
=> PP-6823 Add pay-java-commons to pr pipeline

ci/tasks/pact-provider-master-verification.yml
The java pact tests require a host rather than url for the pact broker
so remove the `https://` from the beginning.
Tested this on a hijacked container and it works.
=> BAU Fix pact broker host var when running mvn test

ci/tasks/endtoend/task.yml
We effectively run `docker system prune -af --volumes` when the e2e task
exists via a trap. However we're not stopping the containers used in the
e2e tests so they're not pruned when that is run. This leaves the
containers and images hanging around. If we stop the containers before
running `docker system prune` it should clear them all out and free up
more disk quicker.
I've tested this idea on a hijacked container. The `docker system prune -af --volumes` that ran as part of the task exiting only reclaimed 961MB and seemed to be due to pruning the images that are not part of that directdebit e2e scenario and so wouldn't have been running. https://cd.gds-reliability.engineering/teams/pay-deploy/pipelines/pr-ci/jobs/directdebit-frontend-test/builds/41#L5f186f35:326
Hijacking the container …
=> PP-6832 Stop containers used for e2e

ci/tasks/endtoend/task.yml
`docker-compose down` will stop running containers if the tests succeed
but if they fail and the trap is triggered before that line then `docker
stop $(docker ps -q)` will stop them before the `docker system prune`
runs.
=> PP-6832 Stop docker containers in clean up trap

ci/tasks/endtoend/task.yml
Check if any containers are running otherwise `docker stop` will report an error
which might be confusing.
=> PP-6832 Amend docker stop command

ci/tasks/node-build-pr.yml
- Strech uses an older version of git without backports that causes
husky to fail, bump it by adding backports
=> PP-6845 Upgrade Git on node-stretch

ci/pipelines/pr.yml
- Run Node PR tests on pay-stubs to be able to remove the jenkins jobs
=> BAU pay-stubs builds

ci/pipelines/pr.yml
It appears that `name` is no longer a valid field within the `step`
schema, see: https://concourse-ci.org/jobs.html#schema.step. This change
fixed the pipeline so it passes `fly validate-pipeline`.
##WHAT##
```
gds5062:pay-omnibus danworth$ fly validate-pipeline  -c ci/pipelines/pr.yml
looks good
```
=> PP-6854 Remove name field from steps

.secrets.baseline
In an effort to prevent accidental leakage of secret material via Git commits GDS Cyber have developed [gds-pre-commit](https://github.com/alphagov/gds-pre-commit).
This is easily installed and provides a git hook to automatically scan files for accidental inclusion of various "secret-looking" material.
The `.secrets.baseline` file configures the tool with known non-secrets in this repo to prevent false positives and to save everyone else having to set it up.
See: https://github.com/alphagov/gds-pre-commit/blob/master/usage.md
To take advantage of protection against accidental secret leakage, [install gds-pre-commit](https://github.com/alphagov/gds-pre-commit#quick-install).
=> BAU: Add gds-pre-commit secrets detection config

terraform/staging-paas/terraform.tfvars
- Connector no longer needs a base URL in the secret service as it is no
longer retrieved from there.
=> PP-6883 Remove Notify Base URL

ci/tasks/endtoend/task.yml
Set the same memory limits for e2e container and JVM as we currently do on
Jenkins.
Appears we set these values on Jenkins here: https://github.com/alphagov/pay-scripts/blob/b5e643eb2ee353a2be482797535efb0747d99942/jenkins/ruby-scripts/pay-environment.rb#L8
We've seen occasions on concourse ci when we exhaust worker memory and the OOM killer kicks in. Seems prudent to introduce similar memory limits for e2e and see what impact this has.
=> PP-6917 Add memory limit for e2e tasks

ci/pipelines/pr.yml
This is to try and protect worker memory which is currently easily
exhausted if mulitple prs are raised concurrently. Java apps takes
approximately 11GB at their peak since unit, pact, intergration and e2e
overlap.
This won't offer total protection since it won't protect the worker
limits if multiple prs are raised across mulitiple apps.
This should likely be replaced with some kind of autoscaling solution/
provisioning of extra worker capacity. We are also planning to make e2e
optional on PRs.
Docs on `serial`
https://concourse-ci.org/jobs.html#schema.job.serial
which takes precedence over the existing `max_in_flight` setting
https://concourse-ci.org/jobs.html#schema.job.max_in_flight
```
GDS5062:pay-omnibus danworth$ fly -t pay-dev validate-pipeline -c ci/pipelines/pr.yml
looks good
```
=> PP-6934 Run e2e on Java apps serially

ci/pipelines/pr.yml
We want e2e to be optional on prs. To run this from now on pin the
correct version in the adminusers pr resource and manually hit "build"
(or use `fly`).
```
gds5062:pay-omnibus danworth$ fly validate-pipeline -c ci/pipelines/pr.yml
looks good
```
=> PP-6966 Remove auto trigger for adminusers card e2e

ci/pipelines/pr.yml
These will now be manually triggered as needed by pinning the
resource to the appropriate resource and triggering a new build
manually. This is so that they are optional for prs.
Make e2e optional for prs. I have removed the corresponding branch protection rules which used to mandate passing of e2e before merging. Passes fly pipeline validation
```
gds5062:pay-omnibus danworth$ fly validate-pipeline -c ci/pipelines/pr.yml
looks good
```
=> PP-6966 Remove auto trigger for e2e jobs

ci/pipelines/pr.yml
Record the time a pr takes to successfully build. Since e2e is optional
this is not a pre-requisite for measuring the time and is therefore not
included in the duration. We may wish to consider this later on.
=> PP-6944 Add pr build time job to each app

ci/pipelines/pr.yml
Pay stubs only needs install and tests running.
Rather than make `node-build-pr.yml` any more complicated with conditional logic for pay-stubs just inline the simple task to install and test.
Also add recording of pr build time whilst we're here.
=> Pp 6996 fix pay stubs ci

ci/grafana/percent_non_erroring.json, ci/grafana/successful_pr_percentile_values.json, ci/grafana/successful_pr_percentile_values_heatmap.json, ci/grafana/successful_pr_percentile_values_per_app.json
- When terraform is run on grafana it will destroy the state of our
dashboards, we should keep a record of their state in JSON so we can restore
from the existing setup
=> PP-6944 Store Dashboard JSON

terraform/modules/paas/carbon-relay.tf, terraform/modules/paas/metric-exporter.tf
Binds metric exporter and carbon relay to Splunk log service in "non-cde" space.
=> BAU: Bind carbon-relay and metric-exporter to correct log service

terraform/modules/aws/card-connector.tf, terraform/modules/aws/ledger.tf, terraform/modules/aws/variables.tf, terraform/modules/aws/vpc.tf, terraform/staging-aws/site.tf
- Adds a default VPC with relevant configuration.
- Allows VPC CIDR range to configured per-environment to support VPC peering without overlapping ranges.
- Configures the default security group with null settings
- Adds a default route table
- Various formatting fixes 🧹
=> PP-6914: Add VPC to AWS environments

terraform/staging-account/site.tf, terraform/staging-aws/site.tf
Ensures AWS Terraform provider declared in staging AWS infra may only be applied in the staging AWS account. This helps prevent the accidental application of changes in the wrong environment.
Also enables Cyber security's cross-account audit role
=> PP-6914: Only allow staging TF to be applied in staging AWS account

terraform/staging-account/site.tf, terraform/test-account/site.tf
Updates Cyber security AWS account audit TF module to TF 0.12 compatible module.
See commit: https://github.com/alphagov/tech-ops/commit/720885a9769c40942ff30b32179e1fad18f2ca10
=> BAU: Update cyber security audit role to TF 0.12 compatible module

terraform/modules/aws/cloudfront_logging/main.tf, terraform/modules/aws/route53.tf, terraform/modules/aws/waf_logging/main.tf, terraform/staging-account/site.tf, terraform/staging-aws/site.tf, terraform/staging-paas/site.tf, terraform/test-account/site.tf
The v3 AWS Terraform provider was released in July 2020. 
See changelog: https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md
The only breaking changes were related to the `aws_route53_record` resource. I have applied this to the staging environment successfully.
=> BAU: upgrade all Terraform to use AWS provider v3

terraform/modules/aws/rds.tf, terraform/modules/aws/rds/subnets.tf, terraform/modules/aws/rds/variables.tf, terraform/modules/aws/variables.tf, terraform/modules/aws/vpc.tf
- Creates a subnet in each AZ for placement of RDS instances
- CIDR for staging VPC is `172.20.0.0/16`. 
- RDS subnet range starts at 0, (defined in `subnet_ranges`). This produces the following subnets: `172.20.0.0/24`, `172.20.1.0/24`, `172.20.2.0/24`.
- Creates a security group with a rule allowing ingress from PaaS Ireland VPC internal (peered) CIDR range
=> PP-6914: Add RDS subnets and PaaS VPC ingress

terraform/staging-aws/site.tf
We have torn down all Staging infra in the `eu-west-2` region. This change will move infra to `eu-west-1` to align with PaaS Ireland infra location.
=> PP-6914: Move Staging AWS infra to eu-west-1 region

terraform/modules/aws/rds/subnets.tf, terraform/staging-aws/site.tf
This change updates the Staging AWS account VPC CIDR to 172.16.0.0/16 and updates the base RDS subnet group range to a CIDR within a range compatible with PaaS for VPC peering.
=> PP-6914: Update VPC cidr & RDS base subnet

terraform/staging-paas/site.tf
This is used by the sqs ups to set the correct sqs url.
Already applied to paas staging and ledger/card-connector now start up.
=> PP-6913 Update the aws region used for paas module

ci/pipelines/pr.yml
We still exhaust worker memory when multiple prs are raised across
applications despite turning off e2e tests. We want to get the pipeline
running reliably and improve performance from there if necessary. This
introduces `serial_groups` which limits all jobs tagged with the same
`serial_groups` to run one at a time. To start with each type of test
e.g. unit, integration, pact has its own serial group tag.
We should monitor the effect this has upon our PR pipeline SLOs, both build
time and error rate.
After another chat with Chris Farmiloe we've decided to implement `serial_groups`.
Mostly as described. I opted for `node_test` as a separate tag since the way we test node apps includes both unit, integration and Cypress within the same job so they don't really fall into a more granular …
=> PP-7062 Add serial groups to pr pipeline

terraform/modules/aws/rds.tf, terraform/modules/aws/rds/main.tf, terraform/modules/aws/rds/subnets.tf, terraform/modules/aws/rds/variables.tf, terraform/modules/aws/variables.tf, terraform/modules/aws/vpc.tf, terraform/staging-aws/site.tf, terraform/staging-aws/terraform.tfvars
Provisions all RDS instances within an RDS subnet group in a given environment.
- Accepts a map of database instances with optional configuration
- Default configuration is applied where values are omitted
- Configures a VPC peering connection to the RDS subnet group from GOV.UK PaaS
- Adds peering connection to VPC routing table
=> PP-6913: Provision RDS instances

terraform/modules/aws/cloudfront_logging/transformation-lambda.tf, terraform/modules/aws/hosted-graphite.tf, terraform/modules/aws/notifications.tf, terraform/modules/aws/products-ui.tf, terraform/modules/aws/publicapi.tf, terraform/modules/aws/rds/main.tf, terraform/modules/aws/selfservice.tf, terraform/modules/aws/variables.tf, terraform/modules/aws/waf_logging/lambda.tf, terraform/staging-aws/site.tf, terraform/staging-aws/terraform.tfvars
- Add remaining dbs in similar fashion to `card-connector`.
- Fix up deprecation warnings.
- Ignore changes to snapshot identifiers and remove them now that we've created the databases since we don't want to reset the dbs to these snapshots each time we TF the environment.
- Pass the paas vpc peering connection name in from `staging-aws/site.tf` since it'll be different for each environment.
=> Pp 6913 add remaining dbs

terraform/modules/aws/rds/main.tf
Enables performance insights to aid debugging of DB performance issues.
- Provides 7-day retention of performance data.
- Performance data is encrypted with default RDS KMS key
More info: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PerfInsights.Overview.html
=> BAU: Enable RDS performance insights with default settings for all DBs

terraform/modules/paas/adminusers.tf, terraform/modules/paas/card-connector.tf, terraform/modules/paas/ledger.tf, terraform/modules/paas/products.tf, terraform/modules/paas/publicauth.tf, terraform/modules/paas/variables.tf, terraform/staging-paas/site.tf, terraform/staging-paas/terraform.tfvars
Add the peered in rds credentials for connector db to the
card-connector-secret-service. The `db_host` comes from a data
`aws_db_instance`. This can be extended using a `for_each` to get the
db_instances for the other apps.
=> PP-7020 Add db credentials for card-connector

terraform/staging-paas/terraform.tfvars
This option is used by apps to ensure DB connections are made over TLS.
A corresponding change should be made to the env-map.yml file in each app's repository to ensure this option is mapped to the `DB_SSL_OPTION` environment variable from the secret service at run time.
=> PP-7020: Add db SSL connection option to static app configuration

ci/pipelines/deploy.yml
Direct Debit is no longer needed. PR & merged test & build pipelines will remain intact allowing apps to be maintained until they may be required again. However deployment tasks and subsequent smoke tests are now removed.
=> BAU: Remove DD connector & frontend deployment & smoke tests

terraform/staging-paas/site.tf
Now that RDS instances used by PaaS apps are accessed via a peered VPC connection, the PaaS RDS service broker databases are no longer required and can be removed from the staging infrastructure.
=> PP-6913: Remove PaaS provided RDS services

terraform/modules/aws/card-frontend.tf, terraform/modules/aws/notifications.tf, terraform/modules/aws/products-ui.tf, terraform/modules/aws/publicapi.tf, terraform/modules/aws/route53.tf, terraform/modules/aws/selfservice.tf, terraform/staging-aws/site.tf
Currently the staging account has the domain registration for
`gdspay.uk`. To make the terraform consistent for any environment
(test, staging etc) create a hosted zone in which the A records for that
environments' apps are created in. Delegate the subdomain to the new  hosted
zone from the hosted zone in staging which owns the `gdspay.uk`
registration; this is to be done manually for now by adding the
necessary name server record pointing to the name servers of the new
hosted zone.
Remove subdomain interpolation in favour of using `var.domain_name`
passed in from the environment module, e.g. `staging.gdspay.uk`..
Co-authored-by: dan worth <dan.worth@digital.cabinet-office.gov.uk>
We've applied this to staging and it all seems to work, smoke tests green and dns resolves as expected.
=> PP-7025 Use separate hosted zones for sub domain delegation

terraform/modules/aws/card-frontend.tf, terraform/modules/aws/notifications.tf, terraform/modules/aws/products-ui.tf, terraform/modules/aws/publicapi.tf, terraform/modules/aws/selfservice.tf
`web_acl_id` property of an `aws_cloudfront_distribution` actually needs to be an ARN even though the docs state ID. https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#web_acl_id
`aws_wafv2_web_acl_logging_configuration` need to use the `us` (us-east-1) provider because they are "global" resources.
=> PP-7150: Web ACL Access Configuration

ci/pipelines/test-deploy.yml, paas/env_variables/test-smoke-tests.yml, paas/env_variables/test.yml
App deployment is triggered by a new git release tagged with
`paas_release-n`. The release is downloaded, the source files extracted
and then pushed into the `test` or `test-cde` space as appropriate.
Mostly copied from `pay-deploy/deploy` pipeline which deploys into
staging.
Pact verifiction to be added in future commit.
Initial creation of the pipeline to deploy apps into the test space. See this diagram for the wider context
https://hackmd.cloudapps.digital/cwTUHKxYTjiO3CRiamUpsg?view
I've left the smoke test setup in from copying it over and I've updated it staging > test where I think necessary. It might not work but sorting out sandbox smoke tests is part of https://payments-platform.atlassian.net/secure/RapidBoard.jspa?rapidView=83&projectKey=PP&modal=detail&selectedIssue=PP-7027
=> PP-7026 Create new pipeline to deploy apps to test environment

ci/pipelines/deploy.yml, ci/pipelines/test-deploy.yml
Possibly something changed since we last deployed it in April but need
to add the space and mapping from the `cardid-data` source to the
generic `artefact` directory which is used by the deploy script.
Sorts out deployment of cardid-data in test and staging. I've applied this and both successfully deploy, as do the corresponding cardid apps in both environments.
=> PP-7026 Add space to cardid data deployment

terraform/staging-paas/terraform.tfvars, terraform/test-paas/terraform.tfvars
To use API tokens that already existed within the copied RDS data from
test-12 or staging-2 we need to use the same bcrypt salt and hmac
values.
=> PP-7027 Use bcrypt salt and hmac values from existing infra

ci/docker/pact_with_jq/Dockerfile, ci/tasks/pact-provider-test-preflight-check.yml
Switch to `json` output which is easier to parse. The preivous logic was
not correctly identifying providers that required validation when they
had not yet been validated against the version of the contract in the
request. This uses a new container which adds `jq` to the
`pactfoundation/pact-cli` image we were already using.
Previous we were parsing the `can-i-deploy` table response with `awk`, we didn't know `json` format was available. This hopefully makes it clearer and correctly identifies cases when provider validation is required.
The bug in this script is mitigated because Jenkins has been running pact validation on main builds.
I have built and pushed the `govukpay/pact_with_jq` image to dockerhub: https://hub.docker.com/repository/docker/govukpay/pact_with_jq
Tested the `jq` with …
=> PP-7022 Fix can-i-deploy check

ci/pipelines/test-deploy.yml
Seems like group and task names must be all lower case and ' ' are no
longer permitted.
Addresses the following warnings, I think this is due to big concourse getting an upgrade
```
gds5062-2:pay-omnibus danworth$ fly -t pay-dev sp -c ci/pipelines/test-deploy.yml -p test-deploy
DEPRECATION WARNING:
- groups.Adminusers: 'Adminusers' is not a valid identifier: must start with a lowercase letter
- groups.Card Connector: 'Card Connector' is not a valid identifier: must start with a lowercase letter
- groups.Card ID: 'Card ID' is not a valid identifier: must start with a lowercase letter
- groups.Card Frontend: 'Card Frontend' is not a valid identifier: must start with a lowercase letter
- groups.Ledger: 'Ledger' is not a valid identifier: must start with a lowercase letter
- groups.Products: …
```
=> PP-7021 Clean up new deprecation warnings

ci/tasks/pact-provider-verification.yml
Now we're using jq the provider names are wrapped in `"`. Update the
check to accomodate this.
=> PP-7022 Update the check for whether the provider requires validation

ci/pipelines/deploy.yml, ci/pipelines/test-deploy.yml, ci/scripts/setup_smoke_tests.sh
In the early days of the PaaS migration we used a bit of the `pay local`
cli to create a user to be used for the sandbox smoke tests. Now we are
using snapshots of RDS instances from our existing environments e.g.
`test-12` we want to use the existing smoke test services and accounts.
Therefore remove the concourse job that would create a new smoke test
user and add a simple script to help set the necessary values.
=> PP-7027 Remove smoke test user setup

ci/tasks/node-build-pr.yml
We run each node app's lint script on Jenkins and we should do the same
on Concourse.
`npm run lint` is run on Jenkins via each app's `build_and_test.sh` script:
```
grep "npm run lint" pay-*/docker/build_and_test.sh                                                             
pay-direct-debit-frontend/docker/build_and_test.sh:npm run lint &&\
pay-frontend/docker/build_and_test.sh:npm run lint
pay-products-ui/docker/build_and_test.sh:npm run lint
pay-selfservice/docker/build_and_test.sh:npm run lint
```
toolbox is built differently but also includes a `lint` script in it's `package.json`:
```
pay-toolbox/package.json -- lint script --> "eslint "src/**/*.{js,ts,tsx}""
```
On the Concourse pr pipeline we test each of those node apps using `node-build-pr.yml` which is modified herein to add …
=> PP-7213 Run lint checks on node prs

ci/pipelines/test-deploy.yml
After a pre-release with the tag format `paas_release-n` has been
deployed and the smoke tests have passed, create a pre-release with the tag
`paas_release_test-n` which can then be deployed into staging.
This is just for Adminusers and will apply the same to the other apps if
we agree on this approach.
As described above. I've tested this out and the resulting pre-release is here: 
https://github.com/alphagov/pay-adminusers/releases/tag/paas_release_test-62
=> PP-7021 Create paas test releases

ci/pipelines/deploy.yml, ci/pipelines/test-deploy.yml
Seems the pipeline has moved on since it was last deployed and the
config needs updating to correctly reference the location of the files
to push.
Updated for test and staging environments.
Deploying the `metric-exporter` was broken because the app's file location was incorrect, see error in logs: https://cd.gds-reliability.engineering/teams/pay-dev/pipelines/test-deploy/jobs/deploy-metric-exporter-test/builds/2#L5f6c2627:17
```
Incorrect Usage: The specified path '/tmp/build/1cd06cbc/metric-exporter-source' does not exist.
```
This fixes it so it now deploys correctly: https://cd.gds-reliability.engineering/teams/pay-dev/pipelines/test-deploy/jobs/deploy-metric-exporter-test/builds/2.1
Anyone wondering this fixes it, it's because the input mapping renames the directory given as the value …
=> PP-7026 Fix deployment of metric-exporter

ci/pipelines/pr.yml
Publiapi is a java consumer. This change ensures that its provider
verification (where we run it's associated providers against it's latest
contracts) happens after it's pushed the latest contracts as part of the
`publicapi-integration-test` job.
with @SandorArpa
I don't think the other apps need to change. the node consumers push their pacts as part of their `test` job which is already a prerequisite for the pact verification. Ledger is more complicated being both consumer and provider and it's pipeline looks fine.
You can see the relationships here: https://pay-concourse-pact-broker.cloudapps.digital/
=> PP-7213 Run Publicapi's provider verification after its pushed pacts

ci/pipelines/deploy.yml, ci/pipelines/main.yml
Initial work on adding main pipeline to build and create github
releases destined for paas. For the time being Jenkins will continue to run the tests on
the main branch and this pipeline will not; we may want to run the pact
tests because we're using separate brokers and `can-i-deploy` checks will be much
more complicated if we don't. Later work will migrate the testing from
Jenkins to this pipeline.
Changes included here:
- Build connector when a commit to main branch is made
- Create and upload github pre-release tagged `paas_release-n`
- Remove building of connector release from existing `deploy` pipeline
- Trigger the deployment of connector into staging via a release tagged
with `paas_release_test-n` which is created via the
`pay-dev/test-deploy` pipeline.
This is almost identical to …
=> Pp 7121 create main build pipeline

ci/pipelines/pr.yml
This is how it works for publicapi.
Initially tried to follow how it works for ledger, but this has a
different setup and the publicapi way of doing it seems sensible.
=> PP-7253 Publish connector pacts as part of integration tests

ci/pipelines/main.yml
When we build connector after a merge to the main branch tag the pacts
for that version of connector with `main`.
This is new since Connector has just become a consumer.
Applied this to main pipeline and it works as expected, here are the connector contracts tagged with `main`
https://pay-concourse-pact-broker.cloudapps.digital/hal-browser/browser.html#/pacticipants/connector/versions/074423d2109c1575b918e122d5a4f1a9cfd3ddf6
=> PP-7121 Tag connector pacts with main

ci/tasks/pact-provider-test-preflight-check.yml
We are now tagging pacts for commits when they have been merged to master with the "main" tag rather than "master". Update PRs to ensure we are validating providers against the correct consumer version.
=> PP-7253 Validate pacts against consumers with main tag

ci/pipelines/pr.yml
Use the 'latest' tag image rather than 'dev'. I think we experimented
with the 'dev' tag because it had some functionality we were exploring
during the development. I don't think we're reliant upon it now, but the
'dev' tag is broken so we need to move from it.
Applied to concourse and this resolves the pr resource errors we suddenly started to see.
=> We were using the 'dev' tag for the pr resource

ci/tasks/pact-provider-tagged-verification.yml, ci/tasks/send-hg-metric.yml, ci/tasks/tag-pacts.yml
- Remove the docker images from my personal dockerhub account to the
govukpay one since we are now later in develpoment and no longer need as
rapid prototyping capability
=> BAU Update Docker Images

ci/pipelines/main.yml, ci/pipelines/pr.yml
- Downgrade the version of the Concourse Github PR Resource to see if it
is in fact new changes introduced to the resource check regarding PR
filtering that is causing the rate limiting error we are seeing.
=> PP-6761 Downgrade Concourse Github PR Resource

ci/pipelines/pr.yml
It seems e2e was removed for DD-Frontend because we're not currently
pursuing DirectDebit and DirectDebit e2e wasn't fully implemented.
However it was still sending a pending status for e2e and pulling the
containers. This removes it to complete the removal.
=> BAU Remove e2e pending status for DD-Frontend

ci/pipelines/toolbox-test-ecr.yml
Adds a new pipeline for pushing Toolbox Docker images to ECR.
- The pipeline checks for new Github releases tagged as `alpha_release-*`
- This triggers a job to pull an image with that commit SHA from Dockerhub, and save it to `image/image.tar`
- The next job then pushes the `image/image.tar` to the ECR repository resource, using the `commit_sha` as the tag.
Environment variables needed:
- `pay_aws_test_account_id` (the same ID is used for the new IAM role and the ECR registry)
- `github-access-token` (already used elsewhere in Pay's Concourse)
- `docker-username` and `docker-password` (already used elsewhere in Pay's Concourse)
- `readonly_secret_access_key` and `readonly_session_token` (provided by Big Concourse)
We've tested the following locally:
- github release trigger with a test …
=> PP-7657 Concourse toolbox ECR test pipeline

ci/pipelines/apps-test-ecr.yml, ci/tasks/pull-image-from-dockerhub.yml
TODO:
- ~we have duplicated the ECR registry resource for each repo, this could probably be DRYer~
- ~ci/pipelines/toolbox-test-ecr.yml could be renamed but we'll do that later for ease of reviewing just now.~
- ~revert https://github.com/alphagov/pay-ci/pull/363/commits/9e837183aa45cbbe9f25de92d6c7f47dc6e26be0 to put the meta job branch back to `master`~
Used the group formatting to combine all the app tasks into one pipeline, as per the pr-ci pipeline.
Pulling the pay-cardid repo is a special case in that it has a private submodule. To get the repo we have ignored the submodules when pulling:
```
- get: cardid-git-release
trigger: true
params:
submodules: none
```
And then updated the repo in a separate task akin to https://github.com/alphagov/pay-ci/blob/master/ci/pipelines/pr.yml#L1253 …
=> PP-7683 apps into test ECR

README.md
The CI checks on this repo itself have been failing since we renamed it in January. While we're fixing it, I thought I'd add some info on the `pipecleaner` tool that check is using.
=> BAU: add info about meta PR checks

ci/pipelines/apps-test-ecr.yml
pull-image-from-dockerhub.yml is located in the apps-test-ecr directory as
specified by the apps-test-ecr resource.
This fixes the error
```
unknown artifact source: 'toolbox-test-ecr' in task config file path 'toolbox-test-ecr/ci/tasks/pull-image-from-dockerhub.yml'
```
(see https://cd.gds-reliability.engineering/teams/pay-dev/pipelines/apps-test-ecr/jobs/products-ui-image-to-test-ecr/builds/10)
=> PP-7683: Fix file location

ci/pipelines/pr.yml, ci/tasks/java-package.yml, ci/tasks/java-tests.yml, ci/tasks/node-build-pr.yml, ci/tasks/node-build.yml, ci/tasks/pact-provider-test-preflight-check.yml, ci/tasks/pact-provider-verification.yml, ci/tasks/publish-pacts.yml, ci/tasks/zip-build.yml
The `pr-ci/ci-pr-test` job has been failing consistently for some weeks (see [an example failed build](https://cd.gds-reliability.engineering/teams/pay-dev/pipelines/pr-ci/jobs/ci-pr-test/builds/47.1)).
This job has been using [pipecleaner](https://github.com/alphagov/paas-cf/tree/main/tools/pipecleaner#features) to run several checks:
- Concourse's own validation
- Shellcheck on any shell or bash scripts
- Resource check, to flag any unused resources in a job description
- (Pipecleaner can also run Rubocop, but we've disabled that option)
I don't think the repo-renaming itself caused the failures, however we can't check further back as the old `omnibus-pr-test` pipeline no longer exists on Big Concourse.
I've gone by the shellcheck suggestions, and validated those using the [online …
=> BAU: fix ci-pr-test failures

ci/pipelines/apps-test-ecr.yml, ci/tasks/pull-image-from-dockerhub.yml
Description:
- This PR adds a pipeline for the nginx proxy which pulls an image from Dockerhub and pushes it to ECR test
=> PP-7683 - Add nginx proxy pipeline to ECR test

ci/pipelines/apps-test-ecr.yml
New nginx-forward-proxy images are detected based on a new semantic version
(appended with the "alpine" tag) found in the
govukpay/nginx-forward-proxy repo in dockerhub. To get this to work we needed
to use a specific version of registry-image-resource as the default one got by
concourse is an older version:
```
- name: updated-registry-image
type: registry-image
source:
repository: concourse/registry-image-resource
tag: "1.1.0"
```
We have settled with doing this because it does not have its own repository like the
other apps do. Rather, it is currently in the pay-infra project, so it would be
incorrect to tag the pay-infra project. As this nginx-foward-proxy is only used
in frontend and rarely changes, we have decided that a short term solution
would be to listen on the (semvar)-alpine …
=> PP-7683: Push nginx-forward-proxy to test ecr

ci/pipelines/apps-test-ecr.yml
Description:
- This PR ensures that the nginx-forward-proxy job is triggered automatically on a new docker image release
=> PP-7683 - Automatically trigger nginx-forward-proxy Concourse job on new Dockerhub release

ci/pipelines/apps-test-ecr.yml
Splits existing toolbox test pipeline into two:
First pipeline triggers on git release, then takes an image from
dockerhub and pushes it to test ecr.
The only change here is that on pushing to test ecr, we add a tag
to the image of the form 123-release. This is in order to trigger
the second pipeline
The second pipeline is triggered by a push to test ecr of an image
with tag of the form `123-release`. THis pipeline has two dummy
jobs to deploy and smoke test this new image (these were previously
tasks, but it makes things clearer to have them as jobs). It then
pushes the image to staging ecr. No tags are added at this stage,
since the staging pipeline only needs a tag of form above (and this
also allows us to refer builds back to originating code change).
=> PP-7794 Split toolbox test pipeline in to build and deploy

ci/tasks/parse-release-tag.yml
Generic task that takes a git release (assuming it is tagged `alpha_release-XXX`) and writes out a docker tag of form `XXX-release`. We can use input mapping to use this for all our pipelines.
=> PP-7794 Parse release tags task

ci/pipelines/toolbox-staging-deploy.yml
Push image to prod ecr after a successful deploy and smoke tests on staging.
We have a green build here https://cd.gds-reliability.engineering/teams/pay-deploy/pipelines/toolbox-staging-deploy/jobs/toolbox-staging-deploy/builds/20
=> PP-7796: Push image to prod ecr

ci/pipelines/apps-test-ecr.yml
Splits frontend, connector, ledger, adminusers and products pipelines as per pattern established by toolbox. Results have been applied so you can look at concourse to see if things look right
=> PP-7794 split remaining app pipelines #1

ci/pipelines/apps-test-ecr.yml
Splits products-ui, publicauth, publicapi and selfservice  pipelines as per pattern established by toolbox. Results have been applied so you can look at concourse to see if things look right
=> PP-7794 split remaining app pipelines 2

ci/docker/terraform/Dockerfile, ci/pipelines/apps-test-ecr.yml
Job uses terraform to deploy a new version of toolbox. The logic is the same as in current ci deploy script https://github.com/alphagov/pay-infra/blob/master/provisioning/scripts/deploy-ecs/ci.rb - i.e we specify an application_image_tag` but leave terraform to set the proxy image tag. No waiting logic at this stage.
Am also committing in the config for docker image that runs thistask - this still needs a pipeline, or maybe another way of doing this (e.g. terraform assume role)
=> PP-7800 Job to deploy toolbox

ci/docker/node-aws-sdk-runner/Dockerfile, ci/pipelines/apps-test-ecr.yml, ci/scripts/wait-for-deploy.js, ci/tasks/assume-role.yml
Adds task to wait for successful ECS deployment using a node script. We have factored out the `assume-role` task and used `load_var` to use the role in both deployment  and waiting tasks (thanks to @rjbaker for this).
See commit s for more detail.
=> PP-7800 wait for deploy

ci/pipelines/apps-test-ecr.yml, ci/scripts/assume-role.js, ci/tasks/assume-role.yml
Use node instead of python + bash to do assume role task. Makes it more maintainable, and clearer.
=> PP-7800 jsify assume role task

ci/docker/node-runner/Dockerfile, ci/pipelines/apps-test-ecr.yml, ci/scripts/get-git-sha-for-release-tag.js, ci/tasks/get-git-sha-for-release-tag.yml
In order to tag a pact with something (eg "test-fargate"), we need the version
which is the git commit sha of the release tag.
In line with the agreed practice of writing scripts in node, we have decided to
make use of a github node api. To this end we have added the `octokit/rest` npm
library to our node-aws-sdk-runner and renamed it to node-runner.
Example successful build: https://cd.gds-reliability.engineering/teams/pay-dev/pipelines/apps-test-ecr/jobs/frontend-pact-tag/builds/3
=> PP-7834: Scripts to get git sha for a release tag

ci/pipelines/apps-test-ecr.yml
How to review:
Check https://cd.gds-reliability.engineering/teams/pay-dev/pipelines/apps-test-ecr to verify green builds for <app>-pact-tag jobs for the relevant apps. 
Check https://pact-broker-test.cloudapps.digital/ to verify apps have been tagged with `test-fargate`.
=> PP-7834: Pact tag for all other apps

ci/pipelines/apps-test-ecr.yml
How to review: check the relevant deploy-"app-name" jobs in https://cd.gds-reliability.engineering/teams/pay-dev/pipelines/apps-test-ecr, verifying that the check-pact-compatibility task has run successfully.
=> PP-7834: Pact compatibility check for all other apps

ci/pipelines/toolbox-staging-deploy.yml
Add deploy step to toolbox staging pipeline. I have also split the pipeline up similarly to test pipeline, and introduced job groups. As part of this I have removed the task that passed through additional tags from the staging image through to the prod one. This is because we now don't pass any such tags from upstream. If we need to e.g. retrieve the git sha for code corresponding to an image we have a task that can do that.
=> PP-7686 Add deployment to staging toolbox pipeline

ci/docker/concourse-runner/Dockerfile
Description:
- Running bash unit tests with the govukpay/concourse-runner requires the jq package to be present
=> PP-7877 - Add jq package to runner to run telegraf bash unit tests

ci/pipelines/deploy-to-test.yml
Description:
- This PR builds a Concourse pipeline which will git clone pay-infra only when there are changes to the images/docker/govukpay/telegraf
sub-directory
- It will run bash unit tests (e.g. start.test.sh) and the subsequent job will build the docker image upon passing and push to test ECR
- A subsequent PR will refactor the docker image job as we use it when building the Concourse runner
=> PP-7877 - Build concourse pipeline to build telegraf image

ci/pipelines/deploy-to-staging.yml
Very similar to test.
No pact compatibility check as that can only be added once all apps are being pact tagged.
Removed trigger from `deploy-frontend-to-staging` job - this will be manually triggered for time being as it is in CDE (see https://docs.google.com/document/d/1oJ347kiaB_tBp-Q_7iZ1NC-xv-uQLz4etoyqI90IKVs)
=> PP-7687 Frontend staging pipeline

ci/pipelines/deploy-to-staging.yml
Adds deployment pipelines for adminusers, products and products-ui (with pact tagging) and cardid and publicauth. Follows exact same pattern established by toolbox and frontend
=> PP-7688 add more staging deployments

ci/pipelines/deploy-to-test.yml
Description:
- We have decided to move the telegraf docker image into its own repo at https://www.github.com/alphagov/pay-telegraf
- This PR updates the deploy-to-test pipeline to listen for new merges at that URL
=> PP-7877 - Modify telegraf pipeline repo

.gitignore, ci/pipelines/deploy-to-test.yml, ci/scripts/assume-role.js, ci/scripts/get-git-sha-for-release-tag.js, ci/scripts/package-lock.json, ci/scripts/package.json, ci/scripts/run_ecs_db_migration.js, ci/scripts/wait-for-deploy.js
Follows the same principles as our existing ruby script run on Jenkins.
Run the current active task defintiion for the service (e.g. Ledger)
whilst overriding the `RUN_MIGRATION` and `RUN_APP` to `true` and
`false` respectively.
If the image version used as the input to the job does not match the
image version of the app currently running then print a warning and
exit.
Update the test deploy pipeline with a ledger-db-migration job.
The interesting bits are in the first commit, the remaining three as some housekeeping. 
Here is a link to the job running: https://cd.gds-reliability.engineering/teams/pay-dev/pipelines/deploy-to-test/jobs/ledger-db-migration/builds/17
Here is a link to the [Splunk search showing the log out put of a ledger db migration …
=> Pp 7881 fargate db migrations

ci/pipelines/deploy-to-test.yml
We plan to use Toolbox deployments as a way of ensuring new versions of sidecars are not totally broken. This commit enbables this by triggering a new deploy of toolbox when a new version of telegraf appears in test ECR. The job then deploys this new version (alongside version of toolbox specified by toolbox ecr resource) I have split into an inline task so as not to have any confusing logic in the deploy-app task.
See https://cd.gds-reliability.engineering/teams/pay-dev/pipelines/deploy-to-test/jobs/deploy-toolbox/builds/149
=> PP-7877 Trigger toolbox deploy on new telegraf

ci/pipelines/deploy-to-test.yml
Building on the first ledger db migration job this adds jobs for the
remaining apps with RDS instances.
```
gds5062-2:pay-ci danworth$ fly -t pay-dev vp -c ci/pipelines/deploy-to-test.yml
looks good
```
=> PP-7914 Add db migration jobs for deploy-to-test

ci/pipelines/deploy-to-test.yml
This commit updates the pipeline to:
* listen on new telegraf tags, e.g. 123-release
* pushes the telegraf image to aws test ecr with 123-release tag
with @nimalank7 @mrlumbu
=> PP-7877: Update telegraf pipeline

ci/pipelines/deploy-to-test.yml
Description:
- Since there are no smoke tests testing toolbox specifically what we will have is the pipeline pushing telegraf to staging ECR only if there has been a successful toolbox deployment to test
=> PP-7877 - Update deploy telegraf to staging ECR

ci/pipelines/deploy-to-staging.yml
Description:
- This PR adds a job which pushes the telegraf image to ECR production only when Toolbox is deployed successfully to the staging environment
- With @oswaldquek @mrlumbu
=> PP-7877 - Push telegraf to ECR production

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml
This is needed so we can start doing pact compatibility checks
=> PP-7688 Add pact tag job for selfservice and connector

ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml
Description:
- Since the telegraf image will be deployed to both staging and production ECR conditional on passing the deploy-toolbox
and deploy-toolbox-staging jobs it makes sense to display it in the UI for clarity
=> PP-7877 - Show deploy-toolbox and deploy-toolbox-to-staging in telegraf group

ci/pipelines/deploy-to-production.yml
Description:
- Some production ECR resources were missing the role configuration which caused an authentication error when checking.
- Toolbox should only check for `*-release` Telegraf variants as that is what the docker images are tagged with
=> PP-7877 - Fix authentication error with production ECR

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml
Now we have pact tagging in all pipelines we can do pact compatibility checks (as we already do in test pipeline) to ensure compatibility of services in a given environment.
See https://cd.gds-reliability.engineering/teams/pay-deploy/pipelines/deploy-to-staging/jobs/deploy-adminusers-to-staging/builds/2 e.g. for example of this working
=> Pp 7688 add pact compatibility checks

ci/pipelines/deploy-to-test.yml
Description:
- Currently the deploy-to-test pipeline for nginx-forward-proxy triggers when there is a new nginx-forward-proxy docker image in DockerHub
which pulls the image from DockerHub and then pushes to nginx-forward-proxy test ECR
- This PR modifies the pipeline to trigger when *-release is tagged on a main merge for pay-nginx-forward-proxy which then builds the image and
pushes to nginx-forward-proxy test ECR
- Pattern is established in [PP-7877 - Build concourse pipeline to build telegraf image](https://github.com/alphagov/pay-ci/pull/405)
=> PP-7755 - Push nginx-forward-proxy with release tag from GitHub repo

ci/pipelines/deploy-to-test.yml
As with other sidecars, on new version of nginx proxy then deploythe new version as by passing in new version to toolbox deploy, and only push the new image to staging once that deploy has succeeded.
https://cd.gds-reliability.engineering/teams/pay-dev/pipelines/deploy-to-test?group=nginx-proxy
=> PP-7755 Test new versions of nginx with toolbox deploy

ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml
Description:
- This PR modifies the deploy-to-staging pipeline so when a new nginx-forward-proxy image appears in
staging ECR it will deploy frontend to staging and upon successful completion of frontend smoke tests
it will deploy the image to production nginx-forward-proxy ECR
- Fixes the error in deploy-to-test pipeline where push-nginx-forward-proxy actually pushed to nginx-proxy ECR
instead of nginx-forward-proxy ECR
=> PP-7755 - Deploy frontend to staging on new nginx-forward-proxy

ci/pipelines/deploy-to-production.yml
Description:
- Upon a new nginx-forward-proxy in prod ECR the deploy-to-production pipeline will
deploy nginx-forward-proxy to production along with frontend
- Displays the telegraf group in deploy-to-production pipeline for ease
=> PP-7755 - Deploy nginx-forward-proxy with frontend to prod

ci/pipelines/deploy-to-test.yml
Couple of funny looking things:
The message is partly comprised of a bit written to a file and then loaded to a variable. This allows us to move the task that creates the messages to a task file, parameterise etc.
The other bit of the message (the build information) is stuck on the end in the `on_{success,failure}` handlers. This is because Concourse only exposes build information in resources https://stackoverflow.com/a/40939590 so if this were appended to the message in the create messages task, all the env vars would evaluate to an empty string.
Success goes to `govuk-pay-activity`, failure to `govuk-pay-announce` as discussed in story notes.
Example of success being sent https://cd.gds-reliability.engineering/teams/pay-dev/pipelines/deploy-to-test/jobs/deploy-toolbox/builds/169 …
=> PP-7889 Notify success and failure of toolbox test deployments

ci/pipelines/deploy-to-production.yml
Description:
- We are incorrectly pact tagging some of our apps as 'prod-fargate' and others as 'production-fargate'
=> BAU - Fix pact tag bug

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml, ci/scripts/run_smoke_test.js, ci/tasks/run-smoke-test.yml
- Adds a generic task for running smoke tests, given a SMOKE_TEST_NAME corresponding to the name of the canary (this is likely to change in the near future)
- Adds the NodeJS script to trigger the canary via the AWS SDK (lifted entirely from @danworth and @rorymalcolm's [spike branch](https://github.com/alphagov/pay-ci/compare/PP-7670_spike_aws_canary), with a little tweaking for linting and error handling)
- Replaces the dummy smoke test steps with the steps to assume the trigger role for the deploy account, and call the NodeJS script for each scenario with the correct variables. 
Note that not all the Canaries are available yet in the AWS deploy account, only `card_payment_test` and `card_payment_staging`.
The new Concourse pipeline variable `pay_aws_deploy_account_id` has been added to …
=> PP-7887 Trigger smoke tests for toolbox post-deploy

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml
Fixes an oversight - this was included in the `deploy-to-test` pipeline but not the equivalent staging or production pipelines.
=> PP-7887: Add pay-ci resource to smoke tests

ci/pipelines/deploy-smoke-tests.yml
PP-7873 Add pipeline to update the smoke tests
The deploy-smoke-tests take a release of pay-smoke-tests that
is built by github actions. There is a manually triggered job to update
the canaries in test, staging and production where the pay-smoke-tests
release must have been deployed to the previous environment before
progressing. This commit does not include any automatic running of
canaries post deploy.
Here it is deployed: https://cd.gds-reliability.engineering/teams/pay-deploy/pipelines/deploy-smoke-tests
It has successfully updated the canaries in:
test environment: https://cd.gds-reliability.engineering/teams/pay-deploy/pipelines/deploy-smoke-tests/jobs/update-canaries-for-test-environment/builds/1
staging environment: https://cd.gds-reliability.engineering/teams/pay-deploy/pipelines/ …
=> Pp 7873 pipeline for smoke test changes

ci/pipelines/deploy-to-test.yml, ci/tasks/create-success-and-failure-snippets.yml
Add success and failure notifications to all deployments, smoke tests and pact tag jobs on test pipeline.
I have extracted a task to create success and failure snippets that I think is reasonably readable and self explanatory.
For deployment notifications we can tell people about versions of all the things deployed which is probably useful.
For smoke tests and pact tags we only have the version of the app (no sidecar versions) so we just include that in notification.
At present this will send all successes to `govuk-pay-activity` and all failures to `govuk-pay-announce`. I have caveated all notifications as only FAO migration team, but I think good to start sending failures to a visible channel, both for migration team to be aware, and to start to get wider team used to this whole thing. …
=> PP-7889 Notifications on test pipeline for deploys, smoke tests, and pact tagging

ci/scripts/run_smoke_test.js
When running our post-deploy smoke tests, if second app is also being deployed, and the smoke tests are already running, the `startCanary` command will fail with a 409 Conflict error.
Ideally we want the Canary to be in status STOPPED, so we can be confident that our forthcoming run will test the just-deployed app. This script adds a check on the Canary's current status, and happily proceeds if the status is STOPPED.
If the status is DELETING or ERROR, something bad has happened to our Canary and we probably shouldn't run it - raise an error.
If the status is anything else (eg RUNNING, STARTED, UPDATING) then waiting for a minute or so should bring the Canary into the STOPPED state. Our Canaries currently take way less than 60s to run and/or update, so this is fairly generous and should …
=> PP-7887: Check Canary is in a startable state

ci/pipelines/deploy-to-staging.yml, ci/tasks/create-notification-snippets.yml
Following pattern on test pipeline.
Only difference is all deployment activity (including beginning of a deployment) is posted to announce channel, as per kick off notes and current dev practice
https://gds.slack.com/archives/CAEN2AVLP/p1616598908006300
=> PP-7889 Add notifications to staging pipeline

ci/pipelines/deploy-to-test.yml, ci/scripts/check-release-versions.js
In our current Jenkins pipelines we have a check that
stops devs accidentally deploying an old version of an
app. This `check-release-versions` task achieves same thing
on Concourse - it checks the version to be deployed of each
container in a task definition, and makes sure it is the
same as or newer than currently deployed version.
There is no mechanism to override this at the moment -
if override is needed devs will need to deploy the thing
manually from laptop.
https://cd.gds-reliability.engineering/teams/pay-dev/pipelines/deploy-to-test/jobs/deploy-toolbox/builds/209
=> PP-7908 Check for downgrade

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml
Trigger ledger pipeline when new image pushed to relevant repo in staging and prod. As per ADR https://docs.google.com/document/d/1oJ347kiaB_tBp-Q_7iZ1NC-xv-uQLz4etoyqI90IKVs/edit#, ledger should be a continuously deployed thing.
=> BAU Trigger ledger pipeline on new image

ci/pipelines/deploy-to-staging.yml
It is needed to get task config
=> BAU Get pay-ci in staging connector smoke test job

ci/tasks/pact-provider-test-preflight-check.yml, ci/tasks/pact-provider-verification.yml, ci/tasks/publish-pacts.yml
For provider pact tests to run on PRs they need to be able
to pull down master/main versions of consumer contracts.
However since some time in autumn last year we have not been
tagging contracts with main/master on concourse pact broker
(for reasons to do with abandonment of PaaS migration).
This PR moves all provider pact testing gubbins to point at
the 'old' pact broker, and uses master tag (as that is what
we use in old pact broker world).
This should work...
=> Fix PR pact things

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml, ci/tasks/create-notification-snippets.yml
- Made the Fargate element less shouty (but still a bit shouty), and linked the text rather than printing the URLs in full
- Removed the sidecar version info for 'start' and 'success' builds. People can always click on the build if they want to see the telegraf/nginx versions etc. 
- Converted full URLs to linked descriptive text where possible
These changes have been applied to the test, staging and production deploy pipelines - see `#govuk-pay-announce` and `#govuk-pay-activity` for examples.
Not done, but that we might want to consider in future:
- different green emojis for the different types of success announcement (deploys, smoke tests, pact tests)
=> BAU: Condense slack notifications

ci/pipelines/deploy-to-test.yml
Fix copy and paste error and change adminuers -> connector in
connector's smoke test job.
=> BAU Correct app name in connector smoke test

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml
Previously, triggering a new release (e.g `release-123`) in Concourse before a previous release (`release-122`) had finished caused the newer release to fail (as the newer job can't acquire the terraform lock). We don't want more than 1 release at once anyway, so adding `serial: true` ensures releases happen one after the other.
I've tested this on `deploy-to-test` pipeline already and it works: newer releases are shown as pending (grey) with the message `'checking max-in-flight is not reached'` until the previous release has finished, after which they continue as normal. 
Once this PR is approved and merged, I'll apply to the `deploy-to-staging` and `deploy-to-production` pipelines.
=> PP-8011 Deploy apps, one release at a time

ci/pipelines/deploy-to-test.yml
Copy/paste error where the products smoke test job was trying to find the ledger ECR image. This was just on the `deploy-to-test` pipeline, the staging and production pipelines are fine.
See error message on [Concourse run #28](https://cd.gds-reliability.engineering/teams/pay-dev/pipelines/deploy-to-test/jobs/smoke-test-products/builds/28). Tested on [Concourse run #29](https://cd.gds-reliability.engineering/teams/pay-dev/pipelines/deploy-to-test/jobs/smoke-test-products/builds/29).
=> BAU: Fix ECR registry var file

ci/pipelines/deploy-to-production.yml
Small fixes for smoke tests on the production pipeline (already applied, in order to test them):
- Use the production ECR tag instead of the staging ECR tag on smoke test jobs (all apps):
- Example fix for Frontend: compare [error build #5](https://cd.gds-reliability.engineering/teams/pay-deploy/pipelines/deploy-to-production/jobs/smoke-test-frontend-on-prod/builds/5) with [success build #6](https://cd.gds-reliability.engineering/teams/pay-deploy/pipelines/deploy-to-production/jobs/smoke-test-frontend-on-prod/builds/6)
- Adminusers smoke tests: add in missing `application_image_tag` var
- Compare [error build #24](https://cd.gds-reliability.engineering/teams/pay-deploy/pipelines/deploy-to-production/jobs/smoke-test-adminusers-on-prod/builds/24) with [success build …
=> BAU: fix slack notifications on deploy-to-prod pipeline

ci/scripts/run-ecs-db-migration.js
At some point the `ledger_db_migration` task changed the name of the `TAG` environment variable to `APPLICATION_IMAGE_TAG` (see https://github.com/alphagov/pay-ci/blob/master/ci/pipelines/deploy-to-test.yml#L1488).
This PR fixes the migration script which now uses the new variable name.
Tested this on the `deploy-to-test` Concourse pipeline using this branch - [the task is now passing](https://cd.gds-reliability.engineering/teams/pay-dev/pipelines/deploy-to-test/jobs/ledger-db-migration/builds/23).
=> PP-7918: Fix application tag variable name

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml
Copies the [DB migration task from the `deploy-to-test` pipeline](https://github.com/alphagov/pay-ci/blob/master/ci/pipelines/deploy-to-test.yml#L1453) into the staging and production pipelines.
We seem to use `prod` instead of `production` on Concourse config, so I've kept to that naming for now.
The DB migration tasks should be manually triggered.
I've tested the [staging config on Concourse](https://cd.gds-reliability.engineering/teams/pay-deploy/pipelines/deploy-to-staging/jobs/ledger-db-migration-staging) and it's passing with the no-op as expected. Once this PR is merged the production config will be updated.
=> PP-7918 Ledger DB migration tasks for staging and production

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml
Adds the task to run Connector DB migrations for the staging and production pipelines, exactly as per the [Ledger PR](https://github.com/alphagov/pay-ci/pull/485).
I've applied to the `deploy-to-staging` and have done a no-op run of the job.
Merging this PR will add the job to the `deploy-to-production` pipeline.
=> PP-7919 Connector DB migration tasks for staging and prod

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml
While testing a new telegraf image, the deploy jobs for the test environment all started at once, and the Concourse container count was exceeded.
Let's put the application deploy jobs into a `serial_group` to force each deploy to happen sequentially. Any deploy job with the `deploy-application` tag will not begin until the other job in progress has finished.
Already tested this on the `deploy-to-test` pipeline in Concourse.
Paired with @danworth
=> PP-8107 serial groups for deploy jobs

ci/pipelines/pr.yml, ci/tasks/java-package.yml, ci/tasks/java-tests.yml
- maven:3.8.1 image currently used is based on java version [`16.0.1`](https://hub.docker.com/layers/maven/library/maven/3.8.1/images/sha256-1ffe2b51b6762b94590a1149cf0c35a169203d467dc34891be1439ad3b54940e?context=explore) which breaks few tests (connector) and we currently use java version 11 everywhere. Use maven image using adoptopenjdk-11 instead.
=> PP-7967 Use jdk-11 maven image

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml
Moves the PublicAuth DB migration job to Concourse (our final one of these 🎉 ). Tested the pipeline config on staging, merging this PR will apply the config on production pipeline.
I've also standardised the naming of the Adminusers DB migration job so it's consistent with the others.
This story also covers adding a Slack notification to DB migration jobs - I'll handle that in a separate PR.
=> PP-7922 PublicAuth DB migration job

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml
Pay developers have kindly requested that we add automatic Slack notifications when a DB migration job is triggered, to save them having to post in Slack manually.
- Concourse can't determine the result of a DB migration, so we don't need success/failure snippets like we have for the release jobs. This means we can hardcode a single snippet and don't need to use the `create-notification-snippet.yml` bash script.
- I've set test, staging and production to all put notifications in `#govuk-pay-announce` (as opposed to `#govuk-pay-activity`) as DB migrations are important to know about but rare enough to not cause too much noise. 
- However [I did test this change on the new publicauth DB migration job](https://cd.gds-reliability.engineering/teams/pay-dev/pipelines/deploy-to-test/jobs/publicau …
=> PP-7922 Slack notifications for DB migration jobs

ci/pipelines/deploy-to-test.yml, ci/scripts/wait-for-deploy.js, ci/tasks/deploy-carbon-relay.yml
Deploy carbon-relay to the test environment. A notable change in this commit
would be for the the `ci/scripts/wait-for-deploy.js` file which was amended to
make it work with carbon-relay. As carbon-relay has no `APPLICATION_IMAGE_TAG`,
`NGINX_IMAGE_TAG`, or `TELEGRAF_IMAGE_TAG` these parameters are now made
optional.
This commit does not include the creation of notification snippets, the
checking that we aren't deploying an older version or pushing the image to
staging ECR. These will be done in a future PR.
Example of a successful deploy: https://cd.gds-reliability.engineering/teams/pay-dev/pipelines/deploy-to-test/jobs/deploy-carbon-relay/builds/14.
=> PP-8162: Deploy carbon-relay to test env

ci/pipelines/deploy-to-test.yml
The team are in agreement that just like for the
nginx/nginx-forward-proxy/telegraf deploys, we only need failure notifications
for carbon-relay deploys.
Contrary to the PR name (with "check-release-version") I've decided to go for a small commit here and do that functionality in another commit.
Example of a successful build: https://cd.gds-reliability.engineering/teams/pay-dev/pipelines/deploy-to-test/jobs/deploy-carbon-relay/builds/21.
Example notification: https://gds.slack.com/archives/CNZFSNM0S/p1624875712015800
=> PP-8162: Create failure notification snippet

ci/pipelines/deploy-to-test.yml, ci/scripts/check-release-versions.js, ci/tasks/check-release-versions.yml
Example build to show this is working: https://cd.gds-reliability.engineering/teams/pay-dev/pipelines/deploy-to-test/jobs/deploy-carbon-relay/builds/26
Example build to show the deploy hasn't been broken: https://cd.gds-reliability.engineering/teams/pay-dev/pipelines/deploy-to-test/jobs/deploy-carbon-relay/builds/26
=> PP-8162: Don't allow a deploy of an older carbon-relay version

ci/pipelines/deploy-to-test.yml
Push to staging ecr if the deploy was successful.
Example of a successful build: https://cd.gds-reliability.engineering/teams/pay-dev/pipelines/deploy-to-test/jobs/push-carbon-relay-to-staging-ecr/builds/1. It can be seen that carbon-relay `2-carbon-relay-release` is in the staging ecr repo.
=> PP-8162: Push carbon-relay image to staging ecr

ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml, ci/tasks/deploy-carbon-relay.yml
[Successful deploy of carbon-relay to staging](https://cd.gds-reliability.engineering/teams/pay-deploy/pipelines/deploy-to-staging/jobs/deploy-carbon-relay/builds/6) followed by a [push of the 2-carbon-relay-release to prod ecr](https://cd.gds-reliability.engineering/teams/pay-deploy/pipelines/deploy-to-staging/jobs/push-carbon-relay-to-production-ecr/builds/1).
This commit also introduces an STUNNEL_IMAGE_TAG environment variable. This [build](https://cd.gds-reliability.engineering/teams/pay-dev/pipelines/deploy-to-test/jobs/deploy-carbon-relay/builds/27) verifies the deploy-to-test pipeline still works.
=> PP-8162: Deploy carbon-relay to staging and push to prod ecr

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml, ci/tasks/create-carbon-relay-notification-snippets.yml
[Success notification](https://gds.slack.com/archives/CEBPUR2JE/p1624962960017200) for deploy of carbon-relay to test.
[Success notification](https://gds.slack.com/archives/CAEN2AVLP/p1624963353004100) for deploy of carbon-relay to staging.
There are no start notifications for deploys to test.
[Start notification](https://gds.slack.com/archives/CAEN2AVLP/p1624963916004300) for deploy of carbon-relay to staging.
=> PP-8162: Create start/success notifications for deploys

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml
Carbon-relay is now deployed when a new stunnel image is detected. 
deploy-carbon-relay job on test: https://cd.gds-reliability.engineering/teams/pay-dev/pipelines/deploy-to-test?group=carbon-relay
deploy-carbon-relay job on staging: https://cd.gds-reliability.engineering/teams/pay-deploy/pipelines/deploy-to-staging?group=carbon-relay
deploy-carbon-relay job on prod: https://cd.gds-reliability.engineering/teams/pay-deploy/pipelines/deploy-to-production?group=carbon-relay
The deploy-carbon-relay job on test and staging push new images of stunnel to the staging ECR and prod ECR respectively. The 1-stunnel-release image, pushed from the test ECR can be seen in those ECRs.
=> PP-8162: Deploy carbon-relay on detection of new stunnel image

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml
Running only one deploy job at any point in time will help concourse to not
fall over.
=> PP-8162: Add deploy carbon-relay jobs to serial groups

ci/pipelines/deploy-to-production.yml
At the moment we are of the opinion that carbon-relay shouldn’t be continuously
deployed into staging/production because we don’t have smoke tests that cover
whether or not app metrics are being sent. That said, we don’t send app metrics
from test-12 so it has to go into at least staging before one could make an
assessment. Therefore we are leaving `trigger: true` on staging, whilst
deployment to prod will have to be manually triggered.
=> PP-8162: Deployment to prod should be a manual process

ci/pipelines/deploy-to-test.yml, ci/tasks/pull-image-from-dockerhub.yml
Notifications is being built by Jenkins CI which pushes it into
Dockerhub as per the other apps. This Job triggers on releases in
pay-notifications github repo, pulls the image from Dockerhub and pushes
into ECR. This is the same pattern we have for the other apps built by
Jenkins CI until we move the build somewhere else.
This has been applied and its works:
https://cd.gds-reliability.engineering/teams/pay-dev/pipelines/deploy-to-test/jobs/push-notifications-to-test-ecr/builds/7
```
gds5062-2:pay-ci danworth$ aws-vault exec test -- aws ecr list-images --repository-name govukpay/notifications | jq '.imageIds[] | select(.imageTag == "45-release")'
{
"imageDigest": "sha256:61547264b871bbc787dd3ac3e4db964b5f485ea8e829d6b8615b0a496ffbfc9b",
"imageTag": "45-release"
}
```
=> PP-8105 Add Notifications Docker to ECR Job

ci/pipelines/deploy-to-test.yml
Adds a job to deploy notifications app, run smoke tests and then push
the image into staging ecr. This follows the existing pattern with a
slight change in the deploy task. Since the notifications app consists
of a single container it doesn't lend itself to reusing existing deploy
yaml files so instead it has been in-lined. Since this is specific to
the notifications app and its a simple bit of bash there it isn't worth
putting this into a yaml file for re-use at this time.
This has been applied to `deploy-to-test` pipeline to confirm it works...and it does https://cd.gds-reliability.engineering/teams/pay-dev/pipelines/deploy-to-test?group=notifications
```
gds5062-2:pay-ci danworth$ aws-vault exec staging -- aws ecr list-images --repository-name govukpay/notifications | jq '.imageIds[] | …
```
=> PP-8105 Add Deploy Notifications Job

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml
This adds a deployment pipeline for Notifications into `pay-deploy` `deploy-to-staging` and `deploy-to-production`. This has been applied to test the configuration and has passed on both pipelines.
staging: https://cd.gds-reliability.engineering/teams/pay-deploy/pipelines/deploy-to-staging?group=notifications
production: https://cd.gds-reliability.engineering/teams/pay-deploy/pipelines/deploy-to-production?group=notifications
Confirmed that the running task definition in staging and prod is using `45-release` as deployed by Concourse (I have manually tested using `0-release`)
```
gds5062-2:scripts danworth$ aws-vault exec staging -- aws ecs describe-task-definition --task-definition staging-2_notifications_FG | jq '.taskDefinition.containerDefinitions[].image' …
```
=> Pp 8105 concourse notifications

ci/pipelines/deploy-to-test.yml, ci/tasks/pull-image-from-dockerhub.yml
Rather than list many different git-release resources and have each one
optional this uses the `input_mapping` feature so that the common script
does not need to know about all of the different git-release resources.
This will make adding new jobs simpler and avoid developers having to
know about the need to update the `pull-image-dockerhub.yml` script.
Temporarily applied this and tried it out on toolbox which worked: https://cd.gds-reliability.engineering/teams/pay-dev/pipelines/deploy-to-test/jobs/push-toolbox-to-test-ecr/builds/204
and with Notifications: https://cd.gds-reliability.engineering/teams/pay-dev/pipelines/deploy-to-test/jobs/push-notifications-to-test-ecr/builds/9
=> PP-8166 Refactor to use input mappings

ci/pipelines/deploy-to-test.yml
This will trigger when a new release is created for the tpc-proxy, pull
the image form Docker hub and push into test ECR, just like we for the
other images being built by Jenkins.
Applied to `deploy-to-test` pipeline and it works: https://cd.gds-reliability.engineering/teams/pay-dev/pipelines/deploy-to-test/jobs/push-tcp-proxy-to-test-ecr/builds/1
=> PP-8166 Add Docker to ECR for tcp-proxy

ci/pipelines/deploy-to-test.yml
As part of the Inputting Mapping refactor, adminusers was inadvertently mis-typed. This fixes it in order to fix the adminusers pipeline.
=> [PP-8166] FIX: Adminusers Input Mapping Typo.

ci/pipelines/deploy-smoke-tests.yml
This has been applied at https://cd.gds-reliability.engineering/teams/pay-deploy/pipelines/deploy-smoke-tests/jobs/update-canaries-for-test-environment/builds/19.
=> PP-8413: Update terraform version

ci/scripts/run_smoke_test.js
The 'fetching error info from S3' functionality has never worked - having a link to the right place in the AWS console should be a better experience for developers.
This also addresses the UnhandledPromiseRejectionWarning from https://cd.gds-reliability.engineering/teams/pay-deploy/pipelines/deploy-to-staging/jobs/smoke-test-frontend-on-staging/builds/66. 
Simplifying the code within the `deploymentChecker` loop (which is still needed to check the result of the canary run) means the unhappy path should now reach the `process.exitCode = 1` instead of looping forever.
=> PP-8548: Replace functionality to retrieve S3 errors with link to Canary dashboard

ci/pipelines/deploy-to-production.yml
Frontend has an Nginx forward proxy and the smoke tests should run
whenever this is updated in production, just as they do when deploying
to staging.
This will bring the `deploy-to-production` pipeline in line with `deploy-to-staging` pipeline
Staging triggers for running smoke tests post frontend deployment
```
gds5062-2:pay-ci danworth$ fly -t pay-deploy gp -p deploy-to-staging --json | jq '.jobs[] | select(.name == "smoke-test-frontend-on-staging").plan[] | try select(.trigger == true)'
{
"get": "frontend-ecr-registry-staging",
"passed": [
"deploy-frontend-to-staging"
],
"trigger": true
}
{
"get": "nginx-forward-proxy-ecr-registry-staging",
"passed": [
"deploy-frontend-to-staging"
],
"trigger": true
}
```
Validates ok
```
gds5062-2:pay-ci danworth$ fly -t pay-deploy vp -c …
```
=> PP-8455 Run smoke tests when nginx-forward-proxy image is updated

ci/pipelines/deploy-to-test.yml, ci/tasks/create-egress-notification-snippets.yml, ci/tasks/deploy-egress.yml
> **WIP**: Until instructed otherwise, do not run this, and do not merge this. Commentary is welcome, however!
This sets the foundations for the Pay Egress proxy to be deployed via Concourse CI, allowing us to decommission the Jenkins Deploy instance.
=> [PP-8167] (WIP) Concourse Pipeline for Egress Proxy

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml
The stripe with and without 3ds canaries are now working and should be
run post deployment to test, staging and production.
The config validates with `fly validate-pipeline`
```
gds5062-2:pay-ci danworth$ fly -t pay-deploy vp -c ci/pipelines/deploy-to-production.yml
looks good
gds5062-2:pay-ci danworth$ fly -t pay-deploy vp -c ci/pipelines/deploy-to-staging.yml
looks good
gds5062-2:pay-ci danworth$ fly -t pay-deploy vp -c ci/pipelines/deploy-to-test.yml
looks good
```
=> PP-8513 Add stripe smoke tests post deploy

ci/pipelines/deploy-to-production.yml
This canary is stuck in "starting" and we are waiting on a response from
AWS since all attempts to revive it have failed.
This is temp, the test passes locally and we'll reinstate this once its unstuck.
```
UNKNOWN:pay-smoke-tests danworth$ aws-vault exec deploy -- node run-local/index.js --env production --test make-card-payment-worldpay-with-3ds --headless
Running make-card-payment-worldpay-with-3ds
Going to create a payment to worldpay
Going to get page https://www.payments.service.gov.uk/secure/3527a98f-c80e-4537-879d-56eab0025412
Finished entering card details and confirmed
Payment status is success
```
=> BAU Temporarily disable card worldpay 3ds production

ci/pipelines/deploy-to-production.yml
The problematic canary seems to have sorted itself out, so add back to pipeline.
=> BAU Reinstate dodgy smoke test

ci/docker/terraform/Dockerfile
Found during the Dockerfile review. This particular image was introduced in [49a32d0](https://github.com/alphagov/pay-ci/commit/49a32d05e0cd379e788d1824882a6df217d0f823#diff-21e072aa0ca4d97577a6d94c19ec3ae36ac8f49d0e5858f3b8c9a25892af7ae2) when first creating the deploy pipelines, but was shortly replaced with the Hashicorp terraform resource in [d00bd0c](https://github.com/alphagov/pay-ci/commit/d00bd0c87e639ef0f4e1d543e4afc623a7dacb43#diff-21e072aa0ca4d97577a6d94c19ec3ae36ac8f49d0e5858f3b8c9a25892af7ae2).
=> PP-8511: Remove unused terraform-runner Dockerfile

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml, ci/tasks/assume-role.yml, ci/tasks/check-release-versions.yml, ci/tasks/run-smoke-test.yml, ci/tasks/wait-for-deploy.yml
The `node-aws-sdk-runner` image was renamed `node-runner` in [3550219](https://github.com/alphagov/pay-ci/commit/3550219db9247c44d07be7ba9fe1a0aab457e639#diff-f3983b37267a01991abeeac0e00d76bc33745465692a5be69bd638c435193003) when we added the `octokit/rest` npm package, but not all the usages were updated.
Given we're not managing the old version of the image anywhere, we should update these usages to the new one:
- DB migration running scripts on each pipeline (tested this out on Ledger test-12 DB migration task ✅ )
- Assume Role task
- Check Release Versions task
- Run Smoke Test task
- Wait For Deploy task
=> PP-8511: Use node-runner instead of node-aws-sdk-runner

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml
These have been removed as part of the Smartpay shutdown.
Already applied in the deploy-to-test pipeline.
=> PP-8729: Remove Smartpay post-deploy canaries

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml, ci/tasks/deploy-app.yml, ci/tasks/deploy-carbon-relay.yml, ci/tasks/deploy-egress.yml, ci/tasks/deploy-frontend.yml
We've upgraded the deploy terraform in pay-infra, which is now running on 0.14.11.
This PR upgrades the Concourse pipelines to do the same (fetching the registry image from hashicorp/terraform).
=> PP-8711: Upgrade terraform version to 0.14.11

ci/pipelines/deploy-smoke-tests.yml
Fixes the resource check error we were seeing: `illegal base64 data at input byte 2`
Github recently changed their Graphqa release formatting behind the scenes (see https://github.com/concourse/github-release-resource/pull/107). The fix has been pushed for the Concourse `github-release-resource`, but this is not available in the version of Concourse that BigConcourse is currently running (v7.2.0). Given it may be 'a while' before BigConcourse reaches 7.5.0+, we can instead pin to the version of the resource repo that contains the fix, and specify this as a `resource_type`.
The naming of the resource type is a bit clumsy but I want it to be clear that this is a version of the resource, not the bleeding edge of the repo. Suggestions for a better name welcome.
[Tested this on the pipeline …
=> PP-8729: Fix github release resource

ci/pipelines/deploy-smoke-tests.yml, ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml, ci/tasks/deploy-app.yml, ci/tasks/deploy-carbon-relay.yml, ci/tasks/deploy-egress.yml, ci/tasks/deploy-frontend.yml
Terraform is being upgraded to 1.0.8 for all microservices in PR https://github.com/alphagov/pay-infra/pull/3313
This PR needs to be merged prior to https://github.com/alphagov/pay-infra/pull/3313 is applied to enable deploys to continue.
=> PP-8711: Upgrade to terraform 1.0.8

ci/docker/concourse-runner/Dockerfile
Add aws-cli to concourse-runner docker image
```
cd ci/docker/concourse-runner
docker build -t concourse-runner:local-master .
```
=> PP-8890: Add aws-cli to concourse-runner docker image

ci/pact_broker/pay-pact-broker_manifest.yml, ci/pipelines/pact-broker.yml
The old manifest details refer to a concourse-specific pact broker app that isn't currently running. Change the app/DB name/routes to point to the current app, and adjust the memory/instances/quota to match the current app.
The `PACT_BROKER_BASIC_AUTH_*` vars are used by the [pact-broker docker image](https://github.com/DiUS/pact_broker-docker/blob/cc4273c6ea49a59af183cd6e63b6c9b98f78ce90/container/etc/nginx/main.d/pactbroker-env.conf). I don't think we need a read-only version of the creds (and we don't have these stored in our usual place anyway).
The current app doesn't have a public healthcheck endpoint - it uses `process` instead.
=> PP-8773: Use manifest for current pact-broker app

ci/pipelines/pact-broker.yml
I thought we'd changed the default branch on this repo from `master` to `main`, but we haven't yet 🤦‍♀️
=> PP-8773: Change branch back to master for pact-broker pipeline

ci/docker/concourse-runner/Dockerfile
Install docker-compose from the main repo, the version is high enough that it doesn't need to come from edge anymore.
This whole container really needs updating and having some tests written around it to make updating it safer, but for now we will get it working like this and can schedule that task along with the normal planning.
The version from the edge apk repo isn't looking in the right place for installed python modules so running docker-compose just shows it can't find any python modules.
```
docker built -t concourse-runner:test .
docker run --rm -ti concourse-runner:test docker-compose help
```
=> BAU: Fix docker-compose in concourse-runner container

ci/pipelines/pr.yml
Limit pr-ci tests.
The tests for the pr-ci pipeline have been failing since before I started, this means they are always ignored and any new potential issues are not flagged. In #553 I fixed all the shellcheck errors, this still leaves us with pipeline validation fails. The tool used to do this test is called pipecleaner and is a gds written tool. It doesn't have the ability to say treat warnings as ok, any warning causes a failure.
To make the tests there are more useful, and to make new shellcheck failures actually get flagged and noticed I've changed the validation to just use fly validate for the pipeline yaml files, this does print out some deprecations but they are not treated as an error, and use pipecleaner to validate the individual task yamls which all pass already.
In theory …
=> BAU: Limit pr-ci tests so they pass and are not ignored

ci/pipelines/deploy-to-test.yml
Using the latest stable version of the resource may help address some issues
we've seen with jobs not triggering correctly.
=> PP-8979: Use concourse/registry-image-resource v1.4.1

ci/pipelines/deploy-to-test.yml
Spotted two typos - one for `products` smoke test (appearing as `ledger` in Slack) and one for `products-ui` (appearing as `products` in Slack).
=> BAU: Fix products slack notifications

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml
Notifications sandbox smoke tests have been run:
https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/deploy-to-staging/jobs/smoke-test-adminusers-on-staging/builds/35.1
https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/smoke-test-adminusers/builds/37.3
https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/deploy-to-production/jobs/smoke-test-adminusers-on-prod/builds/33.1
=> PP-9000: Add notifications sandbox smoke test to post deploy tests

ci/pipelines/node-runner.yml
Merging this means any changes to `ci/docker/node-runner/` will be built, tagged with "latest" and be used by all builds.
The node-runner image is tagged with "latest". The node-runner image was originally tagged with "1-release_2022-01-05" which works (for a [deploy](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/deploy-frontend/builds/35) and [smoke test](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/smoke-test-toolbox/builds/27.1) - see task "print-node-runner-version" which comes from https://github.com/alphagov/pay-ci/pull/564) but given there are no automated tests for upgrading the node runner we might actually want to keep the tag at "1-release_2022-01-05" - this would introduce a manual step …
=> PP-8980: Node runner pipeline

.github/dependabot.yml
Unfortunately I don't believe the "directory" param in the dependabot config is
recursive at the moment so we'll have to specify each directory.
I've also ignored ci/docker/pact_with_jq as there's no build process for it at
the moment.
=> bau: Configure dependabot for Docker containers

ci/pipelines/pr.yml
Connector and ledger PR builds contain a 'pact-provider-verification' job, in
addition to a 'pact-provider-test' job which other app PR builds have. This is
because connetor and ledger are both consumers and providers in the pact world.
The 'pact-provider-verification' job actually runs pact provider tests where
they are the consumer. This PR gives clarity to this purpose. We also set the
context as 'app-as-consumer pact verification' which is used by the GitHub PR
as an additional check.
Naturally, we could clarify the 'pact-provider-test' job and rename it to
'app-as-provider pact verification' but that will come in another PR.
Test builds which demonstrate this:
https://github.com/alphagov/pay-connector/pull/3397
https://github.com/alphagov/pay-ledger/pull/1579
=> PP-9096: Clarify the job formerly known as 'pact-provider-verification'

ci/pipelines/pr.yml
Given we have renamed the `<app>-pact-provider-verification` job to
`<app>-as-consumer-pact-test` (see
https://github.com/alphagov/pay-ci/pull/567), it makes sense to rename
`<app>-pact-provider-test` to `<app>-as-provider-pact-test` for clarity.
=> PP-9096: Rename <app>-pact-provider-test job

ci/pipelines/deploy-smoke-tests.yml, ci/tasks/stop-canaries.yml
We've had trouble updating the canaries in the deploy-smoke-tests pipeline. A
typical error:
```
│ Error: error updating Synthetics Canary (card_wpay_3ds2ex_test): ConflictException: Canary is in a state that can't be modified: ERROR
```
We've found that manually stopping the canaries first unblocks the pipeline, so
that's what we're doing in this PR.
In the interests of small PRs, this PR is for update-canaries-for-test-environment only. Staging and prod will be in another PR.
Example build: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/deploy-smoke-tests/jobs/update-canaries-for-test-environment/builds/21
=> PP-9002: Stop all running canaries before updating them

ci/pipelines/deploy-to-test.yml
First step to creating pipeline for webhooks.
This is currently just the deploy job.
It will be triggered by manual pushes to
ECR for now. I have not included other
jobs (pushes to ecr, smoke tests) as they
will not currently work.
For deploy job itself I have removed
pact tagging and release version checking
to allow any manual tag to be deployed.
I have added a different variant to the
webhook ecr resource. This means it will
look for images of type 123-test_release.
This means we won't pollute the world
with dodgy release numbers when doing
manual testing, and can switch to
standard format when these release
numbers are coming from github.
=> PP-9107 Add webhooks deploy to test job

ci/pipelines/deploy-smoke-tests.yml, ci/tasks/check-canaries-in-error-state.yml, ci/tasks/stop-canaries.yml
We currently require canaries in errored states to be manually recreated by a
person with privileged access. We haven't tested that canaries in the running
state causes a deployment of smoke tests to fail, so the code that stops
canaries if they are running is reverted here.
Builds for this PR:
https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/deploy-smoke-tests/jobs/update-canaries-for-production-environment/builds/8
https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/deploy-smoke-tests/jobs/update-canaries-for-staging-environment/builds/10
https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/deploy-smoke-tests/jobs/update-canaries-for-test-environment/builds/30
=> PP-9002: Check if canaries are in error state

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml
During the deployment process for the egress proxy app we're seeing errors on container shutdown. We want manual oversight of deployments for now.
=> PP-9151: Disable continuous deployment for egress

ci/pipelines/deploy-to-test.yml
Triggers on an appropriately formatted git tag, and then builds jar and
from that the docker image.
This is a pure build step - all tests should have been run prior to this
(except e2e, which is out of scope for now).
Eventually build jar and build image tasks can be extracted, but just
want to leave them in line for now in case we want to fiddle with them
=> PP-9107 Build webhooks job

ci/scripts/assume-role.js
When assume role fails the node script still exits with a success and so the pipeline continues onto the next step.
Given the lack of testing and the importance of this assume-role script I've just added an unhandled promise rejection causing the script to terminate with a failure.
=> BAU: Exit assume-role with failure on unhandled promise rejection

ci/pipelines/infra-drift-detector-higher-envs.yml, ci/pipelines/infra-drift-detector-lower-envs.yml, ci/tasks/check-for-tf-drift.yml
Create pipelines for test, staging, and production which check to see if the bastion plan has any changes.
This will alert us when there is a new ami available since drift will be detected. As a positive side effect we will also see if anyone changes anything without our knowledge.
See https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/infra-drift-detector for the lower-envs file having been applied. Only test-12 will work right now.
There is an accompanying PR to create the role used for this in pay-infra https://github.com/alphagov/pay-infra/pull/3545
This has only been applied in test-12 so the assume-role step will fail right now in all other jobs other than test-12.
=> Pp 9086 check for bastion update

ci/pipelines/infra-drift-detector-higher-envs.yml
The prod account id variable name is prod, not production. This has been applied and works: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/infra-drift-detector/jobs/production-2-bastion/builds/2
=> PP-9086: Fix production account variable name

ci/tasks/endtoend/card/docker-compose.yml, ci/tasks/endtoend/products/docker-compose.yml
In preparation for running end to end tests in CodeBuild it needs to be possible to specify a docker registry which is not dockerhub.
This change allows specifying the env var DOCKER_REGISTRY_URI to use a registry other than dockerhub.
Note the syntax `${DOCKER_REGISTRY_URI:-}` means to default to a blank string if it's unset meaning where it's not set in jenkins/concourse it will continue to use the dockerhub registry.
To test them like jenkins would run them with no env var run them locally (warning, this will take a WHILE (maybe 15 mins+) and will pull several gigs of containers from dockerhub:
```
$ cd ci/tasks/endtoend/card
$ docker-compose up --force-recreate -d
$ endtoend=$(docker ps -aqf "name=endtoend")
$ docker exec ${endtoend} /app/bin/e2e-card
```
Also to see how they run when …
=> PP-9231: Specify docker registry uri for e2e tests

ci/pipelines/codebuild-e2e.yml, ci/tasks/prepare-e2e-codebuild.yml, ci/tasks/run-codebuild.yml
Add a generic task that just executes the run-codebuild script
Add a prepare task specifically to prepare the config needed by run-codebuild to run e2e tests for any project
You can see these tasks in use in this pipeline from my spike PR: https://github.com/alphagov/pay-ci/pull/581/files#diff-005891d8552095a02a99c65c922b140e9d0f5c5a3d2052c17aef93170ceff3a9
And in action in this build of my spike pipeline: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/codebuild-e2e/jobs/frontend/builds/169
=> PP-9231: Add concourse tasks for preparing and running codebuild

.github/workflows/test-run-codebuild.yml, .gitignore, ci/scripts/run-codebuild/.babelrc, ci/scripts/run-codebuild/.npmrc, ci/scripts/run-codebuild/README.md, ci/scripts/run-codebuild/libs/codebuild-runner.js, ci/scripts/run-codebuild/libs/codebuild-runner.test.js, ci/scripts/run-codebuild/libs/executor.js, ci/scripts/run-codebuild/libs/executor.test.js, ci/scripts/run-codebuild/package-lock.json, ci/scripts/run-codebuild/package.json, ci/scripts/run-codebuild/run-codebuild.js
Note: Over 5800 lines of this is the package.lock.json!
Add a script that can be used in a concourse pipeline to execute a codebuild and return logs almost live as the build progesses.
I've also added a workflow to run both a lint check (using standard.js) and unit tests on any changes in the `ci/scripts/run-codebuild` directory.
I've done this in a sub-directory of ci/scripts to isolate it's package from the others allowing me to use aws-sdk v3 among other things and not have dependency pollution between different scripts. I modified the gitignore to ignore node_modules in ci/scripts and all subdirectories.
For information about running it see the README included in this PR.
Also see it in action here: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/codebuild-e2e/job …
=> PP-9231: Add run-codebuild ci script

ci/pipelines/codebuild-e2e.yml
Sadly I forgot to change the branch of pay-ci the example pipeline uses back to master now pay-ci is merged.
This PR just changes that back to master.
You can see a successful run after a set-pipeline here: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/codebuild-e2e/jobs/frontend/builds/179
=> PP-9232: Change branch name to be master, not the spike branch

ci/pipelines/e2e-helpers.yml
The goal here is to replace the existing Jenkins job that does the following:
- searches the pay-infra repo for NAXSI config files
- builds the `reverse-proxy` image from the files in pay-scripts 
- copies the NAXSI files into the nginx config on the image (see [this helper script](https://github.com/alphagov/pay-scripts/blob/master/images/proxy/build-latest-master.sh))
- pushes the image to Dockerhub, for use in end-to-end tests
To replicate this, I've built a new pipeline (that will shortly include builds for some other E2E helper images), `e2e-helpers`. Here's what's included.
Resources:
- `reverse-proxy-src`: i.e. the pay-scripts repo. Changes to the `images/proxy` folder will trigger the pipeline job.
- `pay-infra-src`: i.e. the pay-infra repo. Solely used as a source of NAXSI config …
=> PP-9226: Pipeline to build and push reverse-proxy image to ECR

ci/pipelines/e2e-helpers.yml
Adds a job for building the stubs image into the E2E-helpers pipeline. Using `latest-master` tag for now.
Based on the resources and jobs for reverse-proxy, however we don't need any files from pay-infra for this image.
See a successful run of this job: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/e2e-helpers/jobs/build-and-push-stubs-to-test-ecr/builds/1
Successful E2E test run using the image built by that job: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/pr-ci/jobs/endtoend-products-e2e/builds/98
=> PP-9255: Build+push job for stubs E2E helper image

ci/pipelines/e2e-helpers.yml
Going forward, the new CodeBuild E2E environment will use the `latest` tag for all Pay's images that aren't the candidate image. Our new `stubs` and `reverse-proxy` build jobs will use the `latest` tag for now, and we'll add numbered releases later (as these don't change very often).
Keep `latest-master` for the Dockerhub image tagging, to retain backwards compatibility.
=> PP-9226: Use 'latest' tag for stubs and reverse-proxy ECR

ci/pipelines/e2e-helpers.yml
Based on the resources and jobs for stubs (see https://github.com/alphagov/pay-ci/pull/588).
See successful build of the job here: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/e2e-helpers/jobs/build-and-push-endtoend-to-test-ecr/builds/1
=> PP-9315: Build+push job for the pay-endtoend image

ci/pipelines/e2e-helpers.yml
Add notifications to all the e2e-helper pipeline jobs.
I've put success into #govuk-pay-activity and failures into the starling channel.
Successful runs: 
https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/e2e-helpers/jobs/copy-postgres-11/builds/2
https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/e2e-helpers/jobs/copy-roribio16-alpine-sqs-latest/builds/2
https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/e2e-helpers/jobs/copy-selenium-standalone-chrome-3-141-59-iron/builds/3
Failed runs:
https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/e2e-helpers/jobs/copy-postgres-11/builds/3
https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/e2e-helpers/jobs/copy-roribio16-alpine-sqs-latest/builds/3 …
=> PP-9305: Add notifications to e2e-helper jobs

ci/tasks/parse-release-tag.yml
Add XXX-candidate for a future job (run-frontend-e2e) to be triggered on.
According to
https://github.com/concourse/registry-image-resource#out-push-and-tag-an-image:
```
With additional_tags given in params, the image will be pushed as each tag
listed in the file (whitespace separated).
```
=> PP-9229: Add XXX-candidate tag when pushing image to ECR

ci/docker/concourse-runner/Dockerfile, ci/docker/node-runner/Dockerfile
Update concourse-runner:
1. Bump to latest docker source container (the current one has multiple critical vulns)
2. Remove the things needed to build appmetrics
3. Compress 3 RUN layers into a single layer, the third layer does an rm of the file retrieved in the first RUN, this does mean it's not in the final layer of the image but it's still part of the container at a lower layer so it doesn't reduce the size as 3 layers.
4. We don't need to get some deps from the edge repo anymore since we moved to a later docker container build so just source them from the primary apk repo.
Update node-runner:
1. Bump to node 12.22.10 and alpine 3.15
```
$ cd ci/docker/node-runner
$ docker build -t node-runner:test .
```
```
$ cd ci/docker/concourse-runner
$ docker build -t concourse-runner:test .
```
=> Bau update runners

ci/tasks/endtoend/task.yml
Pin endtoend tests to use the old version of concourse-runner
It appears the endtoend tasks, when run in concourse, do not work using the newer concourse-runner. I have tested all the other pipelines and tasks and they all work. Instead of reverting everything I think it's better to pin just the endtoend tests to the older version of the concourse runner while we update the end to end tests.
It's quite strange since on my local machine and in CodeBuild the endtoend tests run well using up-to-date versions of docker and docker-compose.
A run with this image tag in use for card end to end tests can be seen: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/pr-ci/jobs/card-frontend-card-e2e/builds/11
A run with this image tag in use for products endtoend tests can be …
=> BAU: Pin end-to-end tasks to use concourse-runner:0-release_2022-01-21

ci/pipelines/deploy-to-test.yml, ci/tasks/parse-release-tag.yml
This will give a clearer visualisation of the journey. 
Puts the candidate and release tags into separate files, for use by different `put` jobs (that can be run in parallel).
=> PP-9229: Push to candidate ECR resource

ci/pipelines/deploy-to-test.yml
Add adminusers e2e tests post-push-to-ecr.
You can see it working here: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/run-adminusers-e2e/builds/2
In the run-codebuld-card in that run you can see the config it's running with:
```
{
"projectName": "endtoend-tests-test-12",
"sourceVersion": "vvfUv6.27zgHmpqp5dkQH48PUHNf7NnJ",
"secondarySourcesVersions": {},
"environmentVariables": {
"tag_adminusers": "1091-candidate",
"END_TO_END_TEST_SUITE": "card"
}
}
```
and also that it started up the container with the correct image version:
```
9f6b62d2afd0   <aws-test-registry-uri>/govukpay/adminusers:1091-candidate         "tini -e 143 -- bash…"   About a minute ago   Up About a minute (healthy)   8080-8081/tcp             card_adminusers_1
```
=> PP-9233: Add adminusers e2e tests

ci/pipelines/deploy-to-test.yml
Add adminusers e2e tests post-push-to-ecr.
Example 🟢 build: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/run-selfservice-e2e/builds/5.
=> PP-9233: Add selfservice e2e tests

ci/pipelines/deploy-to-test.yml
Note that running products e2e is not required here.
Example 🟢 build: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/run-cardid-e2e/builds/2
=> PP-9233: Add cardid e2e tests

ci/scripts/run-codebuild/libs/executor.js
This build info is printed at the end of the codebuild, the logging about sending the command to start is printed by the libs/codebuild-runner class at the start of the build.
Remove this inappropriately placed log.
=> BAU: Remove inappropriately placed log line

ci/pipelines/deploy-to-test.yml
While we are developing the new e2e tests it's proving to be noisy, so disable the notifications for now.
=> PP-9338: Disable slack notifications for e2e tests

ci/tasks/endtoend/card/docker-compose.yml, ci/tasks/endtoend/products/docker-compose.yml
When we build PR images we are going to push them to a single ECR repo no matter what the app is (this is to make it easy to expire them when there are a lot, and to not mix the images with the candidate and released images).
This PR allows end-to-end tests to override the repo name for any single app and allow all apps to default to their original repo name
This build had the pipeline set for this branch so was using these docker files: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/run-frontend-e2e/builds/14
=> PP-9338: Allow repo name override per-app in e2e tests

ci/pipelines/deploy-to-test.yml, ci/tasks/prepare-e2e-codebuild.yml
The task is specifically for e2e tests, and in the final design we only need a single codebuild repo and bucket for all e2e tests so we can remove those params and hard code this. This reduces a lot of repetition (of which there is plenty enough already in these yaml files)
There is a build running with this change against this branch here: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/run-frontend-e2e/builds/17
=> PP-9338: Remove need for codebuild project name and bucket for e2e tests

ci/pipelines/pr.yml, ci/tasks/get-pr-build-docker-image-info.yml, ci/tasks/prepare-e2e-codebuild.yml
This PR allows end to end tests to be run on PRs pre-merge.
Changes include:
* Modifying the prepare codebuild task to allow the repository for the app under test to be modified (in order to set it to the pull-request-builds ecr repo)
* Add a task which parses the required information about the build and puts it into files which can be used by an ecr PUT task (and also loaded into the env for later tasks)
* Modify the endtoend-card-e2e job to run in codebuild instead of directly in a concourse container.
Even through YAML anchors are used extensively in this file I've taken the active decision to not use them in this PR. When all of the remaining end to end jobs are changed there will be significantly fewer anchors and the file will be easier to comprehend, if a lot more verbose.
You can …
=> Pp 9338 run pr e2e tests in codebuild

ci/pipelines/pr.yml
1. Change the endtoend e2e tests to run both sets of tests in parallel in a single job. 
2. Change the job name to be generic and not products/card
3. Add status sending without products/card nomenclature
Build pipeline applied:
https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/pr-ci/jobs/endtoend-e2e/builds/2
Looks a lot cleaner too :)
See the build status getting reported correctly:
Pending:
Complete:
An actual working build for endtoend:
https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/pr-ci/jobs/endtoend-e2e/builds/2
=> Pp 9338 change pre-merge endtoend e2e tests to run in codebuild

ci/pipelines/pr.yml, ci/tasks/endtoend/products/docker-compose.yml, ci/tasks/prepare-e2e-codebuild.yml
This PR changes the final set of e2e tests, I had no choice but to remove the unused resources since the pre-commit checks fail with a pipeline that has unused resources.
With products ui the project name is products-ui but env vars can't have hyphens, and in the docker-compose files they are already listed with the hyphens so I amended the prepare-codebuild task to remove any hyphens for use in env var names.
A working build can be seen in https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/pr-ci/jobs/products-ui-e2e/builds/4
If you expand the task `prepare-codebuild` you can see the env var renaming was successful:
Additionally if you look in the run-products-e2e-tests output after the pull is complete you can see the products-ui container running with the correct …
=> Pp 9338 change products UI e2e tests to codebuild

ci/pipelines/pr.yml
Now all e2e tests run in codebuild lets remove the serial group!
=> PP-9338: Remove serial group lockout for pre-merge e2e tests

ci/pipelines/pr.yml
1. Rename groups that had the e2e test type to just the app name (e.g. card_frontend to be frontend)
2. Organise the groups so they are listed as apps in alphabetical order, and then helper "things" in alphabetical order, this reflects the ordering of the deploy-to-* pipelines.
Before:
After:
=> BAU: Make pr pipeline group name more human friendly

ci/tasks/endtoend/zap/docker-compose.yml, ci/tasks/prepare-e2e-codebuild.yml
It seems like adding the following to the docker-compose was all that's needed
to run the zap endtoend tests locally:
```
zap:
image: ${DOCKER_REGISTRY_URI:-}${repo_zap:-govukpay/zap}:${tag_endtoend:-latest}
command: "-Xmx2G"
networks:
pymnt_network:
aliases:
- zap.pymnt.localdomain
logging:
driver: "json-file"
```
To run locally, add the following script to ci/tasks/endtoend/zap:
```
#!/bin/bash
export END_TO_END_JAVA_OPTS="-Xms1G -Xmx2G"
export HTTP_ZAP_ENABLED=true
docker-compose up -d --no-recreate
echo "Sleeping to allow everything to come to life"
sleep 10
docker ps -a
endtoend=$(docker ps -aqf "name=zap_endtoend")
echo "E2E container id - ${endtoend}"
docker exec "${endtoend}" "/app/bin/zap"
```
and run it from the ci/tasks/endtoend/zap directory.
=> PP-9230: Add configurations for running zap endtoend tests

ci/pipelines/control-plane.yml
Add a pipeline to restart pay-control-plane.
This includes automatically restarting every day between 7:00 and 7:30 GMT.
Success notifications into pay-govuk-activity
Failure notifications into pay-starling
Example build: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/control-plane/jobs/restart-control-plane/builds/3
Success notice:
Failure notice:
Events from paas showing restage:
=> BAU: Add a pipeline to restart control plane

ci/pipelines/deploy-to-test.yml
This will:
1. Rename `push-adminusers-to-test-ecr` to `push-adminusers-candidate-to-test-ecr`
3. Require e2e tests before running deploy-adminusers
5. Rename the canididate and latest ecr resources to just `adminusers-(latest|candidate)` I didn't rename the release since that would lose the deploy history and could trigger a redeploy of lots of old versions
New pipeline layout:
https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test?group=adminusers
=> PP-9234: Require e2e tests for adminusers

ci/pipelines/deploy-to-test.yml
This will:
1. Rename `push-cardid-to-test-ecr` to `push-cardid-candidate-to-test-ecr`
3. Require e2e tests before running deploy-cardid
5. Rename the canididate and latest ecr resources to just `cardid-(latest|candidate)` I didn't rename the release since that would lose the deploy history and could trigger a redeploy of lots of old versions
Same change as https://github.com/alphagov/pay-ci/pull/633 but for cardid
New pipeline layout:
https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test?group=cardid
=> PP-9234: Require e2e tests for cardid

ci/pipelines/deploy-to-test.yml
Require end to end tests for connector and frontend.
Added skip_download on the ecr and docker PUT's I added in the previous PRs, saves time and there is no need to pull them given then are the final steps in the jobs.
1. Rename `push-connector-to-test-ecr` to `push-connector-candidate-to-test-ecr`
3. Require e2e tests before running deploy-connector
5. Rename the canididate and latest ecr resources to just `connector-(latest|candidate)` I didn't rename the release since that would lose the deploy history and could trigger a redeploy of lots of old versions
Pipeline after update
https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test?group=connec …
=> Pp 9234 require e2e test for connector and frontend

ci/pipelines/deploy-to-test.yml
Require end to end tests for products and publicapi.
Added skip_download on the ecr and docker PUT's I added in the previous PRs, saves time and there is no need to pull them given then are the final steps in the jobs.
1. Rename `push-Y-to-test-ecr` to `push-Y-candidate-to-test-ecr`
3. Require e2e tests before running deploy-Y
5. Rename the canididate and latest ecr resources to just `Y-(latest|candidate)` I didn't rename the release since that would lose the deploy history and could trigger a redeploy of lots of old versions
Pipeline after update
https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test?group=products …
=> Pp 9234 require e2e test for products and publicapi

ci/pipelines/e2e-helpers.yml
Copy this version in preparation for
https://github.com/alphagov/pay-ci/pull/636.
If it turns out selenium/standalone-chrome:3.141.59 doesn't work with our e2e
tests we can revert this commit.
=> PP-9306: Copy selenium/standalone-chrome:3.141.59 into ECR

ci/pipelines/deploy-to-test.yml
Require end to end tests for products and publicapi.
Added skip_download on the ecr and docker PUT's I added in the previous PRs, saves time and there is no need to pull them given then are the final steps in the jobs.
1. Rename `push-Y-to-test-ecr` to `push-Y-candidate-to-test-ecr`
3. Require e2e tests before running deploy-Y
5. Rename the canididate and latest ecr resources to just `Y-(latest|candidate)` I didn't rename the release since that would lose the deploy history and could trigger a redeploy of lots of old versions
Pipeline after update
https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test?group=products-ui …
=> Pp 9234 require e2e test for products UI and publicauth

ci/pipelines/e2e-helpers.yml
Skip downloading the ECR images again after putting them for all e2e helpers
=> BAU: Don't pull e2e helpers after push

.github/workflows/_run-provider-contract-tests.yml
The pro of having this workflow is that the maven command to run this test is
the same across all our providers.
The cons:
* The providers must be in Java
* The provider project must have a pom.xml which defines a `runContractTests` profile
[adminusers PR](https://github.com/alphagov/pay-adminusers/pull/1287) that proves the use of this workflow.
I've tested that we don't need to pass `-Dpact.provider.version=${commit}` to
the `mvn test -DrunContractTests` command as the pact library will pull out the
latest sha of the provider when publishing the result.
=> PP-9236: Workflow for running a provider contract test

ci/docker/node-runner/Dockerfile, ci/docker/node-runner/Dockerfile.node12, ci/docker/node-runner/Dockerfile.node16, ci/docker/node-runner/README.md, ci/docker/node-runner/source_container_image_versions.json, ci/pipelines/node-runner.yml
UPDATE: Changed to using two dockerfiles to ensure we still get dependabot updates
~* Change node-runner to use a build-arg to decide the source container image version~
~* Include a json file which has the versions we want to use~
* Created separate dockerfiles for node12 and node16 and symlinked Dockerfile to the node12 dockerfile
* Update the node-runner node16 container to set a work-dir (since node-15 if you don't set a workdir npm install doesn't work, an alternative is to `npm install -g ...`)
* Update the node-runner README to explain how to build it locally
* Update the concourse node-runner pipeline to
* run a build for both node12 and node16 
* push node12, node16, and latest tagged images
A working version of this pipeline (which had the push latest disabled so I didn't affect …
=> PP-9373: Build node12 and node16 node-runner images

.github/workflows/test-run-codebuild.yml, ci/tasks/run-codebuild.yml
1. Update run-codebuild to use node16 version of node-runner.
2. Update the workflow to only do node16 unit tests
3. Update the workflow to run on pull-requests where the workflow has changed
=> PP-9373: Update run-codebuild to node16

ci/pipelines/control-plane.yml
https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/control-plane
Adds a build-&-deploy job to the existing Control Plane pipeline:
- new resource: control plane git repo (to checkout and build the image from)
- new resource: control plane dockerhub repo (to be pushed to following the build)
- task: build control plane using `concourse/oci-build-task`
- task: push to dockerhub using tag `latest` (Jenkins currently pushes `latest-master` so this won't conflict)
- task: push to PaaS using the existing cf resource already used by the restart job
- success/failure slack notifications 
At present Jenkins pushes the `latest-master` image to Dockerhub, then applies the `cf push` calling the image _from Dockerhub_, not locally. I've done the same here for now as it's worked …
=> PP-9237 Deploy control plane in Concourse

ci/pipelines/control-plane.yml
Make control plane build also push to ECR for backup of images
Run using this: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/control-plane/jobs/deploy-control-plane/builds/8
=> Pp 9237 add control plane into ecr

ci/pipelines/deploy-to-test.yml
The Slack notifications use the candidate tag.
=> PP-9210: Fix candidate image tag in notifications

ci/pipelines/deploy-to-test.yml
1. Make the webhooks build the same as the other java builds.
2. Add release labels to the built images
3. Add the same notifications as other image builds
=> PP-9213: Standardise the webhooks build

ci/pipelines/deploy-to-test.yml
Build cardid in concourse.
Bonus to make the selfservice gets in parallel
This is slightly different than the other java apps since it has a submodule in a private repo. The release checkout is done with `submodules: none` and then a task is run which actually gets the submodule using https basic auth instead of oath. This code was already written I just changed the image it used from concourse-runner (which is huge) to alpine and did apk add git (as we discovered the other day this is about 2 seconds, instead of around a minute pulling the concourse-runner image).
The whole repo is then copied into cardid-git-release-with-submodules output directory to be passed to later tasks. The later tasks all use this with-submodules version of the repo instead of the plain cardid-git-release repo. …
=> Pp 9213 cardid build

ci/pipelines/deploy-to-staging.yml
Add the starting slack notification to the deploy-notifications-to-staging job.
All other deploy jobs in staging and production pipelines have the correct start notification already.
=> PP-9418: Add start notification to notifications deploy to staging

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml
Allow up to 10 attempts for the Worldpay post-deploy smoke tests before failing. This should reduce noise in the release slack channel and enable more continuous deployment without developer intervention. 
We will still have visibility on continued failures through the scheduled staging smoke tests.
=> PP-9428 Retry Worldpay smoke test failures

ci/pipelines/deploy-to-test.yml, ci/pipelines/e2e-helpers.yml, ci/pipelines/pr.yml
Adds retries for the deploy-to-test, e2e-helpers and pr-ci pipelines.
These retries can be removed once the flaky EPDQ scenario is no longer required.
=> BAU: Allow 3 attempts for flaky card e2e tests

ci/pipelines/pr.yml
These tests are already run on PRs via Github Actions.
=> BAU: Remove stubs tests from PR pipeline

.github/workflows/_run-provider-contract-tests.yml
Set the provider version to either the PR sha, or the master sha
This allows the pact tests to be used during a PR and to set a SHA in the broker that we can actually trace back to a PR.
You can see this in use in https://github.com/alphagov/pay-connector/pull/3555
While we do not need this functionality right this second as part of testing how to do it I think this has become ok to merge and makes it trivial for us to move the other tests later.
=> BAU: Set pact provider version for PRs or Master tests

ci/pipelines/deploy-to-production.yml, ci/tasks/parse-perf-release-tag.yml
Tag image with XXX-perf in test ecr after successful deploy to prod. This is so
a future a job in the pay-dev account can deploy to test-perf environment by
listening on the XXX-perf variant.
🎉  https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/deploy-to-production/jobs/retag-adminusers-image-for-test-perf/builds/3
[1190-perf tag exists in test ECR too](https://eu-west-1.console.aws.amazon.com/ecr/repositories/private/223851549868/govukpay/adminusers?region=eu-west-1).
=> PP-8295: Tag image with XXX-perf for adminusers

ci/pipelines/pr.yml
- Run cardid provider pact tests on connector PR builds and cardid PR builds
- When we checkout cardid master for the connector-as-consumer pact
tests, don't fetch the cardid-data submodule as this isn't required for
pact tests to run.
=> PP-9406 Run cardid provider pact tests on PR builds

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml
Add the check-pact-compatibility step in the deploy-cardid-to-xxxx job on each environment.
Add a cardid-pact-tag job to the deploy pipeline for each environment after running smoke tests.
=> PP-9406 Add pact tasks to cardid deploy pipelines

ci/pipelines/deploy-to-perf.yml
🟢 db migrations can be seen at https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-perf.
This PR follows the pattern set out in https://github.com/alphagov/pay-ci/pull/689.
=> PP-9266: Trigger the rest of the db migrations

ci/pipelines/pr.yml
- add Concourse PR pipeline for the new pact test, where adminusers is the consumer and ledger is the provider. deploy pipelines are already set up for pact tagging.
=> PP-9307 add adminusers - ledger pact test pipeline

ci/pipelines/deploy-to-test.yml
We want to simulate the scheduled canaries on Staging, without the hassle of actually creating the canaries (a bit of a faff).
We can re-use the existing post-deploy Worldpay canaries in test-12, by adding a separate job in the `deploy-to-test` pipeline to trigger those canaries every 5 minutes. This will create enough logs for us to compare to the staging environment.
To emulate the staging scheduled smoke tests as far as possible, I've removed the retries we usually use for the post-deploy jobs. I've also left out the slack notifications to reduce noise.
There may be a small impact on the speed of normal deployments on test-12, as the post-deploy jobs may have to wait in a queue for the scheduled canaries to finish.
=> PP-9624: Temporary pipeline to schedule Worldpay canaries on test-12

ci/pipelines/deploy-to-test.yml
Reverts alphagov/pay-ci#697
This job has now served its purpose - we're confident that the smoke tests are passing consistently.
=> Revert "PP-9624: Temporary pipeline to schedule Worldpay canaries on test-12"

ci/pipelines/deploy-to-test.yml
Concourse pipeline to check the `pay-dockerfiles` repo for
`webhooks_egress_` alpha releases. This will:
- build the dockerfile in the appropriate sub folder
- push the docker image to webhooks egress test ecr
This will also include a step to push to staging ecr (and subsequently
be deployed to staging) when webhooks and webhooks egress are deployed
to the staging environment.
=> PP-9200 Add webhooks egress test pipeline

ci/tasks/scale-fargate-service.yml
Add a task to scale up and down fargate services. This is based on (copy and pasted with a small modification to run the scale command first) https://github.com/alphagov/pay-concourse/blob/main/pipelines/tasks/wait-for-targetgroup-health.yml which has proven to be extremely robust over many months.
Where services are at lower capacity to start with: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/perf-tests/jobs/scale-up-services/builds/4
Where services are already scaled up: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/perf-tests/jobs/scale-up-services/builds/3
See it in action:
Where there are more running tasks than desired: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/perf-tests/jobs/scale-down-services/builds/3 …
=> PP-8337: Add task to scale fargate services

ci/tasks/pause-unpause-pipeline.yml
Add a concourse task to pause and unpause pipelines
When paused it will wait for running jobs to finish before exiting with success.
Note: this is based on https://github.com/alphagov/pay-concourse/blob/main/pipelines/tasks/concourse-land-workers.yml which already performs pipeline actions using fly cli
https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/perf-tests/jobs/scale-down-databases/builds/8
https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/perf-tests/jobs/scale-down-databases/builds/7
=> PP-8337: Add task to pause and unpause pipelines

ci/tasks/start-rds-instance.yml, ci/tasks/stop-rds-instance.yml
Added tasks to:
1. Start an rds instance and wait for it to reach the available state
2. Stop an rds instance and wait for it to reach the stopped state
Where databases were started from a stopped state: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/perf-tests/jobs/scale-up-databases/builds/9
Where databases were already starting: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/perf-tests/jobs/scale-up-databases/builds/8
Where databases were already started: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/perf-tests/jobs/scale-up-databases/builds/10
Where databases were stopped from an available state: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/perf-tests/jobs/scale-down-databases/builds/8
Where …
=> PP-8337: Add tasks to start and stop RDS instances

ci/pipelines/deploy-to-perf.yml
As part of the strategy to run test-perf-1 totally scaled down and only scale up when perf tests run or DB migrations need to happen this starts the db that needs migration and stops it after migration.
You can see in this build that the start db task ran, then after the migration (which fails for unrelated reasons) it stops the DB: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-perf/jobs/adminusers-db-migration-perf/builds/5
=> PP-8337: Start RDS before migration and stop after migration in deploy-to-perf

ci/pipelines/perf-tests.yml
Move the payment simulation to be the first of the 3 simulations run each day.
This gives time for ledger and connector to fully consume any messages that might be on the SQS queues, and also time for the expunge and expiry tasks to complete before scale down.
=> PP-8337: Move payment simulation to be the first test

ci/pipelines/deploy-to-test.yml, ci/tasks/deploy-scheduled-tasks.yml
Terraform deploy the scheduled tasks into test-12.
I want to merge this PR before I do the other envs since this has a task in pay-ci which is needed.
This also requires https://github.com/alphagov/pay-infra/pull/3750
You can see the successful run: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test?group=alpine as well as the correctly formed stream-s3-sqs pipeline: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test?group=stream-s3-sqs
=> Pp 9716 deploy new alpine scheduled tasks to test-12

ci/pipelines/deploy-to-perf.yml, ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml
Deploy scheduled tasks to staging, production and perf env.
I've followed the exact pattern of the other apps and had production add an X-perf tag in test, and then trigger in the deploy-to-perf pipeline to deploy that to test-perf-1.
Note: I also slightly reordered the groups in deploy-to-perf so it matches all the other pipelines (egress in with the microservices, pipeline self-update at the end)
See it in action
alpine: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/deploy-to-staging?group=alpine
stream-s3-sqs: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/deploy-to-staging?group=stream-s3-sqs
alpine: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/deploy-to-production?group=alpine
stream-s3-sqs: …
=> PP-9716: Deploy scheduled tasks in other envs

ci/pipelines/concourse-runner.yml, ci/pipelines/e2e-helpers.yml, ci/tasks/generate-docker-config-file.yml
Enable dockerhub authentication on oci-build-task using the generate-docker-config-file task from EngineerBetter under the MIT license.
Also switch usage of vito/oci-build-task with concourse/oci-build-task
Add a single usage of this on the build-and-push-endtoend-candidate job in the e2e-helpers pipeline to demonstrate it works.
As a test I added a job which creates a dockerfile where the image in the FROM requires authentication. When I didn't provide the DOCKER_CONFIG param you can see the failure requiring authentication in this build: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/e2e-helpers/jobs/test-authenticated-build/builds/1
Once I added the DOCKER_CONFIG param to the oci-build-task you can see the same Dockerfile being built successfully in this build: …
=> PP-9737: Add generate-docker-config-file.yml task from EngineerBetter and use in 1 job as a demo

ci/pipelines/concourse-runner.yml, ci/pipelines/control-plane.yml, ci/pipelines/deploy-to-test.yml, ci/pipelines/e2e-helpers.yml, ci/pipelines/node-runner.yml, ci/pipelines/perf-tests.yml
Following on from https://github.com/alphagov/pay-ci/pull/714 add dockerhub authentication to oci-build-task builds.
reverse-proxy: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/e2e-helpers/jobs/build-and-push-reverse-proxy-candidate/builds/5
stubs: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/e2e-helpers/jobs/build-and-push-stubs-candidate/builds/30
build-and-push https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/node-runner/jobs/build-and-push/builds/7
build-and-push-perf-tests: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/perf-tests/jobs/build-and-push-perf-tests/builds/10
deploy-control-plane: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/control-plane/jobs/deploy …
=> PP-9737: Add docker auth to all oci-build-tasks

ci/pipelines/pr.yml, ci/tasks/build-docker-image.yml
Authenticate for all build tasks in the pr-ci pipeline.
You can see in commit https://github.com/alphagov/pay-ci/commit/63d7cd57d2370f16ae6232f30439218f90695732 where I added the config to test this which ran this build: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/pr-ci/jobs/test-authenticated-build/builds/7 that required authentication (to pull cardid) which succeeded.
=> PP-9737 add docker auth to pr docker image builds

ci/pipelines/perf-tests.yml
Ledger is currently unable to fulfil the requests made by these scenarios. Let's turn off the daily scheduled `SearchPayments` tests until we can address the test settings (or Ledger's settings) properly, and avoid noise in the Slack channel.
We can keep the ad-hoc job that runs `SearchPayments` for now.
~Note for reviewers: I've repeated the explanatory comment due to the large amount of YAML in this file - it's not always easy to determine whether a comment in one place also applies somewhere else in the file, so I've gone for verbosity.~ Ignore this - I've kept the `run-search-payment-simulation-perf-test` in the `all-job` group anyway, so it's only the task in the `scale-and-run-all-simulations` that needs commenting out.
=> BAU: Temporarily disable SearchPayments scenarios

ci/pipelines/deploy-to-staging.yml
For all pipelines on deploy-to-test and for some pipelines on
deploy-to-staging, the `push-x-to-production-ecr` needs the `x-pact-tag`
job to have completed first.
However, for a few apps on the deploy-to-staging pipeline, the
`push-x-to-production-ecr` requires the smoke test task to have
completed. This means that we might push to the production ECR without
tagging the Pact for staging if Concourse gets stuck, which might cause
confusion if we later run across Pact errors.
Fix this so the ordering of tasks across all pipelines is uniform.
=> BAU Run Pact tag task before pushing to ECR

ci/pipelines/deploy-to-test.yml
When the nginx proxy is released currently it gets promoted from test to staging without ever being smoke tested.
Change the nginx-proxy group in deploy-to-test to show the deploys of frontend and products-ui as well as the smoke test jobs for both of these.
Require the passing of both frontend and products-ui smoke tests before promoting the nginx proxy to the staging env.
I did experiment with adding all of the things triggered by an nginx release in test to the view, but that is every service and the view is terrible, this view at least gives us a clear visual of the progress of the container image from release to staging.
You can see the new group at https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test?group=nginx-proxy
=> PP-9741: Display frontend and products-ui and require passing of their smoke tests before push to staging

ci/pipelines/deploy-to-test.yml, ci/tasks/deploy-webhooks-egress.yml
Webhooks egress post merge is tagged as a release prefixed with
""webhooks_egress_" -- this is picked up by a deploy to test pipeline
that currently builds the image and pushes it to test ecr.
Add jobs to deploy this image in the `test-12-fargate` cluster and
subsequently push it to staging ecr to be picked up by a future
pipeline.
=> PP-9211 Add webhooks egress deploy to test and push to staging ecr

ci/pipelines/perf-tests.yml
These simulations have been deleted, see https://github.com/alphagov/pay-perftests/pull/121.
The [scale-and-run-all-simulations job](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/perf-tests/jobs/scale-and-run-all-simulations/builds/33) is passing now.
=> PP-9645: CardIDSimulation and PublicAuthSimulation have been deleted

ci/pipelines/deploy-to-staging.yml
https://github.com/alphagov/pay-ci/pull/720 and https://github.com/alphagov/pay-ci/pull/721 push successful build + deploys to test to the staging environment ecr. Using that as a trigger, deploy these to the `staging-2-fargate` cluster. Additionally add a manual job to run db migrations against webhooks staging.
This follows exact patterns set by existing deploy to test/ deploy to staging pipelines.
---
Add deploy to staging and staging db migration plans to a webhooks
service job.
Smoke tests and any pact tagging will be added by the stories that
include webhooks coverage in those tests.
Add deploy to staging plans to a webhook egress job.
Smoke tests will be added by stories that include webhook coverage in
smoke and end to end tests.
=> PP-9211 Pipelines for webhooks and webhooks egress deploy to staging

ci/pipelines/deploy-to-test.yml
Require build of applications in deploy-to-test before they are deployed.
This helps make the pipelines make more sense and show a joined up pipeline:
From:
To
=> BAU: Require build before deploy

ci/pipelines/control-plane.yml, ci/pipelines/pact-broker.yml
Switch both the pact broker and control plane to zero downtime deploys.
Both of these are simple single app services with no networking rules involved and as such are safe to deploy with this strategy
=> BAU: Change pact broker and control plane to zero downtime deploys

ci/pipelines/control-plane.yml
Making this a zero downtime push requires additional work which we don't have time for at the moment, it's an internal tool which isn't used a lot so a couple of seconds of downtime during deploys seems ok.
=> Revert control plane to push deploy

ci/scripts/run-ecs-db-migration.js
We ran into problems with this as the image tagged 2856-perf-db had not been deployed as an app release (which was still on 2855-perf).
We don't carry out version checks for test-perf-1 deployments elsewhere, as it's low risk given the perf environment should be up to date with production deployments.
The alternative would be some more complex changes to our application deployment script, or an additional app deployment job just for the *-perf-db tagged images (which would probably cause different problems for this check anyway).
=> BAU: Exclude version check from test-perf-1 DB migrations

ci/docker/concourse-runner/Dockerfile
The concourse/concourse-pipeline-resource image has been deprecated and finally failed when the signatures signing the apk indexes have been updated and the new ones are no longer in the final build of this registry image. We (mis)use that resource as a fly cli executor. There is a fly cli resource but that lists it's last compatibility as concourse 5.x.
As such this PR adds the fly CLI installed from our concourse instance, and sha256 sum checked against the known correct sha256 sum.
=> BAU: Add fly cli installed from our own concourse

ci/tasks/pause-unpause-pipeline.yml
Update the pause-unpause pipeline task to use our concourse runner image, now that this includes the fly cli and jq we can also remove the custom install steps for JQ and path setting to get to the fly cli.
=> BAU: Update perf test pipeline to use our concourse runner image

ci/pipelines/pr.yml
While reviewing our [list of non-app Docker images](https://docs.google.com/spreadsheets/d/18by9lu__GVlaijgzy-GBaZheR2HBQK72nqbjR1QxXmE/edit#gid=0), I thought I'd see if the `concourse-s3-resource` image was still being used. The resource that refers to it (`paas-s3`) is present in the PR pipeline, but is not actually being used by anything.
I've also removed the definitions for the following tasks, that are not used anywhere (I think these were used in the old end-to-end tests setup):
- `put-s3-docker-image`
- `put-s3-build`
- `get-local-docker-image`
- `zip-build`
- `put-node-test-failure`
=> BAU: Remove unused resources and definitions from PR pipeline

ci/docker/concourse-runner-with-java-17/Dockerfile, ci/docker/concourse-runner-with-java-17/README.md, ci/docker/concourse-runner-with-java-17/docker-helpers.sh, ci/docker/concourse-runner-with-java-17/docker-wrapper
This is identical to the original
[govukpay/concourse-runner](https://github.com/alphagov/pay-ci/tree/master/ci/docker/concourse-runner)
but with Java 17. The requirement for Java 17 comes from the fact that
[webhooks](https://github.com/alphagov/pay-webhooks) uses it.
Note that docker engine 20.10.17 was originally used but this did not work as dockerd seems to be missing.
This produces a running webhooks integration test: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/pr-ci/jobs/webhooks-integration-test/builds/18.
There will be another PR to add this to concourse runner build.
=> PP-9827: Concourse runner with java 17

ci/pipelines/deploy-to-test.yml
Require the build job to pass before starting the deploy job
=> PP-9829 require build stage to pass before deploying

ci/pipelines/pr.yml, ci/tasks/java-consumer-pact-tests.yml
- Add adminusers-consumer-pact-test job which runs the consumer contract tests to generate the pact files, then publishes them.
- As part of the adminusers-as-consumer-pact-test, run the connector provider contract tests.
- Run both adminusers-consumer-pact-test and adminusers-integration-test before running adminusers-as-consumer-pact-test, as the  adminusers-consumer-pact-test generates and publishes the pacts with  connector as the producer and adminusers-integration-test generates and  publishes the pacts with ledger as the producer. This can be changed in future so that adminusers-consumer-pact-test will generate both.
Test builds:
https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/pr-ci/jobs/adminusers-consumer-pact-test/builds/14 …
=> PP-9292 Run connector provider tests for adminusers PRs

ci/pipelines/pr.yml
We're going to move the ledger consumer tests, which generate the Pact file, to be run as part of the integration test suite.
Wait for ledger-integration-test to pass before running ledger-as-consumer-pact-test as this job needs the pacts to have been published to the broker before running.
=> PP-9292 Run ledger integration tests before consumer tests

ci/pipelines/carbon-relay-ng.yml
This PR adds a build pipeline for the base carbon-relay-ng image.
Efforts are taken to make it as easy as possible to stay up to date with upstream. We are parsing the golang version used to build from the grafana/carbon-relay-ng circleci config.
Despite having already been tested by github this pipeline also runs the tests against the final built container. Considering we are pushing this to a public repository it seems prudent to take the extra care given the container build runs apk upgrade.
A successful run of this pipeline can be seen on concourse https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/carbon-relay-ng/jobs/build-then-test-and-push/builds/4
See the successfully built images in dockerhub: https://hub.docker.com/repository/docker/govukpay/carbon-relay-ng/ge …
=> Pp 9940 build carbon relay ng

ci/pipelines/deploy-to-production.yml
Retag webhooks-egress and webhooks images with perf tags for future deployment to the perf test environment.
Working tasks for this can be seen:
[retag webhooks-egress](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/deploy-to-production/jobs/retag-webhooks-egress-image-for-test-perf/builds/1)
[retag webhooks](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/deploy-to-production/jobs/retag-webhooks-image-for-test-perf/builds/1)
[retag webhooks for db migration](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/deploy-to-production/jobs/retag-webhooks-image-for-test-perf-db/builds/1)
=> Pp 9998 retag webhooks images for perf

ci/pipelines/perf-tests.yml
Add webhooks-rds instances to environment scaling.
This is important to be part of the regular tasks. Otherwise after 7 days the webhooks RDS will be started again by AWS (RDS instances can only be stopped for 7 days continuously and are automatically started after that period) and we will be paying for it continuously. This way we only pay for it for about 40 minutes a day as the perf tests run.
[A successful scale up](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/perf-tests/jobs/scale-up-databases/builds/15)
[A successful scale down](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/perf-tests/jobs/scale-down-databases/builds/10)
=> PP-9998: Add webhooks-rds instances to environment scaling

ci/pipelines/deploy-to-perf.yml
Add in deploy-to-perf:
* Webhooks deployment
* Webhooks db migration
* Webhooks egress deployment
Requires: https://github.com/alphagov/pay-infra/pull/3953
Successful runs can be see in the [webhooks group in the deploy-to-perf pipeline](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-perf?group=webhooks) and the [webhooks-egress group in the deploy-to-perf pipeline](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-perf?group=webhooks-egress)
Notifications to slack:
=> Pp 9998 add webhooks perf deployment

ci/pipelines/perf-tests.yml, ci/tasks/scale-fargate-service.yml
Have perf tests scale webhooks and webhooks-egress scaled for perf tests.
Currently they are set for 0 up and down, but having this means it's easy to change by just adjusting https://github.com/alphagov/pay-perftests/blob/master/ci/scale-service-volumes.yml
I had to allow the target group suffix to be overridden since the webhooks-egress target group exceeded the maximum allowed TG name length and had to be truncated.
Given webhooks relies on webhooks-egress I've also put the scale up and down in an order so that webhooks-egress is alive before webhooks tries to scale (and scaled down in reverse)
Successful scale up: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/perf-tests/jobs/scale-up-all/builds/20
Successful scale down: …
=> Pp 9998 scale webhooks for perf tests

ci/docker/node-runner/Dockerfile.node16
We've seen concourse builds fail with the error
```
selected worker: ip-10-1-11-96
node:internal/modules/cjs/loader:936
throw err;
^
Error: Cannot find module 'aws-sdk'
Require stack:
- /tmp/build/c6eb4761/pay-ci/ci/scripts/assume-role.js
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
at Function.Module._load (node:internal/modules/cjs/loader:778:27)
at Module.require (node:internal/modules/cjs/loader:1005:19)
at require (node:internal/modules/cjs/helpers:102:18)
at Object.<anonymous> (/tmp/build/c6eb4761/pay-ci/ci/scripts/assume-role.js:4:13)
at Module._compile (node:internal/modules/cjs/loader:1103:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
at Module.load (node:internal/modules/cjs/loader:981:32)
at …
```
=> PP-9392: Install npm packages globally

ci/docker/node-runner/Dockerfile.node16
It turns out that https://github.com/alphagov/pay-ci/pull/755 didn't quite do the trick to get the assume-role task within a concourse job working. Upon hijacking the concourse docker container, we found that setting the `NODE_PATH` env variable to `/usr/local/lib/node_modules` enabled a node script to be run from anywhere which resolves our issues.
=> PP-9392: Add NODE_PATH env var

ci/docker/node-runner/Dockerfile, ci/docker/node-runner/Dockerfile.node12, ci/docker/node-runner/README.md, ci/pipelines/node-runner.yml
removed [the symbolic link](https://github.com/alphagov/pay-ci/blob/master/ci/docker/node-runner/Dockerfile) and created a new one to point to Dockerfile.node16 as a default
node12 Dockerfile is removed from pay-ci
[the pay-ci/docker/node-runner README file](https://github.com/alphagov/pay-ci/blob/master/ci/docker/node-runner/README.md) is updated to remove mention of node12
Removed build job for node12 from node-runner.yml
=> PP 10148 remove old node12 version of node runner

ci/scripts/wait-for-deploy.js
We've seen a significant number of deployments take between 10-13 minutes to show as completed in ECS.
Until we can determine the cause of the delay in achieving the stable state (see PP-10154), let's increase the timeout to 15 minutes, to avoid noisy error messages appearing in Slack for deployments that have actually been successful.
=> BAU: Increase deploy timeout to 15 minutes

ci/pipelines/deploy-to-test.yml, ci/tasks/send-release-info-to-hosted-graphite.yml
Adds jobs in the `deploy-to-test` pipeline to send metrics for each app to Hosted Graphite, using a basic netcat command. 
**Notes**
- Concourse already sends metrics to Hosted Graphite for PR build times ([see example for adminusers](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/pr-ci/jobs/record-adminusers-build-time/builds/502)). This is done in a separate Concourse resource that runs a baked-in ruby script. I didn't fancy adapting that, hence using a basic alpine container and using `nc` ([as per the Hosted Graphite docs](https://www.hostedgraphite.com/docs/sendingmetrics/supported-protocols.html#tcp-connection)). I did however keep the `record-*` naming scheme for the job.
- The metric needs to be a numeric value, so we can't send over git commits …
=> PP-10135: Send release numbers to Hosted Graphite

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml
Following on from https://github.com/alphagov/pay-ci/pull/763, send release info metrics to Hosted Graphite following successful deploys to staging and production.
=> PP-10135: Send release metrics to HG for staging and prod apps

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml
Hosted Graphite is not the best at keeping long-lived metrics hanging around. 
This PR adds an hourly 'time' resource that will trigger a refresh of the release metrics, and keep the dashboard populated. A normal release will also trigger the metric sending, as before.
=> PP-10135 Trigger release metrics every hour

ci/pipelines/deploy-to-test.yml
Most of the apps build a candidate image which is then tested as part of the end-to-end test suite. Send metrics to Hosted Graphite for these candidate images, in case the e2e step fails and the image never gets as far as being deployed to test-12.
Apps without e2e coverage: Toolbox, Webhooks, Webhooks-egress, Notifications. We can add in candidate metrics if/when we introduce candidate images for them.
=> PP-10135: Record candidate numbers for apps with e2e

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml
Scheduling the metric jobs every hour meant the resource checks were failing, as there were too many concurrent jobs.
For the test pipeline I've put the `*-release` and the `*-candidate` jobs in the same serial group to try and keep things simple - the jobs themselves are very quick and don't block anything else, so it shouldn't matter if there's a long queue.
=> PP-10135: Use serial_groups for recording metrics

.secrets.baseline, ci/tasks/endtoend/docker-config/endtoend.env
Remove the SELFSERVICE_OTP_KEY environment variable for end-to-end builds as its usages have been replaced by SELFSERVICE_OTP_KEY_BASE32.
=> PP-10051 Remove old environment variable

ci/pipelines/deploy-to-test.yml
Rather than use the bleeding edge version of alpine, pin to version 3.16.
Tested the `update-submodule` step [in this Concourse build](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/build-and-push-cardid-candidate/builds/113)
=> PP-10254: Specify version of alpine to build cardid

ci/tasks/pact-provider-test-preflight-check.yml
Missed this one - the Docker Hub repo has been moved to the new GDS account, this PR updates the pact task to use it.
`pact_with_jq` is currently built and pushed to Dockerhub manually, so there's no pipeline to update for this image.
=> PP-10264: Use pact_with_jq image from GDS Docker Hub account

ci/tasks/pause-unpause-pipeline.yml
The digest changed when we moved the image to the new governmentdigitalservice Docker Hub account.
We don't pin to an image digest elsewhere in the Concourse tasks - I think we can remove this, to streamline the process when we update the image in future.
=> PP-10264: Unpin concourse-runner image version

ci/pipelines/deploy-to-production.yml
We've agreed to continuous deployment in principle for all apps. Carbon relay and stunnel are updated infrequently enough that the risk of being affected by the current Concourse flakiness is outweighed by the practicality of the 'merge-and-forget' option.
Note that we already deploy Carbon relay and Stunnel directly to staging, due to a historical quirk where we hadn't enabled metrics on the test-12 environment, and so needed to see changes on staging-2 to manually verify that metrics were still working.
=> BAU: Auto-deploy carbon-relay and stunnel to production

.github/dependabot.yml
In v20.10.17 the dockerd command was removed. [We reverted it once already](https://github.com/alphagov/pay-ci/pull/786) but forgot to tell dependabot to create new PRs for it, so ended up [merging and reverting a second time](https://github.com/alphagov/pay-ci/pull/797) 😿
=> BAU: Pin Docker dependabot updates to 20.10.16

ci/pipelines/concourse-runner.yml
This adds a concourse job to test PRs on the concourse runner images.
We cannot do this in github actions because the whole point of the container is to give us docker-in-docker on concourse, but of course concourse doesn't run docker, it runs the garden container orchestrator. I did initially try with a github workflow but even in priviledged mode the docker-helpers script can't mess with the cgroups in the way it needs to.
So instead this new job in the concourse-runner pipeline builds the image, and the uses is and executes docker startup, runs a docker command (which would fail if the docker daemon were not running), and then runs docker stop.
It's a very minimal test but a good one going forward since we have had multiple failures where we bump the docker source container for the …
=> PP-10565: Add basic test for concourse-runner

.github/dependabot.yml
Now we have successfully updated to docker 20.10.22 using the `20.10.22-dind` image variant we can remove the dependabot restrictions
=> PP-10565: Remove dependabot restriction

ci/pipelines/deploy-smoke-tests.yml, ci/pipelines/deploy-to-perf.yml, ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml, ci/tasks/check-for-tf-drift.yml, ci/tasks/deploy-app.yml, ci/tasks/deploy-carbon-relay.yml, ci/tasks/deploy-egress.yml, ci/tasks/deploy-frontend.yml, ci/tasks/deploy-scheduled-tasks.yml, ci/tasks/deploy-webhooks-egress.yml
Upgrade all pipelines and tasks to terraform 1.3.7.
I've tried this on the infra-drift-detector pipeline and here is a successful run: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/infra-drift-detector/jobs/test-perf-1-bastion/builds/364
=> PP-10043: Upgrade all pipelines to terraform 1.3.7

ci/pipelines/deploy-to-test.yml
For use in local development.
We weren't previously copying this image over as we didn't think we were using it locally - turns out this was in error (see https://github.com/alphagov/pay-infra/pull/4189).
=> BAU: Copy docker-nginx-proxy image to Dockerhub

.github/dependabot.yml
This will help us categorise our Dependabot PRs across all Pay's repositories more easily.
=> BAU: Add docker labels to dependabot PRs

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml
The Worldpay test environment is currently failing for 3DS payments. While we resolve with Worldpay support, let's disable these smoke test scenarios so our deployment pipeline is unblocked.
=> BAU Temporarily disable Worldpay 3DS smoke tests

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml
The Worldpay test environment has been working for the last couple of days.
=> BAU: Re-enable Worldpay 3DS smoke tests

.github/workflows/_run-provider-contract-tests.yml
Located and replaced all usages of set-output commands in our workflows.
=> PP-10675: replaced usage of set-output in run-provider-contract-tests.yml

ci/pipelines/deploy-to-staging.yml, ci/scripts/parse-staging-release-tag.js, ci/tasks/parse-staging-release-tag.yml
Added tasks to get metrics in the deploy-to-staging Adminusers in the following jobs:
- deploy-adminusers-to-staging
- smoke-test-adminusers-on-staging
- adminusers-pact-tag
- push-adminusers-to-production-ecr
=> PP 10733 add concourse metrics on the deploy to staging pipeline adminusers

ci/pipelines/deploy-to-staging.yml
Added tasks to send metrics to HG in the deploy-to-staging toolbox pipeline in the following jobs:
- deploy to staging toolbox 
- push-toolbox-to-production-ecr
=> PP-10733: added tasks to send job release info to HG

ci/pipelines/deploy-to-staging.yml
Added tasks in the deploy to staging selfservice pipeline for the jobs;
- deploy-selfservice-to-staging
- smoke-test-selfservice-on-staging
- selfservice-pact-tag
- push-selfservice-to-production-ecr
=> PP-10733: Added tasks in selfservice pipeline to send concourse metrics

ci/pipelines/pact-broker.yml
- updated the resource name of pact-broker-ecr-registry to specifically reference the account it relates to
=> PP-10768 rename pactbroker ecr resource

ci/pipelines/carbon-relay-ng.yml
- Parse the golang version correctly
- Get the carbon-relay-ng version by parsing the (now architecture-specific) new name of the binary
Tested this in https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/carbon-relay-ng/jobs/build-then-test-and-push/builds/14
=> BAU: Carbon-relay-ng pipeline tweaks

ci/pipelines/deploy-to-test.yml
Images are usually pushed to dockerhub after a e2e build but webhooks has no e2e tests at the moment, so push it at the end of the build-webhooks step.
Triggered this [build on concourse](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/build-webhooks/builds/374), which put the webhooks image [in dockerhub](https://hub.docker.com/repository/docker/governmentdigitalservice/pay-webhooks/general).
=> PP-10925: Push webhooks image to dockerhub

ci/tasks/node-build-pr.yml
16-stretch-slim is no longer available. ~We use Alpine base images for the actual Node app images, so one would hope their tests should run OK on `node:16-alpine3.17`...~ We're going to try `bullseye-slim` instead for now, as the Alpine change would require some extra wrangling.
=> BAU: Switch Concourse PR node tests to use alpine3.17

ci/pipelines/infra-drift-detector-higher-envs.yml, ci/pipelines/infra-drift-detector-lower-envs.yml, ci/tasks/check-sns-topic-unsubscribers.yml
This PR adds a Concourse `check-for-zendesk-unsubscribers` job that runs a script to the `infra-drift-detector-pipeline` to check if there are any SNS topic unsubscribers, then notify the starling team if an SNS topic subscription has been deleted.
We were unable to find a solution with Terraform/CloudTrail logging:
https://payments-platform.atlassian.net/jira/software/c/projects/PP/boards/83?modal=detail&selectedIssue=PP-10926
>Unsubscribing via an email link does not generate a CloudTrail notification.
>Being unsubscribed does not make terraform see the state as inconsistent
>There are no AWS Config rules which can check this, and even if there were we are notified about compliance violations via an SNS topic which emails Zendesk, meaning if that topic was unsubscribed we would never …
=> Check for zendesk unsubscribers

ci/pipelines/pr.yml
The end to end tests are run using the config in ci/tasks/endtoend. Testing changes to this is painful and theres' no guarantee it will work once merged.
This PR adds a PR end to end tests for changes to anythign in ci/tasks/endtoend.
It will use the current master of every container, but use the pay-ci config in the PR for running the end to end tests.
=> PP-10968: Run end to end PR tests for PRs changing the endtoend config in pay-ci

ci/tasks/parse-release-tag.yml
We added a date to a new tag file so the date an image is built  can later be passed through Concourse pipeline.
The alpine image tag was out of date so this was bumped.
=> PP-11028: Add date to tag file

ci/pipelines/pr.yml
Pipecleaner has been updated to need golang 1.18+
=> BAU: Update golang version for pipecleaner

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml
Enable full continuous deployment for all application images and sidecars out to production.
This was agreed in [this ADR](https://github.com/alphagov/pay-architecture/blob/main/adr/021-continuously-deploy-all-applications.md)
=> PP-8143: fully continuously deploy all apps and sidecars

ci/pipelines/infra-drift-detector-higher-envs.yml
Add drift detection for deploy-tooling environment bastion.
When there was drift (the AMI needing updating) this [run showed it had drifted](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/infra-drift-detector/jobs/deploy-2-bastion/builds/3) and we got this meesage in slack
After the new AMI was applied, [a rerun of the job passed with no drift](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/infra-drift-detector/jobs/deploy-2-bastion/builds/4) and the activity channel got this message 
After I ran those jobs I changed it to run every day at 7am so the job now wont work until tomorrow (and also fixed the name of the job to deploy-tooling-bastion not deploy-2-bastion)
The overnight drift detection ran successfully …
=> PP-11018: Add bastion drift detector for deploy

ci/pipelines/pr.yml
[pay-pr-flow-stats](https://github.com/alphagov/pay-pr-flow-stats) will soon be archived, so remove all uses of its docker image.
=> PP-11118: Remove use of pay-pr-flow-stats docker

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml, ci/tasks/check-canaries-in-error-state.yml
- Added Worldpay recurring card payment smoke test tasks to test/staging/prod pipelines
=> PP-10501 Add Worldpay recurring payment smoke test tasks

ci/pipelines/deploy-to-test.yml
Adds deployment of adot images to test and then staging ecr.
There's a job to run integration tests, but since we don't have time this second to be pragmatic we'll leave the test out and add it in a couple of weeks when I'm back. Instead for now it retags the candidate image with a release tag, a latest tag, and pushes to github as latest-master
You can see this job succeeding:
https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test?group=adot
=> PP-11224: Add deploy-to-test group and deployment for adot image

ci/pipelines/deploy-to-test.yml, ci/tasks/parse-release-tag.yml
Image build date labels and Concourse tags were previously added to candidate images in https://github.com/alphagov/pay-ci/pull/885 . This PR adds labels and tags to release images in the same way.
=> PP-11028: Add timestamp tags to release images

ci/tasks/check-pact-compatibility.yml, ci/tasks/pact-provider-test-preflight-check.yml, ci/tasks/pact-provider-verification.yml, ci/tasks/pact-tag.yml, ci/tasks/publish-pacts.yml
Update pact-broker urls within Concourse so that pact tests, new version tags, pact publishing are done using the migrated pact-broker once its database is updated.
The pactbroker url is changing from https://pay-pact-broker.cloudapps.digital/ & https://pact-broker-test.cloudapps.digital/ [[1](https://github.com/alphagov/pay-ci/blob/711d25cdfee3a47e3e58845badc25f66d26735cd/ci/pact_broker/pay-pact-broker_manifest.yml#L19C1-L21C48)] to https://pact-broker.deploy.payments.service.gov.uk/
=> PP-11292: Update pact-broker urls

ci/pipelines/deploy-to-perf.yml, ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/tasks/create-notification-snippets.yml
Have concourse deploy ADOT to staging, prod, and perf
ADOT is still disabled so this is a whole lot of "No changes" right now.
You can see working jobs with this config:
perf: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-perf/jobs/deploy-publicauth-to-perf/builds/29
staging: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/deploy-to-staging/jobs/deploy-adminusers-to-staging/builds/503
production:  https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/deploy-to-production/jobs/deploy-adminusers-to-prod/builds/460
=> Pp 11226/deploy adot to staging, prod, and perf

ci/pipelines/prometheus-pushgateway.yml
At the moment the pipeline copies v1.6.0 of the [prometheus pushgatway on dockerhub](https://hub.docker.com/r/prom/pushgateway/tags) to our ECR for use by the up-and-coming pushgateway ECR task definition. In the future we will extend this pipeline with deployment for the pushgateway.
[Successful run](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/prometheus-pushgateway/jobs/copy-prometheus-pushgateway/builds/1).
Pushgateway image is now in [deploy ECR](https://eu-west-1.console.aws.amazon.com/ecr/repositories/private/424875624006/pushgateway?region=eu-west-1).
=> PP-11272: Prometheus pushgateway pipeline

ci/pipelines/pay-js.yml, ci/tasks/npm-version-and-create-pr.yml
Limitations in the GitHub permissions model mean that if we want to automatically version and release our Node packages we'll need to do the versioning part from Concourse.
This pipeline monitors commits to the main branches of our `pay-js` packages. When a new commit (that is not a release commit created by this pipeline) is detected. Concourse will build and version the package appropriately, creating a release tag and opening a PR to merge in files affected by the `npm version patch` command.
=> PP-11314 pipeline for versioning node packages

ci/pipelines/pr.yml
Remove the pact-test serial group.
There's no reason I know of to require the pact tests to run serially across different projects.
Having them in a serial group is slowing PR tests and causing serial conflicts with concourse getting confused and occasionally never running any jobs.
Note: I have already applied this to test the theory that it was the serial group stopping the jobs from running, and to unblock developers
=> BAU: Remove pact test serial group

ci/tasks/check-canaries-in-error-state.yml
Worldpay remove 3ds1, we already removed the smoke tests for them, but forgot about the error state checks
=> PP-11389: Remove error state checks for worldpay 3ds1 tests

ci/pipelines/pact-broker.yml, ci/tasks/deploy-pact-broker.yml
Pass the pact-broker image tag through to terraform so that the Concourse pipeline can be triggered to deploy/redeploy the AWS ECS Fargate service (using a new task definition).
=> PP-10671: Pass pactbroker image tag through to terraform

ci/pipelines/pact-broker.yml
so that the tag pushed alongside the image to AWS ECR matches the image built and deployed.
Paired with @jfharden
=> PP-10671: Get and set the pactbroker image tag

ci/pipelines/infra-drift-detector-higher-envs.yml, ci/pipelines/infra-drift-detector-lower-envs.yml, ci/tasks/check-sns-topic-unsubscribers.yml
1. Rewrote the sns checker to be a little more resilient and to check multiple regions as specified by the REGIONS parameter.
2. Set the checker to run every 15 minutes now we are much more dependent on these sns topics.
You can see the jobs running and working in the infra-drift-detector pipelines in dev and deploy teams
=> Pp 11425/make sns unsubscribe check multi region

ci/scripts/test-metrics.js
Fix the ADOT integration test.
I broke the integration test when I updated the default labels, we no longer receive a job label (on purpose, it's not useful for us) but this means the query used in the integration test needs updating. I also added a cluster selector label just in case test-perf-1 toolbox were ever online when the test ran
=> BAU: Fix ADOT integration test

.github/workflows/test-run-codebuild.yml, ci/docker/node-runner/Dockerfile.node18, ci/pipelines/node-runner.yml, ci/tasks/node-build-pr.yml
Node 16 is out of support. Move internal tooling to Node 18.
Move Github actions from 16 to 18; build new Node 18 version of node-runner and have Concourse use it; use Node 18 for Concourse PR jobs.
Use Node18 runtime for logging Lambdas. They all pass their unit tests on Node 18.
I have run what scripts I could locally with Node 16 and 18 containers, and observed no difference.
I'VE LOOKED HARD BUT I MAY HAVE MISSED SOMETHING!
=> PP-11411-upgrade-concourse-script-containers-to-node-18

ci/tasks/publish-pacts.yml
We should be consistent with the tooling used for running the Concourse tasks. Also this base image hasn't been updated in some time.
The `governmentdigitalservice/pay-concourse-runner` image ([see Dockerfile here](https://github.com/alphagov/pay-ci/blob/master/ci/docker/concourse-runner/Dockerfile)) has `curl` and `jq` installed, and receives regular Dependabot updates.
=> PP-11626: Replace alpine-curl-jq with concourse-runner

ci/pipelines/deploy-to-test.yml
Adding build date labels and tags to webhooks and notifications images before they are pushed to ECR in test.
Some extra docker labels were added to follow the other images.
Pipeline changes can be checked by:
`fly --target pay-dev set-pipeline --config ci/pipelines/deploy-to-test.yml --pipeline deploy-to-test`
=> PP-11704: add timestamp tags to notifications and webhooks

.github/dependabot.yml
We're using Node18 everywhere at the moment - the `node-runner` helper image should align with this.
=> BAU: Pin node-runner image to Node 18

ci/pipelines/stubs.yml, ci/tasks/deploy-stubs.yml
Add a pipeline to build and deploy the Stubs application in ECS.
A couple of things about this pipeline are "old". First, though we have other tickets to move tests into Github Actions, building from the Stubs `Dockerfile` runs tests in-place so, in this case, in Concourse. Second, the tag of the image is always `latest-master`. These don't seem ideal, but I chose to leave them as-is. I have, however, added code to put in build-date and Git SHA labels, in line with other repos.
[The pipeline currently in Concourse](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/stubs) has been deployed from my laptop. The deploy phase is not expected to work, as it currently has nothing to deploy to. The ECS service is defined in https://github.com/alphagov/pay-infra/pull/4547, …
=> PP-11459-create-stubs-ecs-pipeline

ci/pipelines/perf-tests.yml
Start perf databases during the weekly maintenance window to ensure AWS can apply minor updates and OS security patches etc.
You can see this applied https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/perf-tests
=> PP-11703: Start perf DBs for weekly maintenance window

ci/pipelines/deploy-to-perf.yml
Deploy Stubs to ECS rather than PAAS in test-perf.
I'm doing this rather blindly. It _looks_ like the right thing to do, but I need a reviewer more aware of the whole test-perf ecology to tell me I'm on the right path.
=> PP-11785-deploy-stubs-to-perf

ci/pipelines/perf-tests.yml
Scale Stubs in ECS rather than in PAAS when we run the perf-test pipeline.
You can see successful scale-up and scale-downs:
* https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/perf-tests/jobs/scale-up-all/builds/61.15
* https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/perf-tests/jobs/scale-down-all/builds/27.2
This change will not work without the IAM changes in https://github.com/alphagov/pay-infra/pull/4617
=> PP-11873-scale-stubs-when-perf-test-run

ci/tasks/start-rds-instance.yml, ci/tasks/stop-rds-instance.yml
The RDS instances sometimes take a long time to startup/shutdown, on some occasions AWS decides to do a backup at startup, or shutdown, and our waiting period isn't long enough for it to complete.
Increase waiting periods for both startup and shutdown to 1 hour.
=> BAU: increase db startup & shutdown timeouts

ci/docker/concourse-runner-with-java-17/docker-helpers.sh, ci/docker/concourse-runner/docker-helpers.sh
Updated the sanitize crgroups method to match the latest version https://github.com/concourse/docker-image-resource/blob/master/assets/common.sh which provides cgroups v2 support
=> PP-10714: Update concourse runner docker helpers sanitize cgroups

ci/pipelines/stubs.yml
Add the variant release filter to the stubs ecr registry image.
Without this we get an empty list of resources and it makes the deploy stubs pipeline impossible to pin the ecr image.
=> BAU: The stubs ecr registry image needs the variant filter

.github/workflows/_run-provider-contract-tests.yml
- Pull postgres 15.2 along with 11.16 when running provider contract tests. We can remove 11.16 once all apps have been updated to use postgres 15.2
=> PP-11895 Pull postgres 15.2 for provider contract tests

ci/pipelines/deploy-to-test.yml
- Removed build-jar task from  connector & cardid jobs as it is no longer required
=> PP-10385 Remove build-jar task from connector and cardid jobs

ci/pipelines/deploy-to-test.yml
- Removed build-jar task from rest of the jobs as it is no longer required
=> PP-10385 Remove build-jar task from rest of the jobs

ci/pipelines/perf-tests.yml, ci/tasks/prepare-perftests-codebuild.yml
Make it easy for developers to run the performance tests using a PR on the pay-perftests git repo.
I had to refactor a little so I moved the prepare codebuild task into it's own file (so we could override the repo name and version with vars).
You can see this working on the "build-and-run-perftests-from-pr job in https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/perf-tests?group=perf-tests-build
I also ran https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/perf-tests/jobs/run-self-service-simulation-perf-test/builds/20 to prove it doesn't break the jobs which already run the perftests.
=> PP-11964: Allow running perftests on PRs of pay-perftests

ci/pipelines/deploy-to-test.yml, ci/pipelines/pr.yml
- CardID submodule URL is configured as SSH but concourse is re-writing as HTTPS URL. Codebuild also needs HTTPS URL for submodules. https://github.com/alphagov/pay-cardid/pull/1134 updates the submodule URL to HTTPS. so update pipeline for the change
=> PP-10386 Treat submodules URL as https

ci/pipelines/deploy-to-test.yml, ci/tasks/prepare-codebuild-multiarch.yml
Build multi-arch cardid Docker images in CodeBuild, and publish them to ECR and Docker Hub.
This PR has [a companion in `pay-infra`](https://github.com/alphagov/pay-infra/pull/4679) which sets up the IAM role Concourse needs to run CodeBuild jobs.
The work here can easily be repurposed to other Pay applications. N
[Here is a completed Concourse job](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/codebuild-cardid/builds/38) and [here are the published images](https://eu-west-1.console.aws.amazon.com/ecr/repositories/private/223851549868/govukpay/cardid?region=eu-west-1).
=> PP-10386-build-cardid-in-codebuild

ci/pipelines/deploy-to-test.yml
Build multiarch adminusers in CodeBuild.
You can see a successful pipeline run [here](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/run-adminusers-e2e/builds/601); the Docker Hub images [here](https://hub.docker.com/repository/docker/governmentdigitalservice/pay-adminusers/general) and the ECR images [here](https://eu-west-1.console.aws.amazon.com/ecr/repositories/private/223851549868/govukpay/adminusers?region=eu-west-1).
Pipeline has been reverted to the old version until this is merged.
=> PP-12008-build-adminusers-in-codebuild

ci/pipelines/deploy-to-test.yml
- Builds connector images in CodeBuild. Changes are similar to https://github.com/alphagov/pay-ci/pull/995
- [build candidate](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/build-and-push-connector-candidate/builds/820)
- [re-tag manifest after e2e tests](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/run-connector-e2e/builds/870)
=> PP-12010 Build connector in CodeBuild

ci/pipelines/deploy-to-test.yml
Build PublicAPI in Codebuild, for ARM and AMD.
See [Docker Hub image](https://hub.docker.com/layers/governmentdigitalservice/pay-publicapi/latest-master/images/sha256-a3602cb6f8b157df09731c45361287148426ce2006ef1ae29e90a0075c3d236f?context=repo), [Concourse](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/build-and-push-publicapi-candidate/builds/387) and [ECR](https://eu-west-1.console.aws.amazon.com/ecr/repositories/private/223851549868/govukpay/publicapi?region=eu-west-1).
=> PP-12012-build-publicapi-in-codebuild

.github/workflows/_validate_docker_image_is_manifest.yml
Given we are moving to multi-arch builds we want to be able to check from all repos with docker images SHA pinned that the pins point to a manifest, and not directly to an image.
This reusable workflow will check every FROM line in the dockerfile specified as an input (defaulting to Dockerfile in the root of the repo using this workflow) and validate they are a manifest, and provide helpful information if they are not a manifest, including a likely manifest sha where that is possible to establish.
I opened a PR in pay-frontend which uses this workflow. This test https://github.com/alphagov/pay-frontend/actions/runs/7387040621/job/20095008936 shows a passing check (where all the FROM lines are valid).
For this test I altered one of the FROM lines to use a SHA which points directly to an …
=> PP-12015: Add reusable workflow to check docker image definitions are manifests, not images

ci/pipelines/e2e-helpers.yml
Build stubs mulit-arch in the e2e-helpers pipeline.
This doesn't get it into the deploy account, I'll do a follow up for that next.
=> PP-12034: In e2e-helpers build stubs in codebuild multi-arch

ci/pipelines/e2e-helpers.yml, ci/tasks/copy-multiarch-image-to-other-account.yml
We need to copy multi-arch images from one account to another. This adds a task (and uses it in e2e-helpers for stubs) which:
1. uses 1 role in a source account, logs in to ECR
2. pulls the images XX-candidate-<ARCH> (both amd64 and armv8)
3. uses a second role in a destination account and logs into ECR again with that
4. Pushes the images to the destination account
5. Creates a manifest in the destination account of XX-release
=> Pp 12034/push multiarch stubs to deploy

ci/pipelines/stubs.yml
e2e-helpers pipeline now builds multi-arch images, and pushes those multi-arch images into deploy ECR.
This PR stops us rebuilding them in the deploy account, and instead uses the pushed images built in test
I applied it and you can see the deployment in https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/stubs and the successful deployment of the multi-arch image https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/stubs/jobs/deploy-stubs/builds/26
=> PP-12034: Stubs is built and pushed to deploy ECR from the e2e-helpers pipeline, don't rebuild it

ci/pipelines/deploy-to-test.yml
Build publicauth AMD/ARM in CodeBuild, push to Docker and ECR.
* [Concourse Run](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/build-and-push-publicauth-candidate/builds/302)
* [ECR images](https://eu-west-1.console.aws.amazon.com/ecr/repositories/private/223851549868/govukpay/publicauth?region=eu-west-1)
* [Docker Hub images](https://hub.docker.com/repository/docker/governmentdigitalservice/pay-publicauth/general)
=> PP-12080-build-publicauth-in-codebuild

ci/pipelines/deploy-to-test.yml
Requires https://github.com/alphagov/pay-infra/pull/4711
Notifications doesn't go to dockerhub so:
[successful build](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/build-and-push-notifications-to-test-ecr/builds/35)
[ECR Images](https://eu-west-1.console.aws.amazon.com/ecr/repositories/private/223851549868/govukpay/notifications?region=eu-west-1)
=> PP-12033: Build notifications multi-arch

ci/pipelines/e2e-helpers.yml
Build multiarch reverse-proxy images in CodeBuild. Because those images need to include naxsi rules which are stored in pay-infra, I have also had to make changes to [pay-infra](https://github.com/alphagov/pay-infra/pull/4714) and [pay-scripts](https://github.com/alphagov/pay-scripts/pull/1436).
* [Concourse run of build job](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/e2e-helpers/jobs/build-and-push-reverse-proxy-candidate/builds/417.2)
* [Concourse run of e2e job](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/e2e-helpers/jobs/reverse-proxy-e2e/builds/391)
* [Images in ECR](https://eu-west-1.console.aws.amazon.com/ecr/repositories/private/223851549868/govukpay/reverse-proxy?region=eu-west-1)
* [Images in Docker …
=> PP-12035-reverse-proxy-codebuild

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml, ci/scripts/get-git-sha-for-release-tag.js, ci/tasks/get-git-sha-for-release-tag.yml
Authenticate to github on all git resources in deploy-to-x pipelines and also on all calls of get-git-sha-for-release-tag.yml
=> BAU: authenticate with GitHub

ci/pipelines/deploy-to-test.yml
- Tagging for nginx-forward-proxy has been changed in https://github.com/alphagov/pay-nginx-forward-proxy/pull/90. Use alpha_release tags in CI pipelines
=> PP-12032 Update nginx-forward-proxy pipeline to use `alpha_release` tags

ci/pipelines/deploy-to-test.yml
Build multi-arch egress proxy in CodeBuild, and push to ECR. This is not pushed to Docker Hub.
* [Concourse Build](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/build-and-push-egress-candidate/builds/16)
* [Images in ECR](https://eu-west-1.console.aws.amazon.com/ecr/repositories/private/223851549868/govukpay/egress?region=eu-west-1)
* [Smoke test](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/smoke-test-egress/builds/52)
=> PP-12025-build-egress-in-codebuild

ci/pipelines/deploy-to-test.yml, ci/tasks/parse-ecr-release-tag.yml
Copy multi-arch images for adminusers from test to staging.
I've made some of the config anchors so they can be reused in the million other places they are needed and they don't change at all.
You can see a successful copy:
https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/push-adminusers-to-staging-ecr/builds/605
=> PP-12074: Copy multi-arch images from test to staging for adminusers

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml
- The Stripe 3DS smoke test has been failing with the below error message. It looks like Stripe 3DS iframe DOM has changed
> Failure Reason: "TimeoutError: Waiting for selector `iframe.FullscreenFrame` failed: Waiting failed: 30000ms exceeded Stack: TimeoutError: Waiting for selector `iframe.FullscreenFrame` failed: Waiting failed: 30000ms exceeded\n    at Timeout.<anonymous> (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:65:32)\n    at listOnTimeout (node:internal/timers:569:17)\n    at process.processTimers (node:internal/timers:512:7) for step: Click submit button on 3DS page"
- Temporarily remove the test while we investigate and fix the test
=> BAU: Remove Stripe 3DS smoke test temporarily

ci/pipelines/deploy-to-staging.yml
Push application images from staging ECR to production ECR.
This change just pushes adminusers. Once we're satisfied it works correctly, I will submit another PR for all the other applications, as I did for test -> staging.
[Concourse run is here](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/deploy-to-staging/jobs/push-adminusers-to-production-ecr/builds/573).
There are a lot of whitespace changes in this change. It will be easier to review if you ask Github to ignore whitespace.
=> PP-12074-copy-multiarch-builds-to-prod

.github/dependabot.yml
Stop dependabot from trying to update to a `dind` version that pact tests are not compatible with.
=> BAU pin `dind` for concourse runners

ci/pipelines/deploy-to-staging.yml
Push all multiarch builds from staging to production. Adminusers has already been done, in #1037.
This is a big change, but to make reviewing as easy as possible, each application is in its own commit. (Which will be squashed on merge.)
Everything has been tested by running the relevant `push-XXXX-to-production-ecr` job in Concourse.
=> PP-12074-copy-all-multiarch-builds-to-prod

.github/workflows/_validate_docker_image_is_manifest.yml
Our unit test to make sure all docker base images are manifests, not raw images, uses docker manifest inspect (which is listed as experimental). It seems that if a new manifest gets pushed with the same tag (which probably leaves the old manifest untagged) docker manifest inspect fails, even when referencing a manifest by a sha pin.
We can instead use docker buildx imagetools inspect which seems to always work
=> PP-12156: Replace docker manifest inspect with docker buildx imagetools inspect

ci/pipelines/deploy-to-production.yml, ci/tasks/copy-multiarch-image-to-other-account.yml, ci/tasks/manifest-retag.yml
Retag the adminusers candidate in the test ECR for test-perf. Requires [this change to pay-infra](https://github.com/alphagov/pay-infra/pull/4728).
Not many adminusers releases require a database migration, and since we only keep a hundred images in our eu-west-1 test ECR, we cannot be certain that the perf-db candidate still exists there. But, we keep everything in our eu-central-1 test ECR, so this change copies the relevant candidate release across regions prior to retagging.
Concourse runs:
* https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/deploy-to-production/jobs/retag-adminusers-image-for-test-perf-db/builds/41
* https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/deploy-to-production/jobs/retag-adminusers-image-for-test-perf/builds/393 …
=> PP-12075-retag-adminusers-for-perf-test

ci/pipelines/deploy-to-production.yml
Make sure all our application images end up in eu-west-1 test ECR, tagged for perf-test. Each app is in a separate commit for simple reviewing, but I'm afraid it will still be a huge chore.
Note that when I ran the jobs to test them, a couple of the DB ones failed. This is because migrations aren't that common, and  in some cases we haven't run a multiarch build since the last one. This shouldn't be an issue: what's needed is already there, and the next ones will succeed.
=> PP-12075-retag-for-perf-test

.github/workflows/_validate_docker_image_is_manifest.yml
ADOT images use a different manifest list mediatype than all the others we have, but it is a valid image list type so we should be ok with this too.
See https://github.com/alphagov/pay-adot/actions/runs/7871038916/job/21473486399 for the failure using the manifest verification on master.
=> PP-12123: There's another mediatype which is an image list

ci/pipelines/concourse-runner.yml
- Runs adminusers & webhooks integration tests for updates to concourse-runner images
- new PRs updating concourse-runner images
-  [concourse-runner-with-java-17 PR](https://github.com/alphagov/pay-ci/pull/1047): [concourse job](https://pay-cd.deploy.payments.service.gov.uk/builds/109801502)
- [concourse-runner PR](https://github.com/alphagov/pay-ci/pull/1043): [concourse job](https://pay-cd.deploy.payments.service.gov.uk/builds/109798145)
- Major version bump fails as expected
- https://github.com/alphagov/pay-ci/pull/1051
- [concourse job](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/concourse-runner/jobs/concourse-runner-pr/builds/91)
=> PP-12125 Run integration tests for concourse runner image updates

ci/pipelines/prometheus-pushgateway.yml
Add a job to the prometheus-pushgateway pipeline to build and push the prometheus-pushgateway-resource to dockerhub.
Later, when we aren't just spiking on this it would be good to add some integration tests between candidate and confirmed release, but while we are spiking this minimal setup will do.
Also bump the pushgateway to 1.7.0
=> PP-12123: Add jobs to build and push prometheus pushgateway resource

ci/pipelines/prometheus-pushgateway.yml
After merging my previous PR for this pipeline I noticed it doesn't have the self-update job. So this PR adds a pipeline self-update from master in pay-ci.
I set the pipeline with this job and you can see it successfully run: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/prometheus-pushgateway/jobs/update-prometheus-pushgateway-pipeline/builds/1
=> BAU: Add prometheus-pushgateway pipeline self update

ci/pipelines/deploy-to-test.yml, ci/tasks/create-notification-snippets.yml, ci/tasks/parse-candidate-tag.yml, ci/tasks/parse-ecr-release-tag.yml, ci/tasks/parse-release-tag.yml
Considering we have hundreds of places to send the metrics I've put a lot of effort in deploy-to-test to be able to parse all the different kinds of inputs and generate app names and release numbers, and to use yaml anchors and loaded variables so we can not have to repeat literally thousands of lines of code.
I've run all the jobs and have created a simple grafana dashboard which shows the release number sent at each step:
https://grafana.monitoring.pay-cd.deploy.payments.service.gov.uk/d/e5000e04-deef-4ac7-8ffc-b7364c241dd1/release-pipeline-releases?orgId=1
=> PP-12123: try sending metrics from deploy-adminusers

ci/pipelines/grafana-annotation-resource.yml
Add pipeline to build and push https://github.com/alphagov/paas-grafana-annotation-resource to dockerhub
Successful build: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/grafana-annotation-resource/jobs/build-and-push-grafana-annotation-resource/builds/1.1
Dockerhub release: https://hub.docker.com/repository/docker/governmentdigitalservice/pay-grafana-annotation-resource/tags?page=1&ordering=last_updated
=> PP-12218: Add grafana-annotation-resource pipeline

ci/tasks/endtoend/docker-config/cardid.env
The changes in https://github.com/alphagov/pay-cardid/pull/1165 iterate towards a solution where the production bin range files overwrite the local files when a release artefact is prepared.  That means that the local environment can read the files from `src/main/resources` and show sensible defaults, then when we build a release artefact those files will be replaced with production-suitable files.
On our way towards that solution we're improving the local environment by using the newly created demo files but production-like environments need to put the old value back in.
These environment variables will be needed on each production-like environment but I'm testing them first in endtoend.
When remove the git submodule implementation these environment variables will be removed.
=> PP-12222: Overriding new default values with the old production-like values

ci/pipelines/deploy-to-production.yml
1. Add plenty of anchors for allowing sending release metrics as we did in test with the added complication that for _some_ steps we send to a different channel (the anchor was previously suffixed with _p1 which doesn't make much sense since it's announcing a good thing, so I renamed it _annouce.
2. Add deployment metric sending for all 4 of the adminusers deploy-to-production steps.
You can see them in grafana now: 
https://grafana.monitoring.pay-cd.deploy.payments.service.gov.uk/d/e5000e04-deef-4ac7-8ffc-b7364c241dd1/release-pipeline-releases
=> Pp 12216/send release metrics for adminusers in prod

ci/pipelines/deploy-to-perf.yml
1. Add plenty of anchors for allowing sending release metrics as we did in test
2. Add deployment metric sending for the deploy-adminusers job in deploy-to-perf
You can see a successful run of this in https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-perf/jobs/deploy-adminusers-to-perf/builds/461
And I updated the temp dashboard to show it https://grafana.monitoring.pay-cd.deploy.payments.service.gov.uk/d/e5000e04-deef-4ac7-8ffc-b7364c241dd1/release-pipeline-releases?orgId=1
=> PP-12216: Send adminusers release metrics from deploy-to-perf

ci/pipelines/deploy-to-test.yml
The `deploy-to-test.yml` pipeline file contained a duplicate `definitions` block introduced in [this commit](https://github.com/alphagov/pay-ci/commit/a80b8d46429af621e113e25e1ea4785a7a12f5d2).
Tidy up the file by:
*  Nesting the array type anchors under a new mapping `array_anchors`. 
* Moving the map type anchors under the first `definitions`.
* Converting the array type anchor in the second `definitions` block to a map type and moving it to the first `definitions` block, and removing teh now empty second block.
These changes are seperate commits that at no point change the actual pipeline.
=> BAU: Tidy pipeline anchors

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml
The `deploy-to-staging.yml` and `deploy-to-production.yml` pipeline files contain a `definitions` block containing "array type" anchors and also a lot of "map type" anchors at the top level.
This PR tidies up these pipelines by:
* Nesting the array type anchors under a new mapping `array_anchors`
* Moving the map type anchors under `definitions`
This is a condensed version of the changes made in [pay-ci/pull/1067](https://github.com/alphagov/pay-ci/pull/1067).
Dry-run updates to the pipelines show no update, as intended.
```console
> fly -t pay-deploy set-pipeline -d -p deploy-to-staging -c ci/pipelines/deploy-to-staging.yml
no changes to apply
> fly -t pay-deploy set-pipeline -d -p deploy-to-production -c ci/pipelines/deploy-to-production.yml 
no changes to apply
```
=> BAU: Tidy pipeline anchors for deploy to staging and prod pipelines

ci/pipelines/deploy-to-test.yml
Puts an annotation in Grafana when an adminusers release succeeds.
We already have logic to report success to Slack and Prometheus, so I chose to piggyback off that. 
Tags are the application name, the target environment, and the fixed string `release`. What is released is encoded in the annotation description. I am happy to discuss and/or alter this choice, because I flip-flopped many times on what should or should not be a tag.
You can see an annotation [here](https://grafana.monitoring.pay-cd.deploy.payments.service.gov.uk/goto/qdZQ7ETSR?orgId=1).
=> PP-12219-deployment-events-for-adminusers

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml
Update `deploy-to-test`, `deploy-to-perf`, `deploy-to-staging`, and `deploy-to-production` to send release metrics for the cardid app.
This is a fairly mechanical copy of the changes made to the jobs for adminusers in these pipelines. Some reordering was done to add consistency with the structure of the adminusers jobs.
=> PP-12262: Send Release Metrics for CardID

ci/pipelines/deploy-to-perf.yml
Some of the YAML anchors added for helping with release metrics for the adminusers app in the deploy to perf pipeline were specific to adminusers and therefore could not be used for other apps.
Refactor the helper YAML anchors in deploy-to-perf so that they are not adminusers specific.
=> BAU: Refactor deploy-to-perf pipeline YAML anchors

ci/pipelines/deploy-to-perf.yml
Update the `deploy-to-perf` pipeline to send release metrics for the cardid app. This is a mechanical copy of the same changes made for the adminusers app.
This completes the pipeline updates for `cardid` started in [pull 1070](https://github.com/alphagov/pay-ci/pull/1070)
=> PP-12262: Send release metrics for cardid in `deploy-to-perf`

ci/pipelines/deploy-to-perf.yml, ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml
Webhooks-egress and egress are both in their own repos now and using consistent tagging of XX-release and alpha_release-XX.
=> PP-12390: Update deploy pipelines for new egress and webhooks-egress repos and tagging

ci/pkl-pipelines/common/pipeline_self_update.pkl, ci/pkl-pipelines/common/shared_resources.pkl, ci/pkl-pipelines/pay-deploy/detect-secrets.pkl, ci/pkl-pipelines/pay-deploy/pay-js.pkl
Between my changes and the changes of @kbottla we ended up with some duplicated, but different, shared code. This PR removes that duplication and reuses the newer code @kbottla wrote.
I've also added the pipeline self update to strip pay-dev team name as well as pay-deploy
There are no set-pipeline differences between this PR and the ones we already merged.
=> PP-12343: Refactor to reduce duplicated common shared code

ci/pkl-pipelines/common/pipeline_self_update.pkl, ci/pkl-pipelines/pay-deploy/pay-js.pkl
Oops, left -test in the name of the pipelines that get set with the self update, and also pay-js is in the pay-deploy subfolder
=> PP-12343: Pay-js is in pay-deploy subfolder, also don't apply pipelines with -test suffix

ci/pipelines/deploy-to-production.yml
Update the `deploy-to-production` pipeline to send release metrics for the egress app.
Pipeline applied.
Run all jobs:
Metrics recieved:
=> PP-12264: Send release metrics for egress in deploy-to-production

ci/pkl-pipelines/common/shared_pipelines/pkl_pipeline_changes.pkl, ci/pkl-pipelines/common/shared_resources.pkl
I realised, the actual concourse ci tests (running pipecleaner etc) and my tests all post the same test name to concourse, so they overwrite each other for the test status.
This PR allows the test name to be set in the shared resource, and updates the pkl-pipeline-changes pipelines to use a new name.
Hopefully this PR should _also_ demo the whole process works
=> PP-12385: Use different test names from concourse regular ci test

ci/pipelines/deploy-to-perf.yml, ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml
Send deployment metrics for all relevant publicauth tasks across all pipelines.
[See in Grafana](https://grafana.monitoring.pay-cd.deploy.payments.service.gov.uk/goto/bqAHb9ASg?orgId=1).
=> PP-12268-publicauth-release-metrics

ci/scripts/comment-on-pr-with-pkl-pipeline-diffs.sh
These 2 messages get applied as a comment on the PR but don't make it clear which concourse team they apply to, so add that information into the comment.
=> BAU: Improve comments so you always know which concourse team it applies to

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml, ci/pipelines/perf-tests.yml
We are defining the registry-image resource type in some pipelines, but its now bundled with concourse and we don't need to custom define it.
We also don't use cloudfoundry anymore so removing the cf-cli resource type from the perf-tests pipeline.
I've not removed it from deploy-to-perf since @kbottla is currently converting it to pkl
=> PP-12421: Remove redundant resource types

ci/pipelines/deploy-to-perf.yml, ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml
Send release metrics for toolbox. 
[Here they are in Grafana](https://grafana.monitoring.pay-cd.deploy.payments.service.gov.uk/goto/vOTmReAIR?orgId=1). Note that toolbox doesn't do pact tagging or smoke-testing.
=> PP-12272-toolbox-release-metrics

ci/pkl-pipelines/common/shared_resources_for_slack_notifications.pkl, ci/pkl-pipelines/pay-dev/deploy-to-perf.pkl, ci/scripts/deploy-notifications.sh
- Added deploy-to-perf pkl module
- Some apps show additional changes for Slack notifications as `sending metrics` yaml is being added for apps not done yet
- `adot` is not added to list of apps as test-perf doesn't have `adot` group. Will add it separately 
Diff is in concourse due to size. Can use the terminal using below which shows diffs in color
`cd ci/pkl-pipelines/pay-dev`
`fly -t pay-dev set-pipeline -c ./deploy-to-perf.yml -p deploy-to-perf --dry-run | zmore`
=> PP-12420 Convert deploy-to-perf pipeline to pkl

ci/pipelines/deploy-to-production.yml, ci/pipelines/deploy-to-staging.yml, ci/pipelines/deploy-to-test.yml
- Fix the typo in `conocurse` so that when pipelines are being migrated from yml to pkl, diffs shown are minimal
=> PP-12422 Fix typo

ci/pkl-pipelines/common/pipeline_self_update.pkl, ci/pkl-pipelines/common/shared_pipelines/pkl_pipeline_changes.pkl, ci/pkl-pipelines/common/shared_resources.pkl, ci/pkl-pipelines/common/shared_resources_for_metrics.pkl, ci/pkl-pipelines/common/shared_resources_for_slack_notifications.pkl, ci/pkl-pipelines/pay-deploy/concourse-runner.pkl, ci/pkl-pipelines/pay-deploy/detect-secrets.pkl, ci/pkl-pipelines/pay-deploy/pact-broker.pkl, ci/pkl-pipelines/pay-deploy/pay-js.pkl, ci/pkl-pipelines/pay-deploy/prometheus-pushgateway.pkl, ci/pkl-pipelines/pay-dev/deploy-to-perf.pkl, ci/scripts/test-concourse-runner.sh
First pass at converting the `concourse-runner` pipeline to pkl. This commit only adds the pkl file. Dry run applying the resulting yaml to concourse gives the following differences:
* All git resources have password and username
* Resource `concourse-runner-pipeline` renamed `pipeline_source`
* Job `update-concourse-runner-pipeline` replaced with shared version `update-pipeline`
First commit is a find replace on the `pkl-concourse-pipeline` version.
=> PP-12424: Convert `concourse-runner` pipeline to pkl

ci/pkl-pipelines/pay-deploy/concourse-runner.pkl
To use the extracted script file, the `pay-ci` resource must be an input. Additionally, reference to the script file `test-concourse-runner` was incorrect. It should be `test-concourse-runner.sh`
=> PP-12424: Input pay-ci and fix script file name

ci/pkl-pipelines/pay-dev/e2e-helpers.pkl
Generates the e2e-helpers file with minimal changes, mostly related to the set-pipeline job, which we've decided to do in a new, uniform way.
It can definitely be made smaller, and should be once we've pulled helper functions together in `shared_resources` but for now I think it will do. It is, I hope, clear. 
Some, possibly much, duplication can be removed by changing the jobs slightly, but my aim here was to reproduce the pipeline as-is, including oddities. (Including a single-step `in_parallel`.)
=> PP-12386-convert-e2e-helpers-to-pkl

ci/pkl-pipelines/common/shared_resources_for_deploy_pipelines.pkl, ci/pkl-pipelines/pay-deploy/deploy-to-production.pkl, ci/pkl-pipelines/pay-dev/deploy-to-perf.pkl
- Moved list of apps to separate pkl module and used in perf and prod pipelines
- Added aliases to avoid lengthy references throughout
- Common tasks in deploy pipelines can be added to `shared_resources_for_deploy_pipelines.pkl`
=> PP-12422 Refactor: move list of apps to separate pkl module

ci/docker/node-runner/Dockerfile
Pulls in Node security updates and the latest alpine.
=> PP-12515: Bump Node to 18.20.1-alpine3.19

ci/pipelines/deploy-to-test.yml
When we do a release annotation, put the pipeline name in as an extra tag. This will let us filter annotation displays in dashboards.
=> BAU-tag-releases-with-pipeline

ci/pipelines/deploy-to-test.yml
use literal string, because variable isn't expanded. (And isn't necessary, really.)
=> BAU-tag-releases-with-pipeline-literal

.github/dependabot.yml, ci/docker/concourse-runner-with-java-21/Dockerfile, ci/docker/concourse-runner-with-java-21/README.md, ci/docker/concourse-runner-with-java-21/docker-helpers.sh, ci/docker/concourse-runner-with-java-21/docker-wrapper, ci/pkl-pipelines/pay-deploy/concourse-runner.pkl
My first attempt at some pkl. Very happy to amend anything if I've gone down the wrong track. 
At some point we'll need a container for running Java 21 tests on Concourse, similar to how we have a Java 17 container for Webhooks tests. I'm not too worried about DRYing this as eventually we won't need the Java 11 and Java 17 versions.
- Clones the Dockerfile and associated helper scripts into a new folder. These are identical to the Java 17 files apart from the `openjdk` version.
- Adds Dependabot config for the new Java 21 Dockerfile
- Adds the new resources to the concourse-runner pipeline (I've created the new repo in DockerHub already)
- Adds the Java 21 build steps to a) the PR job b) the post-merge job. Unlike Java 17 and webhooks, there is no app running on Java 21 where we can test …
=> PP-11718 Concourse runner with Java 21

ci/pkl-pipelines/pay-dev/deploy-to-test.pkl
- deploy-toolbox (in test) job needs `adot-candidate` instead of release.
=> PP-12423 Fix deploy-toolbox (test) job

ci/pkl-pipelines/pay-dev/deploy-to-test.pkl
- Passes APP_NAME param to parse-release-tag task. `grep url=` in the parse-release task is returning multiple URLs (card-id and submodule) and breaking the cardid build.
- Also fixes path for deploy-to-test pkl module
=> PP-12423 Fix cardid job

ci/pkl-pipelines/common/shared_pipelines/init_lock_pools.pkl, ci/pkl-pipelines/pay-deploy/init-lock-pools.pkl, ci/pkl-pipelines/pay-dev/init-lock-pools.pkl, ci/scripts/init-lock-pools.sh, ci/tasks/init-lock-pools.yml
I had said I wasn't going to do this the right way initially, but actually it's far easier to get concourse to make the pools than it is for me to setup manual code commit access, so I just made the pipelines which provision the lock pools for the existing pipelines.
In order to use the concourse pool resource we have to init the pools. I took inspriation from:
https://github.com/alphagov/pay-concourse/blob/main/pipelines/concourse-deployer.yml#L459-L469
https://github.com/alphagov/pay-concourse/blob/main/pipelines/tasks/test-init-pool.yml
And also the docs for the concourse pool resource: https://github.com/concourse/pool-resource
This initialises pay-dev and pay-deploy pools (each team has it's own team) with pools that mimic the existing serial groups.
I've run the init job for the …
=> PP-12494: Add init lock pools pipeline in pay-deploy and pay-dev

ci/pipelines/build-and-push-java-lambdas.yml, ci/scripts/build-java-lambdas.sh, ci/tasks/build-java-lambdas.yml
Pipeline to test and build pay-java-lambdas JARs. Only the relevant submodules for the last pay-java-lambda's commit are built.
Pushing the JARs to the s3 bucket(s) is another task in itself and will be in the next PR.
See example output at https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/build-and-push-java-lambdas/jobs/build/builds/32:
```
FINAL BUILD OUTPUT:
ls -alh build/bin-ranges-diff
total 25M    
drwxr-xr-x    2 root     root        4.0K Apr 15 13:56 .
drwxr-xr-x    5 root     root        4.0K Apr 15 13:56 ..
-rw-r--r--    1 root     root       24.8M Apr 15 13:56 bin-ranges-diff-1.0.20240415135459.jar
ls -alh build/bin-ranges-promotion
total 25M    
drwxr-xr-x    2 root     root        4.0K Apr 15 13:56 .
drwxr-xr-x    5 root     root        4.0K Apr 15 …
```
=> PP-12537: Concourse pipeline to build pay-java-lambdas JARs

ci/pkl-pipelines/common/shared_pipelines/init_lock_pools.pkl, ci/pkl-pipelines/common/shared_resources_for_lock_pools.pkl
As well as setting up the lock pools, we need to actually add some locks into the pools which are the things that will actually be claimed and released.
I've tried this out and you can see a successful init in pay-deploy: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/init-lock-pools/jobs/initialise-pools/builds/14
I've also made a test-locks pipeline (not to be committed) which demonstrates it in use. All 3 jobs try and acquire the same lock, and then release it at the end. If you start them all you can watch them behave as expected (one claims the lock, the others wait until it's released before continuing) https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/test-locks
=> PP-12494: Add locks to pools on init

ci/pkl-pipelines/pay-deploy/deploy-to-production.pkl
Replace both the smoke test and deploy application serial groups with pool resource locking
=> PP-12494: Change deploy-to-prod locking to pool resource instead of serial group

ci/pkl-pipelines/common/shared_resources_for_lock_pools.pkl
Releasing the lock is ultra-important, so lets have 10 attempts at it in case of concourse weirdness
=> PP-12494: Have 10 attempts to release the locks

ci/pkl-pipelines/pay-dev/e2e-helpers.pkl
The resource "e2e-helpers-pipeline" was used prior to using the pipeline self update tasks, it no longer has any jobs using it and trying to set the piepline generates the error https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/e2e-helpers/jobs/update-pipeline/builds/1
```
error: invalid pipeline config:
invalid resources:
resource 'e2e-helpers-pipeline' is not used
```
=> BAU: Fix e2e-helpers pipeline

ci/pkl-pipelines/common/shared_pipelines/init_lock_pools.pkl, ci/pkl-pipelines/common/shared_resources_for_lock_pools.pkl
This adds job which allow us to force unlock a claimed lock.
You can see this where I got a test lock, then force unlcoked it. You can see the lock was claimed in https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/test-locks/jobs/test-lock-1/builds/2 at 16:55:01
Then force unlocked in https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/init-lock-pools/jobs/force-release-test-locks-lock/builds/3 at 16:55:07
Then the original test lock job https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/test-locks/jobs/test-lock-1/builds/2 fails (correctly) to release the (already force released) lock at 16:55:57 (See the first screenshot again)
=> PP-12494: Add jobs to force release locks

ci/pkl-pipelines/common/shared_resources_for_annotations.pkl, ci/pkl-pipelines/pay-deploy/deploy-to-production.pkl, ci/pkl-pipelines/pay-deploy/deploy-to-staging.pkl, ci/pkl-pipelines/pay-dev/deploy-to-perf.pkl, ci/pkl-pipelines/pay-dev/deploy-to-test.pkl
Send deployment events for all applications, across all environments.
This change adds to three pipelines, and modifies deploy-to-test to use the same mechanism as the other three.
[Here you can see toolbox being deployed by every pipeline](https://grafana.monitoring.pay-cd.deploy.payments.service.gov.uk/goto/52xoFHBIg?orgId=1), and [here](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/deploy-toolbox/builds/494) is an example build.
The pipeline diffs are all reporting as too big to show. Feel free to dig, reviewer, naturally, but I have manually checked them all. deploy-to-test just reorders a couple of attributes, for no obvious reason, and the others all add the same things.
=> PP-12316-deployment-events

ci/pkl-pipelines/pay-deploy/deploy-to-staging.pkl
In deploy-to-staging, replace smoke test and app-deploy serial groups with lock pools.
[Here](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/deploy-to-staging/jobs/deploy-toolbox-to-staging/builds/477) is a run of deploy-toolbox which waited for deploy-adminusers to complete and release the lock.
And [here](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/deploy-to-staging/jobs/smoke-test-products-on-staging/builds/259) is smoke-test-products waiting for smoke-test-adminusers to finish.
=> PP-12562-use-locks-in-deploy-to-staging

.github/workflows/_run-app-as-provider-contract-tests.yml, .github/workflows/_run-java-tests-and-publish-pacts.yml, .github/workflows/_run-provider-pact-tests-for-consumer.yml, .github/workflows/detect-secrets.yml
- Added reusable GitHub actions workflow to
- run integration tests for Java apps and publish pact (based on input param)
- run app as provider contract tests
- run pact provider tests for consumer
Used workflows in adminusers PR
- https://github.com/alphagov/pay-adminusers/pull/2486
- Test run: https://github.com/alphagov/pay-adminusers/actions/runs/8923066283 
- and a PR demonstrating failed pact tests on PR https://github.com/alphagov/pay-adminusers/pull/2491
=> PP-12584 Reusable workflows for Java tests

ci/pipelines/pr.yml
- Removed all (except E2E tests) adminusers tests from the concourse
- all tests will be run in GitHbu actions https://github.com/alphagov/pay-adminusers/pull/2492
=> PP-12570 Remove adminusers tests on PRs

.github/workflows/_run-node-cypress-tests.yml, .github/workflows/_run-node-install-and-compile.yml, .github/workflows/_run-node-unit-tests-and-publish-pacts.yml, .github/workflows/_validate_docker_image_is_manifest.yml
- Added reusable workflow to run node tests
- Added separate workflows for install-and-compile, unit-tests and cypress-tests so we can run unit-tests and cypress-tests in parallel
Selfservice [PR](https://github.com/alphagov/pay-selfservice/pull/4218) tests demonstrating use of workflows
https://github.com/alphagov/pay-selfservice/actions/runs/9005006437
=> PP-12588 Reusable GitHub action workflows for node apps

ci/pipelines/pr.yml
- Removed all (except E2E) cardId tests from Concourse
Depends on https://github.com/alphagov/pay-cardid/pull/1208
=> PP-12571 Remove cardId tests

ci/pipelines/pr.yml
- Removed toolbox tests from Concourse
- Depends on https://github.com/alphagov/pay-toolbox/pull/1813
=> PP-12580 Remove toolbox tests

ci/pipelines/pr.yml
- Removed all (except E2E) publicauth tests from Concourse
- Depends on https://github.com/alphagov/pay-publicauth/pull/1249
=> PP-12578 Remove publicauth tests

ci/pkl-pipelines/pay-deploy/deploy-to-production.pkl, ci/pkl-pipelines/pay-deploy/deploy-to-staging.pkl, ci/pkl-pipelines/pay-deploy/init-lock-pools.pkl, ci/pkl-pipelines/pay-dev/deploy-to-test.pkl, ci/pkl-pipelines/pay-dev/init-lock-pools.pkl
When I created the lock pool I've accidentally made staging and prod share the same deploy application and smoke test locks, they need to be suffixed with the env the pipeline is deploying to.
=> BAU: Fix shared lock pools so they are limited to a single pipeline

ci/pkl-pipelines/common/shared_resources_for_annotations.pkl, ci/pkl-pipelines/common/shared_resources_for_metrics.pkl
Lots of the send metrics tasks fail erroneously, so lets just try them 3 times to stop nonsense failed jobs.
=> BAU: 3 attempts to send metrics and annotations

ci/pipelines/pr.yml
Remove unit, integration, and pact tests for products, leaving e2e where it is.
=> PP-12575-remove-products-pact-tests

ci/pkl-pipelines/common/shared_resources_for_test_pipelines.pkl, ci/pkl-pipelines/pay-dev/e2e-helpers.pkl
The pr-ci pipeline (see https://github.com/alphagov/pay-ci/pull/1212) shares a fair bit of code with the e2e-helpers pipeline. This change breaks common code out of e2e-helpers into a library, which will also be used by pr-ci.
=> PP-12582-test-shared-resources

ci/pkl-pipelines/pay-deploy/infra-drift-detector.pkl, ci/pkl-pipelines/pay-dev/infra-drift-detector.pkl
We saw two failures on the assume-role step, so retry it. These tasks run very frequently, and if the state they check for occurs, they will fail repeatedly, so intermittent failures can be ignored. They also run quickly, so I think it's fine to add retries to the tests themselves. They make quite a few API calls, so the odd failure isn't impossible.
=> BAU-add-retries-to-sns-sub-check

ci/pkl-pipelines/common/shared_resources_for_test_pipelines.pkl, ci/pkl-pipelines/pay-dev/e2e-helpers.pkl, ci/pkl-pipelines/pay-dev/pr-ci.pkl, ci/scripts/check-pipelines-and-tasks.sh, ci/scripts/update-cardid-submodule.sh, ci/tasks/check-pipelines-and-tasks.yml, ci/tasks/update-cardid-submodule.yml
Re-implement the PR pipeline in Pkl. Makes these changes, which, I hope, are all an improvement.
* change filename base from `pr` to `pr-ci`, matching the pipeline name.
* replace bespoke "deploy pipeline" with the standard one from `common/`.
* calls the `pay-ci` resource `pay-ci` rather than `ci`, making `input_mapping` (mostly) redundant.
* breaks out embedded scripts into their own tasks and files.
* makes future removal of the cardid submodule very easy.
* calls frontend and connector `frontend` and `connector` rather than `card-frontend` and `card-connector`.
The only other changes should be trivial enforcements of consistency, like numbers of retries on CodeBuild jobs.
[Here is a successful cardid build (with submodule)](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pi …
=> PP-12582-migrate-pr-pipeline-to-pkl

.github/workflows/_run-app-as-provider-contract-tests.yml, .github/workflows/_run-java-tests-and-publish-pacts.yml, .github/workflows/_run-provider-pact-tests-for-consumer.yml
- Make JDK 21 the default version for all Java apps as all except Ledger are on Java 21. Ledger can still run tests with JDK21 where target release 11 and will soon be on Java21.
=> PP-12730 Make JDK 21 default version for Java tests

ci/pkl-pipelines/pay-dev/perf-tests.pkl
Create jobs for extended duration perf tests. This includes getting a set of assume role tokens which last for 2 hours instead of 1.
Most of the code change here is moving the execution of a simulation into a function so I can call it as standard or extended
=> PP-12684: Create jobs for extended perf tests

ci/pkl-pipelines/pay-dev/deploy-to-test.pkl
The adot deploy pipeline is supposed to build and push a candidate, then deploy toolbox with the candidate, and then run the adot-integration test, once that passes it should be retagged as release. In the conversion to pkl we've lost that behaviour and instead the build-and-push-adot-candidate also retags as XX-release.
This is made worse by the adot-integration-test job doing a push of its local XX-candidate image (which is architecture specific) as XX-release, meaning we overwrite the XX-release manifest with an XX-release intel image.
This PR changes build-and-push-adot-candidate to not retag as release, and updates the adot-integration-test to retag instead of pushing an image
This also means removing the ecr latest and dockerhub latest resources (since they aren't accessed via a PUT …
=> PP-12778: Fix adot deploy pipeline

ci/docker/node-runner/Dockerfile, ci/scripts/assume-role.js, ci/scripts/package-lock.json, ci/scripts/package.json, ci/tasks/assume-role.yml
- Updated assume-role task to use AWS SDK v3
- Updated Dockerfile to install required npm AWS SDK package for sts
This is to test IMDSv2 changes using the latest AWS SDK.
The current version results in the below error even though our code is similar to AWS docs https://docs.aws.amazon.com/code-library/latest/ug/sts_example_sts_AssumeRole_section.html
` Missing credentials in the config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1`
Tested the change with infra-detector job https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/infra-drift-detector/jobs/deploy-check-for-zendesk-unsubscribers/builds/26483 and notice `assume-role` task doesn't display `maintenance mode` warning anymore
=> PP-12740 Update assume role task to use AWS SDK v3

ci/docker/node-runner/Dockerfile, ci/pkl-pipelines/common/shared_resources_for_deploy_pipelines.pkl, ci/scripts/check-release-versions.js, ci/scripts/package-lock.json, ci/scripts/package.json, ci/scripts/run-ecs-db-migration.js, ci/scripts/wait-for-deploy.js, ci/tasks/check-release-versions.yml, ci/tasks/wait-for-deploy.yml
- Updated ECS scripts to use AWS SDK v3
=> PP-12783 Update ECS scripts to use AWS SDK v3

ci/pkl-pipelines/pay-deploy/concourse-runner.pkl
Leftover from the Java 21 upgrade - our guinea pig app (adminusers) is now on Java 21 so the old concourse-runner image test will fail.
=> BAU: Run concourse-runner tests with Java 21

ci/pkl-pipelines/pay-deploy/concourse-runner.pkl
https://github.com/alphagov/pay-ci/pull/1245 didn't quite work as we mislabelled the image source.
=> BAU: Run concourse-runner tests with Java 21 again

ci/pkl-pipelines/pay-deploy/prometheus-pushgateway.pkl
Modifies the prometheus-pushgateway pipeline to copy a multiarch ADOT from staging, and ARM version of pushgateway.
[Here's a Concourse run of the modified job](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/prometheus-pushgateway/jobs/push-adot-to-deploy-ecr/builds/23).
Corresponds to [this change in pay-infra](https://github.com/alphagov/pay-infra/pull/4861).
=> PP-12756-migrate-pushgateway-to-arm

ci/docker/pact-broker/Dockerfile
locally I ran up a pact broker of our current version (2.54.0.0), ran consumer tests for products-ui and ledger, and provider tests for connector and products and everything is happy on the current version (connector of course complains some consumers haven't got any pacts published, but the ledger ones all pass)
Then I updated the pact broker to the very latest version (keeping the same local postgres db), it started up, migrated the db, and I can still successfully run all the tests and publish all the pacts again
=> PP-12835: Update pact broker version

ci/tasks/create-notification-snippets.yml
Releases are failing because `19-candidate` is not a metric. Rather than just stripping `-release` from tags, now strip dash-anything. Same for adot, nginx, and forward-proxy.
=> BAU-fix-broken-metrics

ci/docker/concourse-runner/Dockerfile
- Install docker-scout in concourse-runner as per https://github.com/docker/scout-cli?tab=readme-ov-file#script-installation so we can run interval vulnerability scans
- Had to set DOCKER_HOME and RUN mkdir as otherwise build is failing with error `docker is not installed; refusing to install to '/root/.docker/cli-plugins' `
- Build output
=> PP-12758 Install docker-scout

ci/docker/concourse-runner/Dockerfile, ci/scripts/test-concourse-runner.sh
- Upgrades concourse-runner JDK version to 21 as we no longer have any apps using Java 11.
- We can remove concourse-runner-with-21 and use concourse-runner everywhere.
=> PP-12758 Upgrade concourse-runner JDK to 21

ci/pkl-pipelines/common/PayResources.pkl, ci/pkl-pipelines/common/shared_resources_for_times.pkl, ci/pkl-pipelines/pay-deploy/internal-vulnerability-scan.pkl
Use our fork of the cron resource https://github.com/alphagov/cron-resource to trigger the internal vulnerability scan to run quarterly
I set the cron expression to `39 14 19 JUL,MAR,JUN,SEP,DEC *` in order to test that this works. It triggered this run https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/internal-vulnerability-scan/jobs/run-vulnerability-scan/builds/4 which you can see triggered as expected
=> PP-12909: Run internal vulnerability scan quarterly

ci/pkl-pipelines/pay-deploy/internal-vulnerability-scan.pkl, ci/scripts/run-vulnerability-scan/create-jira-issue.sh, ci/tasks/create-vulnerability-scan-jira-issue.yml
When storing these details in pay-low-pass it will be a pain when rotating if we store the username, token, and api key, and also a base64 encoded concatenation of the username and api key. So instead accept JIRA_API_USERNAME and JIRA_API_TOKEN and base64 encode them in the script.
=> PP-12908: Use Jira API username and token, and base64 encode it in the script

.pre-commit-config.yaml, .secrets.baseline, ci/scripts/run-vulnerability-scan/create-jira-issue.sh, ci/tasks/create-vulnerability-scan-jira-issue.yml
To use a script in pay-ci it needs pay-ci as an input
This ran successfully https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/internal-vulnerability-scan/jobs/run-vulnerability-scan/builds/9
=> PP-12908: Fix create-jira-story task

.gitignore, ci/scripts/run-vulnerability-scan/scan.sh
- Updated internal vulnerability scan script so it can be run manually if needed
- From the pay-ci root, run
- `cd ci/scripts/run-vulnerability-scan`
- `export MANUAL_RUN=true && aws-vault exec staging -- bash scan.sh`
- Report will be in the `ci/scripts/run-vulnerability-scan/reports` folder
Concourse job still runs as expected https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/internal-vulnerability-scan/jobs/run-vulnerability-scan/builds/12
=> PP-12912 Updates to run internal vulnerability scan manually

ci/pkl-pipelines/common/shared_pipelines/init_lock_pools.pkl
The lock pool repos get massive very quickly, reinit them every day to keep them trim and tidy
```diff
resources:
resource every-day-at-2-30 has been added:
+ icon: alarm
+ name: every-day-at-2-30
+ source:
+   location: Europe/London
+   start: "2:30"
+   stop: "2:40"
+ type: time
jobs:
job force-release-deploy-application-staging-lock has changed:
name: force-release-deploy-application-staging-lock
plan:
- - get: get-already-claimed-deploy-application-staging-lock
-   resource: lock-pool-deploy-application-staging
+ - in_parallel:
+     steps:
+     - get: get-already-claimed-deploy-application-staging-lock
+       resource: lock-pool-deploy-application-staging
+     - get: every-day-at-2-30
+       trigger: true
- attempts: 3
params:
release: …
```
=> BAU: Reinit lock pools daily

ci/pkl-pipelines/common/shared_pipelines/init_lock_pools.pkl
Sigh, I put the trigger on the wrong job, it was on the force unlock, instead of re-init.
I've applied this change to https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/init-lock-pools?group=initialise-pools and it is now correct.
So sorry for the need for a re-review
=> BAU: Apply daily schedule to correct job

ci/pkl-pipelines/common/shared_resources_for_times.pkl
The icon I picked for this previously is a material design icon, but not one concourse supports. This changes it to one that is supported. I've applied this to test: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/internal-vulnerability-scan
=> BAU: Fix quarterly icon

ci/pkl-pipelines/pay-deploy/internal-vulnerability-scan.pkl
Update `internal-vulnerability-scan` to send appropriate slack messages on success, failure an error.
On success send to #govuk-pay-pci and include a link to the created Jira ticket. On failure and error send to both `#govuk-pay-starling` and `#govuk-pay-pci`
=> PP-12760: Send slack message on vuln scan

ci/pkl-pipelines/common/shared_pipelines/pkl_pipeline_changes.pkl
The pkl pipeline changes job doesn't run when things are more than 1 level deep.
https://github.com/alphagov/pay-ci/blob/master/ci/pkl-pipelines/common/shared_pipelines/pkl_pipeline_changes.pkl#L18
```
["paths"] = new Listing<String> {
"ci/pkl-pipelines/**/*.pkl"
}
```
Does not work as I expected, it does not go more than 1 level deep, so it works for
* `ci/pkl-pipelines/pay-dev/foo.pkl`
* `ci/pkl-pipelines/common/bar.pkl`
bit it does not work for
* `ci/pkl-pipelines/common/shared_pipelines/baz.pkl`
According to the [docs of the github-pr resource](https://github.com/cloudfoundry-community/github-pr-resource) this can be a prefix as well as a glob pattern
```
Only produce new versions if the PR includes changes to files that match one or more glob patterns or prefixes.
```
So switch the …
=> BAU: Fix pkl pipeline changes paths

ci/pkl-pipelines/pay-deploy/pay-js.pkl
Begin to align on the use of the `PayResources.PayGitHubResource` class rather than a function. The use of objects/classes seems favoured by the pkl maintainers over functions [1]. It also allows us to make greater use of the type safety, simpler maintenance and simpler syntax.
[1]:https://github.com/apple/pkl/discussions/487#discussioncomment-9382697
What are peoples' thoughts on this? If we're agreed then I don't mind doing some refactoring as it'll help me continue to get comfortable with `pkl`
=> Refactor Pay-Js To Use Class Rather Than Function

ci/pkl-pipelines/common/PayResources.pkl, ci/pkl-pipelines/common/pipeline_self_update.pkl, ci/pkl-pipelines/common/shared_resources.pkl, ci/pkl-pipelines/pay-deploy/concourse-resources.pkl, ci/pkl-pipelines/pay-deploy/deploy-to-production.pkl, ci/pkl-pipelines/pay-deploy/deploy-to-staging.pkl, ci/pkl-pipelines/pay-deploy/detect-secrets.pkl, ci/pkl-pipelines/pay-deploy/infra-drift-detector.pkl, ci/pkl-pipelines/pay-deploy/pact-broker.pkl, ci/pkl-pipelines/pay-deploy/prometheus-pushgateway.pkl, ci/pkl-pipelines/pay-dev/deploy-to-perf.pkl, ci/pkl-pipelines/pay-dev/deploy-to-test.pkl, ci/pkl-pipelines/pay-dev/e2e-helpers.pkl, ci/pkl-pipelines/pay-dev/infra-drift-detector.pkl, ci/pkl-pipelines/pay-dev/perf-tests.pkl
The use of objects/classes seems favoured by the pkl maintainers over functions [1]. It also allows us to make greater use of the type safety, simpler maintenance and simpler syntax.
[1]: https://github.com/apple/pkl/discussions/487#discussioncomment-9382697
Continues on the path to align on using classes/objects (in this case `PayGitHubResource`) rather than a function as started in https://github.com/alphagov/pay-ci/pull/1282. The net affect should be no changes, so although this PR includes many files, it _should_ be simple to review...
=> Use PayGitHubResource Class

ci/pkl-pipelines/pay-dev/deploy-to-test.pkl
Devs need to be able to run the egress proxy as part of pay local. This means it needs to be in dockerhub. I've already opened a PR for the candidate images to be pushed to dockerhub. This PR will tag those post-build as latest & release
=> PP-13049: Retag egress in dockerhub as release

ci/pkl-pipelines/pay-dev/perf-tests.pkl
Noticed this typo "Execition" instead of "Execution" when looking for references to ci.
=> BAU: Fix typo

.github/workflows/_validate_docker_image_is_manifest.yml
We're introducing use of scratch container bases for some containers. This change updates the manifest check to allow for scratch images.
You can [see a working execution of this test](https://github.com/alphagov/pay-aws-bastion/actions/runs/10454911480/job/28948663783?pr=2) (run using this branch). This check checked both the build container definition and the scratch definition (which is also the reason we want to run this on Dockerfiles which end with a scratch container)
=> PP-12812: Make manifest check support scratch images

ci/pkl-pipelines/common/shared_resources_for_multi_arch_builds.pkl, ci/pkl-pipelines/pay-dev/deploy-to-test.pkl, ci/pkl-pipelines/pay-dev/e2e-helpers.pkl
I need to create 2 new multi arch builds, so I'm refactoring the current ones to use a shared component which I can reuse.
In this instance there will be a small change, that is to give some of the e2e helper builds 3 attempts, but I'd rather standardise on the builds rather than special case, especially where it isn't necessary.
=> PP-12812: Extract multi arch candidate build

ci/pkl-pipelines/common/shared_resources_for_multi_arch_builds.pkl, ci/pkl-pipelines/pay-deploy/deploy-to-production.pkl, ci/pkl-pipelines/pay-deploy/deploy-to-staging.pkl, ci/pkl-pipelines/pay-dev/deploy-to-test.pkl, ci/pkl-pipelines/pay-dev/e2e-helpers.pkl
Extract the manifest retag code into the shared multi arch module.
I renamed the candidate_image_tag variable in e2e helpers since that's the only place where it was different and that allowed me to standardise the shared code more.
Although the yaml for deploy-to-production is different, it's just a reordering of some keys and the actual pipeline is no changes.
=> pp-12812: Refactor of image retag to use shared code

ci/pkl-pipelines/pay-dev/e2e-helpers.pkl
This refactor:
* Puts related jobs in a groups to make it easier to find the right stuff in the pipeline
* Creates local types to define multi arch images to build, and images to copy from dockerhub to ecr
* Uses lists of those types to generate the resources/groups/jobs in loops
This does produce a number of changes since the jobs were not identical before, but it's almost all ordering of tasks. I took the best from all the jobs and made as much run in parallel as possible.
The one extra thing is it's adding in a zap test for stubs, but lets make them the same as each other instead of special casing that
It also (by coincidence) fixes the notification messages of a number of jobs which incorrectly listed the tags that were being copied
Successful builds for the jobs changnig:
* build …
=> PP-11913: Refactor e2e-helpers

ci/pkl-pipelines/common/PayResources.pkl, ci/pkl-pipelines/common/shared_resources.pkl, ci/pkl-pipelines/common/shared_resources_for_deploy_pipelines.pkl, ci/pkl-pipelines/common/shared_resources_for_multi_arch_builds.pkl, ci/pkl-pipelines/pay-dev/bastion.pkl, ci/pkl-pipelines/pay-dev/deploy-to-test.pkl, ci/pkl-pipelines/pay-dev/e2e-helpers.pkl
* Refactor the multi arch build jobs to be available in shared code
* Also extract some of the common parsing tasks to be available in shared code
* Use the shared multi arch build jobs to build the bastion
I've applied the bastion pipeline and you can see a successful build https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/bastion/jobs/build-and-push-bastion-release/builds/2
The e2e-helpers diff is just changnig the wording of the notifications slightly to make them more generalised (they always link to the specific build though, so it's only the fluff that's generalised, not the concrete actions)
=> PP-12812: Refactor bastion build to use shared code

ci/pkl-pipelines/common/shared_resources_for_terraform.pkl, ci/scripts/find-terraform-version.sh, ci/tasks/find-terraform-version.yml
I need to add a new deploy-bastion.yml task. All the deploy-<app> tasks hardcode the terraform version, and I'm making that problem worse.
We really need to be updating our terraform version more often but right now it's a huge pain, so I'm adding (thanks to pkl it's easy) loading the terraform version from the .terraform-version file.
All the terraform is run using the hashicorp/terraform docker image, so we can easily vary the tag loaded by loaded var
The script I've added, you tell it where the TF root is, and it reverse recurses up the tree right to `pay-infra/` looking for .terraform-version files (the same way tfenv does). As soon as it finds one it stops and outputs it.
The shared pkl lets you add it easily to an existing pipeline like:
```pkl
jobs {
new {
name = "deploy-bastion" …
```
=> Pp 12812/dynamically load tf version

ci/pipelines/deploy-smoke-tests.yml, ci/pipelines/stubs.yml, ci/pkl-pipelines/common/shared_resources_for_deploy_pipelines.pkl, ci/pkl-pipelines/pay-deploy/deploy-to-production.pkl, ci/pkl-pipelines/pay-deploy/deploy-to-staging.pkl, ci/pkl-pipelines/pay-deploy/infra-drift-detector.pkl, ci/pkl-pipelines/pay-deploy/pact-broker.pkl, ci/pkl-pipelines/pay-dev/deploy-to-perf.pkl, ci/pkl-pipelines/pay-dev/deploy-to-test.pkl, ci/pkl-pipelines/pay-dev/infra-drift-detector.pkl, ci/tasks/deploy-app-with-adot.yml, ci/tasks/deploy-app.yml, ci/tasks/deploy-egress.yml, ci/tasks/deploy-frontend-with-adot.yml, ci/tasks/deploy-frontend.yml, ci/tasks/deploy-pact-broker.yml, ci/tasks/deploy-scheduled-tasks.yml, ci/tasks/deploy-stubs.yml, ci/tasks/deploy-webhooks-egress.yml
For all deployments, load the TF version, then use it instead of hardcoding for 1.3.7.
Where it's still a yml pipeline I just used the yml output generated in the pkl
=> Pp 12812: Use the tf version in pay-infra for all deployments

ci/pkl-pipelines/common/shared_pipelines/bastion.pkl, ci/pkl-pipelines/common/shared_resources.pkl, ci/pkl-pipelines/common/shared_resources_for_deploy_pipelines.pkl, ci/pkl-pipelines/pay-deploy/bastion.pkl, ci/pkl-pipelines/pay-dev/bastion.pkl
Add bastion deployment pipelines which go:
```
pay-dev:
build in test -> deploy in test-12 -> push to staging
-> deploy in test-perf-1
pay-deploy:
deploy in staging -> push to prod -> deploy in prod -> push to deploy -> deploy in deploy  
```
Rather than making a new deploy-x yaml and script I just used the fact the hashicorp terraform container can be configured more easily via some simple env vars, which saves on task yamls and extra scripts
Given there must be a pipeline in each team I refactored the existing stuff to be in a shared pipeline which is configured with a small amount of config in each teams pipeline
I appled these and you can see all jobs working as expected:
[pay-dev/bastion](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/bastion) …
=> PP-12812: Add bastion deployment pipelines

ci/pkl-pipelines/common/shared_resources_for_deploy_pipelines.pkl, ci/pkl-pipelines/pay-deploy/deploy-to-production.pkl, ci/pkl-pipelines/pay-deploy/deploy-to-staging.pkl, ci/pkl-pipelines/pay-dev/deploy-to-test.pkl
When we deploy, we occasionally need to be able to disable the rollback version check, this is to allow us to deploy an old version in an emergency.
When we migrated to pkl we didn't make it easy to disable the check.
This PR enables configuring on a per-app per-env basis whether the version check should be performed. It defaults to enabled for everything.
The following change would disable it for connector in production, but is not set in this PR:
```
$ git diff
diff --git a/ci/pkl-pipelines/common/shared_resources_for_deploy_pipelines.pkl b/ci/pkl-pipelines/common/shared_resources_for_deploy_pipelines.pkl
index 4d0fade..cdd2a41 100644
--- a/ci/pkl-pipelines/common/shared_resources_for_deploy_pipelines.pkl
+++ b/ci/pkl-pipelines/common/shared_resources_for_deploy_pipelines.pkl
@@ -49,7 …
```
=> incident-2024-09-02: Allow disabling version rollback check for apps

ci/pkl-pipelines/pay-deploy/deploy-to-production.pkl, ci/pkl-pipelines/pay-deploy/deploy-to-staging.pkl, ci/pkl-pipelines/pay-dev/deploy-to-perf.pkl, ci/pkl-pipelines/pay-dev/deploy-to-test.pkl
The path for finding the terraform version for scheduled http tasks was missing the preceding pay-infra. This caused deployment failure as seen here: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/deploy-scheduled-tasks/builds/181
This PR fixes it for all envs. I applied the deploy-to-test pipeline and reran with the same inputs, and you can see a working deploy here: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/deploy-scheduled-tasks/builds/181.1
=> BAU: Fix path for scheduled http tasks

ci/pkl-pipelines/pay-deploy/internal-vulnerability-scan.pkl, ci/scripts/run-vulnerability-scan/display-vulnerability-scan-result.sh, ci/tasks/display-vulnerability-scan-result.yml
To allow for less noisy rescans add the ability to run a scan and just print the results. I also got it to display the scan in the version of the job that creates a jira story.
You can see the result of applying and running this here: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/internal-vulnerability-scan/jobs/run-internal-vulnerability-without-creating-jira-ticket/builds/2
=> PP-13158: Allow running and displaying a vuln scan without Jira story

ci/docker/concourse-runner/Dockerfile
Bump the version of docker scout cli
When I did a test build docker also gave me a warning about using CMD of the non-json format:
```
1 warning found (use docker --debug to expand):
- JSONArgsRecommended: JSON arguments recommended for CMD to prevent unintended behavior related to OS signals (line 59)
```
In our case it doesn't matter, but I'd rather not have a noisy warning all the time, it will make it harder to heed warnings that do matter, so change it anyway.
=> Pp 13158/bump docker scout cli version

ci/pkl-pipelines/pay-dev/init-lock-pools.pkl
This lock pool isn't used. The perf tests pipeline is still using serial groups and is fine to keep doing so
=> BAU: Remove unused lock pool

ci/pkl-pipelines/pay-dev/perf-tests.pkl, ci/scripts/start-rds-instance.sh, ci/scripts/stop-rds-instance.sh, ci/tasks/start-rds-instance.yml, ci/tasks/stop-rds-instance.yml
Start and stop db scripts both aren't as robust as we would hope.
After waiting for the db to be available with `aws rds wait db-instance-available --db-instance-identifier ...` the dbs are still sometimes in another state (like configuring enhanced monitoring, or backing up`.
On shutdown, since the dbs aren't online all that often in perf env they are sometimes configuring enhanced monitoring, rebooting, or backing up, when we try and shut them down.
So in all these cases we'll wait while it happens and just keep polling the state.
I've extracted the scripts into their own files (as agreed within the team as general practice).
Sometimes the STS tokens also time out, so set extended duration for everything that scales the databases
I ran scale up dbs …
=> PP-13257: Make start and stop DB more robust

.github/workflows/_run-codeql-scan.yml
For Toolbox, the typescript files we want to scan are in a different folder (`src`).
This change adjusts the workflow to handle Typescript scans as well as Node.
Corresponding Toolbox PR: https://github.com/alphagov/pay-toolbox/pull/1857
=> PP-12244: Handle Typescript repositories in CodeQL shared workflow

ci/docker/concourse-runner/Dockerfile
- Installs session-manager-plugin in pay-concourse-runner to test bastion
- build works
```
➜  concourse-runner git:(pp_13142_install_session_manager) docker build -t governmentdigitalservice/pay-concourse-runner:local .
[+] Building 1.9s (20/20) FINISHED                                                                                                                         docker:desktop-linux
=> [internal] load build definition from Dockerfile                                                                                                                       0.0s
=> => transferring dockerfile: 2.42kB                                                                                                                                     0.0s
=> [internal] load metadata for …
```
=> PP-13142 Install session-manager-plugin

ci/pkl-pipelines/common/shared_pipelines/bastion.pkl
- Updates bastion pipeline to build candidate image, run E2E test and retag image as release before deploying to test
- Build candidate: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/bastion/jobs/build-and-push-bastion-candidate/builds/3
- E2E test and retag as release - https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/bastion/jobs/bastion-e2e-test-and-retag-image-as-release/builds/1
=> PP-13142 Run Bastion E2E test before deploying to test

ci/pkl-pipelines/pay-deploy/deploy-to-production.pkl, ci/pkl-pipelines/pay-deploy/deploy-to-staging.pkl, ci/pkl-pipelines/pay-dev/deploy-to-perf.pkl, ci/pkl-pipelines/pay-dev/deploy-to-test.pkl
We need additional tags on the release annotations.
The ability to filter for annotations is _extremely_ limited, and you can't do any kind of transform, and values based on chained variables don't update. So we need to be able to filter on what is actually selectable in the dashboards. In some cases this is the cluster name (`<env>-fargate`), in some cases the account name.
=> PP-13286: Send additional tags on release annotations

.github/workflows/_run-dependency-review.yml
Introduce [actions/dependency-review](https://github.com/actions/dependency-review-action) as a shared workflow, based on [GOV.UK's equivalent shared workflow](https://github.com/alphagov/govuk-infrastructure/blob/main/.github/workflows/dependency-review.yml).
This is intended to replace Snyk PR checks which detect if a vulnerable dependency is about to be introduced via a pull request. This is currently only available for our public repositories. 
GOV.UK's implementation includes post-merge checks on the default branch. I've intentionally left these out, as these are covered by existing Dependabot alerts and I want to closely replicate our existing workflow.
I've added in two inputs to allow overrides for:
- minimum severity level 
- whether to 'warn only' and not block merging 
I'll …
=> PP-12686: Shared workflow for dependency reviews on PRs

.github/workflows/test-run-codebuild.yml, .github/workflows/test-semver.yml
This resolves the remaining Node16 deprecation warnings on shared workflows.
=> PP-12244: Update checkout and setup-node actions

ci/docker/node-runner/Dockerfile
The downgrade check runs on the node-runner image and now needs to use the fly cli to check if a downgrade release is the latest enabled release. This add fly using the same process as per the concourse-runner image.
Built locally and it seems to work...
```
➤➤ node-runner $ docker build -t my_node_runner .
[+] Building 29.7s (15/15) FINISHED
.....
➤➤ node-runner $ docker run --rm my_node_runner which fly
/usr/local/bin/fly
```
=> Add Fly Cli to Node-Runner

ci/pkl-pipelines/pay-dev/perf-tests.pkl, ci/scripts/perf-test-cleanup/check-for-running-db.sh, ci/tasks/perf-test-cleanup/check-for-running-db.yml
Regularly the daily performance tests fail to start, the DB starts, and is available, and then before the DB cleanup task runs (which checks for connector DB being available) the DB goes into another state (e.g. backing-up).
So lets wait for that to complete, we don't want random reboots etc during the performance test or our baseline will be invalid.
I've also extended the duration of the session for the role doing this work since they may have to wait an extended period for the RDS instance to get to a settled state.
I applied this (amended to point pay-ci to this PR branch) and [ran the scale-and-run-all-simulations build](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/perf-tests/jobs/scale-and-run-all-simulations/builds/912)
I discovered I also needed …
=> BAU: Wait for DBs to be available before clearing DB

ci/scripts/support-rota-notification/index.js
- Skips updating in-hours topics/sending notifications during bank holidays
- Notifies all on-call engineers (Saturday & Sunday) to triage alerts
=> BAU - Check for bank holidays for support notifications

.github/workflows/_validate_docker_image_is_manifest.yml
Only check images that are remote images, not that are references to other layers in the same manifest
=> BAU: Don't validate images that are layers in the same Dockerfile

ci/pkl-pipelines/pay-deploy/internal-vulnerability-scan.pkl
Required to run the shell script it contains.
To fix this: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/internal-vulnerability-scan/jobs/create-network-review-jira-story/builds/1
=> Add Pay-CI To Create Network Review Task

ci/tasks/create-network-review-jira-issue.yml
The 'reports' input was a copy and paste error from a similar task.
To fix: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-deploy/pipelines/internal-vulnerability-scan/jobs/create-network-review-jira-story/builds/2
=> Remove Erroneous Input to Create Network Task

.github/workflows/_create-alpha-release-tag.yml, .github/workflows/_run-app-as-provider-contract-tests.yml, .github/workflows/test-run-codebuild.yml
- Updates a few shared workflows to run on `ubuntu-latest` as Ubuntu 20.04 will be unsupported soon.
- The rest of the workflows use ubuntu-latest
=> PP-13652 Update shared workflows to run on ubuntu-latest

.github/dependabot.yml, ci/docker/concourse-runner/Dockerfile
The docker-in-docker image for `concourse-runner` was pinned to avoid major version updates in January 2024, as v25 introduced incompatibilities with our pact tests (that run using this image). As such we have fallen behind with patches, including the recent [OpenSSL CVE](https://openssl-library.org/news/secadv/20250211.txt).
Since January 2024 we have upgraded our apps to Java 21 and Pact v4, which we believe will address the issue with the pact tests. We also introduced a PR check for this image in February 2024, that runs the pact tests against Adminusers on Concourse using the built `concourse-runner` image, so it should give a good indication of whether this hypothesis is true [EDIT: the tests pass 🎉 ].
=> PP-13604 Upgrade docker-dind base image for concourse-runner

.github/dependabot.yml, ci/docker/concourse-runner/Dockerfile
Reverts alphagov/pay-ci#1361
Unfortunately it looks like this still a breaking change.
While the e2e tests pass, it looks like images built with this version of concourse-runner are missing a layer and cannot be pushed to ECR. [See an example here](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/pr-ci/jobs/ledger-e2e/builds/2467).
=> Revert "PP-13604 Upgrade docker-dind base image for concourse-runner"

ci/tasks/endtoend/card/docker-compose.yml, ci/tasks/endtoend/products/docker-compose.yml, ci/tasks/endtoend/zap/docker-compose.yml
Over the weekend AWS' AMD64 codebuild environment started throwing errors when you try to set mem_limits in docker-compose.
Support suggested removing them as a workaround, so for now we will temporarily remove them to allow our deployments to continue while we continue to engage with AWS support
Having applied this to a temporary branch you can see a connector end to end run passing: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/deploy-to-test/jobs/run-connector-e2e/builds/1394
=> [PP-13914] Remove mem_limit temporarily

ci/scripts/test-logging-pipeline/index.js, ci/scripts/test-logging-pipeline/package-lock.json, ci/scripts/test-logging-pipeline/package.json
- Added node script to send test logs for CloudTrail and S3 log events, and check for logging-related alarms in the ALARM state.
Tested locally
`➜  test-logging-pipeline git:(pp_13784_e2e_test_logging_pipeline) AWS_ACCOUNT_ID=[REDACTED] AWS_ACCOUNT_NAME=[REDACTED] S3_OBJECT_NAME=2025-04-15-00-00-00-2AD1799A1B3E2A9D aws-vault exec [env] -- node index.js`
```
- Sending CloudTrail log events -
Sent CloudTrail log events
- Sending test S3 Event notifications to SQS -
Sent test S3 Event notifications to SQS
Waiting 120 seconds before querying for any CloudWatch alarms in ALARM state
5 seconds elapsed
10 seconds elapsed
15 seconds elapsed
20 seconds elapsed
25 seconds elapsed
30 seconds elapsed
35 seconds elapsed
40 seconds elapsed
45 seconds elapsed
50 seconds elapsed
55 seconds elapsed
60 …
```
=> PP-13784 Script to test logging pipeline

ci/scripts/test-logging-pipeline/index.js
- Increases wait time to 3 mins to account for any buffering/async delays before querying CloudWatch alarms
=> PP-13784 Increase logging e2e test wait time

ci/pkl-pipelines/pay-dev/deploy-to-test.pkl
Reverts alphagov/pay-ci#1381
We have decided instead to remove the zap tests for selfservice from the end to end tests
=> Revert "PP-13989: Add ZAP tests to selfservice end to end tests"

ci/pkl-pipelines/pay-dev/deploy-logging-pipeline.pkl, ci/tasks/deploy-logging-pipeline.yml
Adds the deployment of the logging pipeline to the test account. There are some significant differences between dev and test, along with some pending changes to run the E2E against test and not dev, so unfortunately making use of the `for` loop by adding `test` to the list of `accounts` wasn't practical. There are undoubtedly opportunities for re-use and abstraction, especially using `pkl`, but let's do that as part of the pending refactoring when we have a clearer idea. This PR does not change what we currently do to dev, that will change in a future ticket.
The first two commits includes some minor refactoring before adding the deployment to the test account in the third.
=> Pp 13785 deploy logging test

ci/pkl-pipelines/pay-deploy/concourse-resources.pkl
Now our fork of pool-resource is archived we no longer need the build pipeline
=> PP-13959: Remove pool-resource build

ci/pkl-pipelines/pay-dev/deploy-logging-pipeline.pkl
- Reordered logging pipeline jobs so infra/lambda changes are deployed in test-e2e env, e2e tests are run, and then changes are deployed to other accounts/environments in parallel.
_new pipeline_
=> PP-14017 Reorder logging pipeline jobs

ci/pkl-pipelines/pay-dev/deploy-logging-pipeline.pkl
Add a grafana annotation when we deploy the logging pipelines with tags of
* logging-release
* `<env>` (where it's an env deployment)
* `<account>`
(Due to the limited filtering capabilities in grafana lookups of annotations it's better to have both account and env)
Running a job with an env:
Running a job without an env:
Both visible in a complete list of annotations shown in grafana
=> [PP-13972] Add grafana annotations to logging pipeline deploys

ci/pkl-pipelines/pay-deploy/deploy-logging-pipeline.pkl
- Added `deploy-pay-cd` (which ships Concourse & Prometheus logs) environment to the deploy logging pipeline
=> PP-13789 Added deploy-pay-cd env to logging pipeline

ci/tasks/endtoend/zap/docker-compose.yml
See description in https://github.com/alphagov/pay-infra/pull/5196 for background details.
This PR switches the ZAP suite of the end to end tests to use the duplicated Docker image now held in the new `govukpay/endtoend-zap` ECR repository. I've hardcoded the repository name and image tag for now.
In theory this should be a no-op as the image itself has not changed.
=> PP-14175: Use dedicated endtoend-zap Docker image for ZAP tests

ci/pkl-pipelines/pay-dev/e2e-helpers.pkl
Splits the `end-to-end` group of the [e2e-helpers pipeline](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/e2e-helpers?group=end-to-end) into two jobs:
- building, testing and promoting a candidate image from the new pay-endtoend-zap repo
- building, testing and promoting a candidate image from the original pay-endtoend repo image
Other things to note:
- The ECR and Docker Hub repositories are already in place
- The CodeBuild job should not need any changes or additional permissions
- The default branch for the new repo is `main` instead of `master`
- I've only included the ZAP suite in the new set of post-merge tests, and removed it from the original set.
If there's a better way to organise the resources within the file (or avoid duplication), I'm happy to move …
=> PP-14175: Split out endtoend-zap image build into separate Concourse job

ci/pkl-pipelines/pay-dev/pr-ci.pkl
Creates the equivalent PR checks for pay-endtoend-zap, based on the [PR checks for pay-endtoend](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/pr-ci?group=end_to_end).
The new repo will use the same 'config check' configuration as the existing pay-endtoend repo (i.e. trigger if there are relevant changes within pay-ci).
I've also amended pay-endtoend to only run the `card` and `products` suite of tests, ready for removing ZAP from that repo.
=> PP-14175: Run PR checks against pay-endtoend-zap repository

.github/workflows/_run-node-cypress-tests-rebrand.yml
- New workflow to only run the Cypress tests for the new branding.
- This workflow is run once the main Cypress test suite workflow is done.
- We need a separate workflow for the rebranding tests because they need the Cypress server to run with ENABLE_FLAG=true
- This will be used temporarily until the new branding is live.
- Once it is live, the main Cypress tests will be updated and then this workflow can be removed.
- This is a clone of the existing Cypress tests workflow but runs the following commands instead:
- npm run cypress:server-rebrand
- npm run cypress:test-rebrand -
=> PP-13898 Add new GHA workflow - run Cypress branding tests

.github/workflows/_validate_docker_image_is_manifest.yml, .github/workflows/check-pact-broker-base-image-is-manifest.yml
- Changes to support manifest validation for pact-broker image reference, which follows a different pattern from references in other apps
**Working action**
https://github.com/alphagov/pay-ci/actions/runs/16495643066/job/46640590907?pr=1428
**Action that failed for an invalid Docker manifest**
https://github.com/alphagov/pay-ci/actions/runs/16495704508/job/46640789217?pr=1428
=> PP-12801 Update Validate docker image is manifest action for pactbroker

ci/pkl-pipelines/pay-deploy/deploy-to-production.pkl
- temporarily disable the Worldpay recurring card payment smoke test in production
- to be re-enabled in https://payments-platform.atlassian.net/browse/PP-14366
=> PP-14368 temporarily disable worldpay recurring st
